### ISSUE TITLE
Alpha matting doesn't work in rembg-server

### ISSUE THREAD

**Issue by serzhb** [danielgatis/rembg#100]
Hi,

I used this request to remove background with alpha matting:
http://localhost:5000/?a=1&ae=15&url=https://raw.githubusercontent.com/danielgatis/rembg/master/examples/car-2.jpg

But I got the same result as i got before when i didn't use a/ae parameters. 

Am I wrong or the rembg-server is not working correctly?

**Comment by danielgatis** [comment]
```
Am I wrong or the rembg-server is not working correctly?
```

It's working. Checkout this line:
https://github.com/danielgatis/rembg/blob/master/src/rembg/cmd/server.py#L60
