### ISSUE TITLE
Wrong env variable for u2net_human_seg model

### ISSUE THREAD

**Issue by Gubarev** [danielgatis/rembg#103]
Currently `U2NET_PATH` env variable can be used to define path to `u2net_human_seg` model. However it seems like env variable should be different to distinguish path to `u2net` and `u2net_human_seg`.

I propose something like: `U2NET_HUMAN_SEG_PATH`

https://github.com/danielgatis/rembg/blob/94ce485c8ca2812a3042fc10d3fdbb89fddd2aee/src/rembg/u2net/detect.py#L92

**Comment by danielgatis** [comment]
the rembg loads only one model per run, so it is ok the same `env var` name.
