### ISSUE TITLE
Request to use smaller alternative to  torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl

### ISSUE THREAD

**Issue by Ozymandias42** [danielgatis/rembg#104]
torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl bloats the package with 804.1 MB
This can't possibly be needed if I merely want to use the pre-trained net as a tool and not do dev-work on it.

**Comment by ketz** [comment]
seconded. Can we change this somehow?

**Comment by danielgatis** [comment]
Sorry, I have no idea how to do this. Feel free to open a PR.
