### ISSUE TITLE
pip install rembg complains of "rembg 1.0.14 depends on torch==1.6.0" while currently 1.8

### ISSUE THREAD

**Issue by man-of-panda3d** [danielgatis/rembg#107]
Thanks for this great tool. While trying to use it, i tried pip install command which failed complaining:
ERROR: Cannot install rembg==1.0.10, rembg==1.0.11, rembg==1.0.12, rembg==1.0.13, rembg==1.0.14, rembg==1.0.7, rembg==1.0.8 and rembg==1.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    rembg 1.0.14 depends on torch==1.6.0
    rembg 1.0.13 depends on torch==1.6.0
    rembg 1.0.12 depends on torch==1.6.0
    rembg 1.0.11 depends on torch==1.6.0
    rembg 1.0.10 depends on torch==1.6.0
    rembg 1.0.9 depends on torch==1.6.0
    rembg 1.0.8 depends on torch==1.6.0
    rembg 1.0.7 depends on torch==1.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies.

Can you please help me on this. Thanks in advance.

**Comment by danielgatis** [comment]
This issue is already fixed in the last version.

https://github.com/danielgatis/rembg/blob/master/requirements.txt#L5
