### ISSUE TITLE
Memory leak in the server version

### ISSUE THREAD

**Issue by a-tonchev** [danielgatis/rembg#108]
When starting the server (rembg-server), the allocated memory in idle is around 200mb, after processing images, with each image the RAM is rising and stay higher, so after ~10 images, the allocated memory (RAM) in idle is already around 1GB

Expected behavior:
idle memory should not rise after processing images

**Comment by dreamoocy** [comment]
same issue.

**Comment by danielgatis** [comment]
closing for lack of evidence.

**Comment by cassanelli-ampligo** [comment]
I actually have the same problem

**Comment by onlinebizsoft** [comment]
For anyone who has similar issue, I had same issue and it was OK when I use machine with GPU and install this with GPU option.
