### ISSUE TITLE
Rembg white / transparent background how?

### ISSUE THREAD

**Issue by yinjue** [danielgatis/rembg#109]
Thanks for creating the script rembg.

May I ask how to use the white or transparent background?

Currently, the background is grey.

**Comment by danielgatis** [comment]
```
Currently, the background is grey.
```
No. The output is a transparent background, but you can use a third-party library to modify the image after background removal.

**Comment by biplob004** [comment]
Save the output file as .png file extention, it will automatically gives your a transparent background.
