### ISSUE TITLE
Working for some images but giving errors on some images

### ISSUE THREAD

**Issue by Aryan-Solanki** [danielgatis/rembg#114]
code
![image](https://user-images.githubusercontent.com/37494973/124313081-ff98ae80-db8d-11eb-8528-abd9384b3b79.png)

it works for some images but sometimes gives this error
![image](https://user-images.githubusercontent.com/37494973/124313254-3d95d280-db8e-11eb-8dfc-527e94bf0d8b.png)

**Comment by danielgatis** [comment]
it is a pillow issue: https://github.com/python-pillow/Pillow/issues/4414

**Comment by Aryan-Solanki** [comment]
thanks buddy u solved it
