### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002375B155220>

### ISSUE THREAD

**Issue by Aryan-Solanki** [danielgatis/rembg#115]
code
![image](https://user-images.githubusercontent.com/37494973/124315788-1f31d600-db92-11eb-9e8f-f09f72299c8c.png)

error
![image](https://user-images.githubusercontent.com/37494973/124315758-0f19f680-db92-11eb-8454-c7eab1f6e638.png)

overlay_obj[_].index(i) is of type <class 'numpy.ndarray'>

**Comment by raphaelmartin** [comment]
Any fix? Same problem

**Comment by levovix0** [comment]
i got same issue when tried to remove background from image in-place
```sh
rembg i 1.png 1.png
```

to fix change output image to new file
```sh
rembg i 1.png rembg-1.png
```
