### ISSUE TITLE
Cannot install due to dependencies

### ISSUE THREAD

**Issue by chickenlover23** [danielgatis/rembg#12]
I am getting this error. Python version is Python 3.7.6 (64-bit).

ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0 (from rembg) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for torchvision==0.7.0 (from rembg)

**Comment by danielgatis** [comment]
Sorry I can't help you. 
But you can open this issue here: https://github.com/pytorch/pytorch
