### ISSUE TITLE
Home directory not writeable

### ISSUE THREAD

**Issue by mr-romeijn** [danielgatis/rembg#125]
I'm trying to setup Rembg in a Dockercontainer for AWS Lambda. So far I got everything within the container working properly. When running it on lambda however I run into the issue that the Home directory is not writeable. 

`"Error: Command failed: rembg -o /tmp/tmp-8-YVLMOvmnEfCz /tmp/tmp-8-s9pHTMhbTarv",
    "OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k",
    "OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k",
    "Matplotlib created a temporary config/cache directory at /tmp/matplotlib-yafcwl4j because the default path (/home/sbx_user1051/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.",
    "Traceback (most recent call last):",
    "  File \"/usr/local/bin/rembg\", line 8, in <module>",
    "    sys.exit(main())",
    "  File \"/usr/local/lib/python3.8/site-packages/rembg/cmd/cli.py\", line 146, in main",
    "    remove(",
    "  File \"/usr/local/lib/python3.8/site-packages/rembg/bg.py\", line 90, in remove",
    "    model = get_model(model_name)",
    "  File \"/usr/local/lib/python3.8/site-packages/rembg/bg.py\", line 78, in get_model",
    "    return detect.load_model(model_name=\"u2net\")",
    "  File \"/usr/local/lib/python3.8/site-packages/rembg/u2net/detect.py\", line 83, in load_model",
    "    download_file_from_google_drive(",
    "  File \"/usr/local/lib/python3.8/site-packages/rembg/u2net/detect.py\", line 23, in download_file_from_google_drive",
    "    os.makedirs(head, exist_ok=True)",
    "  File \"/usr/lib64/python3.8/os.py\", line 213, in makedirs",
    "    makedirs(head, exist_ok=exist_ok)",
    "  File \"/usr/lib64/python3.8/os.py\", line 223, in makedirs",
    "    mkdir(name, mode)",
    "OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'",
    "",
    "    at checkExecSyncError (child_process.js:635:11)",
    "    at execSync (child_process.js:671:15)",
    "    at Rembg.remove (/var/task/lib/rembg.js:18:7)",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "    at async Runtime.module.exports.do [as handler] (/var/task/handler.js:11:17)"`

As seen in above stack trace the method load_model fails because it defaults to the homedir. Is there any way to provide a path when initiating the remove method? (using CLI or Module)

**Comment by danielgatis** [comment]
try to set `U2NETP_PATH` 

look at:
https://github.com/danielgatis/rembg/blob/master/src/rembg/u2net/detect.py#L59

**Comment by mr-romeijn** [comment]
Hm. Tried setting it to /tmp but sadly (due to the os.path.expanduser) in the path generation it does not set the correct filename properly. I tried setting the env var dynamically on script call when calling it with a specific model.

e.g. `export U2NET_PATH=`/tmp/${model}.pth`

but for some reason it doesn't get picked up

**Comment by ahmarz** [comment]
Can you share how did you manage to set it in the docker ?

**Comment by nikevp** [comment]
It looks like the ENV was updated to `U2NET_HOME `. I haven't been able to get this working on AWS Lamdba by setting the path though. @danielgatis any tips?

**Comment by nikevp** [comment]
If anyone is trying to run in AWS Lambda, setting the U2NET_HOME path to `tmp/` will not work. Downloading the model will still try writing to a path outside of tmp. To work around this I made the following changes:

1. Download the desired .onnx model from Google Drive and save this file in the root of your lambda
2. Copy the session_factory.py file from the rembg package to the root of your lambda
3. Edit session_factory.py by replacing lines 40-51 with the following line:
```
# Note: Store model in the lambda code directly instead of downloading
path = f"{Path(__file__).parent.resolve()}/u2net.onnx"
```
4. Add the following line to your Dockerfile
```
ADD u2net.onnx /var/lang/lib/python3.8/site-packages/rembg/u2net.onnx
```

Assumptions:
* You are running a Dockerized AWS Lambda container image. The unzipped size of this library is too big for a standard zip upload. 

If anyone has a better approach than modifying the source code lmk :)
