### ISSUE TITLE
Removing bg in a black and white image works partially

### ISSUE THREAD

**Issue by bhaskard** [danielgatis/rembg#126]
I do have below image 

<img width="324" alt="blackwhite" src="https://user-images.githubusercontent.com/5709548/127732769-22810d30-c061-487e-86d2-43b15372de7e.png">

 
Tried removing the bg and but it removed the bg incorrectly, please help on how can we fix this.

![output1](https://user-images.githubusercontent.com/5709548/127732790-e161eea3-e352-4bb1-ad90-2f3ee9226b22.png)

**Comment by Bozzified** [comment]
well yes, it's not perfect. Your model has a white shirt on a an almost white background. There's very little you can do aside from possibly tranining a model on isolating people and hoping it would be better that way.

**Comment by SmartManoj** [comment]
What about this?
![image](https://user-images.githubusercontent.com/7231077/133792502-048aef9f-d75d-48d4-8ed4-7c6a7486de9e.png)
![image](https://user-images.githubusercontent.com/7231077/133792596-ab72deb1-06ba-4d59-9cab-7b4d355e4535.png)
![image](https://user-images.githubusercontent.com/7231077/133792750-29b6700e-6b52-46a1-9255-fc288220fa73.png)

**Comment by danielgatis** [comment]
did you run with this param ?
```
-m u2net_human_seg
```
