### ISSUE TITLE
Adjusting how aggressively backgrounds are removed

### ISSUE THREAD

**Issue by edsuverta** [danielgatis/rembg#129]
Hi,

This library works great out of the box.

Sometimes however it removes too much of the background, is it possible to adjust how aggressively the background is removed?

Thanks.

**Comment by hdiggins** [comment]
@danielgatis would love to get an answer to this as well. I tried adjusting the alpha_matting parameters in the remove method, but it doesnt seem to have any effect

**Comment by Bozzified** [comment]
Hi, the "the aggressiveness" of the tool or "effectivness" is achieved by training your model or using already pre-trained one:
https://pytorch.org/tutorials/beginner/basics/intro.html#

Alpha_matting will only really influence the roughness of the edges for the default model
