### ISSUE TITLE
The original image is resized after processing

### ISSUE THREAD

**Issue by Bozzified** [danielgatis/rembg#130]
Hi Daniel, 

I've noticed when doing some higher resolution images that rembg resizes the output image loses the resolution.

Is there an option or is this a bug. IMO the image should keep the same input resolution and have an option if for performance the rembg would handle scaling while working.

Example: 
Input image is 2560x1600 screenshot. Run it throught the script, run rembg, the ouput image after rembg seemingly lost the resolution after processing.

**Comment by quijibodesign** [comment]
I was able to change the -az "--alpha-matting-base-size" to a larger number. In my case 4000 for the height of my image. This then fixed the down sizing.

ap.add_argument(
        "-az",
        "--alpha-matting-base-size",
        default=1000,
        type=int,
        help="The image base size.",
    )
