### ISSUE TITLE
Having troubles with Ubuntu 20.04

### ISSUE THREAD

**Issue by MauriceConrad** [danielgatis/rembg#137]
I',m trying to get the tool working on fresh ubuntu servers. But during the installation process as documented, the error `ERROR: numba 0.54.0 has requirement numpy<1.21,>=1.17, but you'll have numpy 1.21.2 which is incompatible` occurs all the time. I've tried it on different completely fresh environments but no success at all. I'm also nit succeeding with downgrading numpy any way.

**Comment by ggua5470** [comment]
Hi, 
I have got the same issue. And fixed it by downgrading numpy.
pip install --upgrade numpy==1.20
