### ISSUE TITLE
Rembg GUI

### ISSUE THREAD

**Issue by raniaamina** [danielgatis/rembg#139]
Hi Rembg Dev,

Rembg is awesome and fantastic tool.
I just wanna inform that, we ([Devlovers ID](https://github.com/devlovers-id)) create the GUI version of rembg, we call it Sapulatar.

Here is Sapulatar project repository:
- https://github.com/devlovers-id/sapulatar-qt
- [Pypi page](https://pypi.org/project/sapulatar-qt/)

Regards,
Rania Amina

**Comment by danielgatis** [comment]
wow! great job! pinned!

**Comment by raniaamina** [comment]
Thanks!

**Comment by LinuxBeaver** [comment]
This is huge, Now normies can use REMBG. Thank you!
