### ISSUE TITLE
Image Border

### ISSUE THREAD

**Issue by alfonsmartinez** [danielgatis/rembg#14]
Hi

In some internet services the result appears without borders.

Is there a way to remove the border from the generated photos?

ORIGINAL
![_DSC7085](https://user-images.githubusercontent.com/1842985/94539467-8c03f280-0245-11eb-82d6-a938405b48fe.JPG)

GENERATED
![j2](https://user-images.githubusercontent.com/1842985/94538794-c0c37a00-0244-11eb-99df-ead00e29e732.png)

GENERATED ANOTHER SERVICE
![_DSC7085](https://user-images.githubusercontent.com/1842985/94538823-c91bb500-0244-11eb-83ed-7009f395e1be.png)

**Comment by vthang95** [comment]
I have the same question

**Comment by danielgatis** [comment]
Hi,
Try this:
https://github.com/danielgatis/rembg#advance-usage

**Comment by alfonsmartinez** [comment]
works perfectly in this case.

thank you very much
good work

**Comment by ashkaps** [comment]
Hello @danielgatis thank you for the awesome work. This is great. 
While I was trying this out I struggled with a few issues initially where I would see a fringe on the border of the object. 
After your implementation of alpha matting, this issue got resolved but I am starting to see pixel degradation on the contours.
I was wondering how you ended up with 240 - 10 -10? I have tried a few different combinations and each fix one set of images and break the other set :D.
In your opinion what is the best way to handle all varied set of images?

Images - https://drive.google.com/file/d/1CK_pIsH9jX09xC4IyIF8Jkc0XclL3fju/view?usp=sharing

**Comment by ashkaps** [comment]
hey @danielgatis thanks for reaching out to the pymatting team. Seeing their response there really isn't a general way to predict the boundaries of an object even with a neural network.
Considering a neural network will be trained on a particular usecase. 
I have been checking out results from a site called remove.bg and their results look good in most cases. Appears that they are somehow deleting the boundary pixels or more so they have a crisp different in background and foreground. They are actually chipping away a minute portion of the image. Thoughts?

**Comment by tomstevelfq** [comment]
> 

Hi,ashkaps,
     Have you found the reason why the pixel degradation on the contours after alpha matting?

**Comment by mingkang1993** [comment]
Have you found the reason why the pixel degradation on the contours after alpha matting?
（+1）

**Comment by jjangga0214** [comment]
@danielgatis 

> Hi,
Try this:
https://github.com/danielgatis/rembg#advance-usage

This does not exist anymore. 
Is it updated to https://github.com/danielgatis/rembg/blob/main/USAGE.md?
Thanks.

**Comment by OxAN0N** [comment]
> Hi, Try this: https://github.com/danielgatis/rembg#advance-usage

For saving your time, you can get the same result with 
```
output = remove(input, alpha_matting=True, alpha_matting_erode_size=15)

```
