### ISSUE TITLE
Mypy: Type hint issues in src/rembg/u2net/detect.py

### ISSUE THREAD

**Issue by cclauss** [danielgatis/rembg#143]
It bugs mypy that `net` is set to a `U2NETP` on line 58 but set to a `U2NET` on lines 74 and 90.

https://github.com/danielgatis/rembg/blob/master/src/rembg/u2net/detect.py#L58

$ [`mypy --ignore-missing-imports --install-types --non-interactive .`](https://pypi.org/project/mypy/)
```
src/rembg/u2net/detect.py:74: error: Incompatible types in assignment
    (expression has type "U2NET", variable has type "U2NETP")
src/rembg/u2net/detect.py:90: error: Incompatible types in assignment
    (expression has type "U2NET", variable has type "U2NETP")
```

**Comment by danielgatis** [comment]
Sorry, static type checking is not a "must have" for this project.
