### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by kalx-cyber** [danielgatis/rembg#147]
Please advise

The conflict is caused by:
    rembg 1.0.14 depends on torchvision==0.7.0
    rembg 1.0.13 depends on torchvision==0.7.0
    rembg 1.0.12 depends on torchvision==0.7.0
    rembg 1.0.11 depends on torchvision==0.7.0
    rembg 1.0.10 depends on torchvision==0.7.0
    rembg 1.0.9 depends on torchvision==0.7.0
    rembg 1.0.8 depends on torchvision==0.7.0
    rembg 1.0.7 depends on torchvision==0.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1)
ERROR: No matching distribution found for torchvision==0.7.0

**Comment by danielgatis** [comment]
fixed in next version

**Comment by juanmarin96** [comment]
Same happends with FastAPI dependency 
![image](https://user-images.githubusercontent.com/19893284/190243053-adef36d1-cc14-40e8-bfd4-fdce6056d67f.png)
