### ISSUE TITLE
Small Squares in Background

### ISSUE THREAD

**Issue by thierrydecae** [danielgatis/rembg#148]
Hi, the code runs fine and the image gets saved ok but small squares are added to the background, does anyone know how to remove these so that the returned background is plain white
![rmbg_out](https://user-images.githubusercontent.com/13047683/136251019-76d56e2e-db24-4959-bb09-f7d551602777.png)
?
Many Thanks :-)

**Comment by danielgatis** [comment]
the output background is transparent by default.
