### ISSUE TITLE
Non Avx Cpu support 

### ISSUE THREAD

**Issue by Kos-M** [danielgatis/rembg#157]
Hi i have a cpu that not supports avx instructions , nor avx2 .
Is any workaround to bypass NPACK use , or any legacy version of that ?

```
[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.

```
I'm getting that with : rembg -o ./out.jpg input.jpg

Thanks

**Comment by sdkcarlos** [comment]
> Hi i have a cpu that not supports avx instructions , nor avx2 . Is any workaround to bypass NPACK use , or any legacy version of that ?
> 
> ```
> [W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
> ```
> 
> I'm getting that with : rembg -o ./out.jpg input.jpg
> 
> Thanks

I received the same message when trying the package inside a virtual machine in VirtualBox, the background is removed though so it works pretty well. After some research, it seems you can remove this warning [avoiding the use of NNPack when building Pytorch from source](https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518/4).

**Comment by Kos-M** [comment]
Indeed , background removed in the end. im closing this :+1:
