### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by firaki12345-cmd** [danielgatis/rembg#158]
**Using google colab** 

installed rembg and tried the following code 

`!rembg -o /content/new.png /content/182.png `

**it gives the error with both jpg and png files. (Please Help)**

```
Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 5, in <module>
    from rembg.cmd.cli import main
  File "/usr/local/lib/python3.7/dist-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/usr/local/lib/python3.7/dist-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by demegire** [comment]
I have experienced the same problem. Colab uses python 3.7, but this package is intended for python 3.8+. There are no easy ways of doing this, you could try: https://newbedev.com/install-python-3-8-kernel-in-google-colaboratory. You are better off with using your local runtime

**Comment by firaki12345-cmd** [comment]
> I have experienced the same problem. Colab uses python 3.7, but this package is intended for python 3.8+. There are no easy ways of doing this, you could try: https://newbedev.com/install-python-3-8-kernel-in-google-colaboratory. You are better off with using your local runtime

i found a better tool that works flawlessly

https://github.com/OPHoperHPO/image-background-remove-tool
