### ISSUE TITLE
rembg: command not found

### ISSUE THREAD

**Issue by necotec** [danielgatis/rembg#166]
Hey ho,

at first, a big THANK YOU for this work!

I've installed `rembg` without any problems on **Linux Mint 20.2**. Now i want to test this great tool, but, when I run it, then I resolve the error `rembg: command not found`. Is there any `Softlink/Hardlink` missing? 

If i run `pip install --user rembg` again, there are many messages, that `Requiriement already installed` in my home folder (`/home/USER/.local/lib/python3.8/site-packages`).

Can you help me? Normally, I've nothing to do with **python** :). 

Thank you very much

**Comment by se7en-x230** [comment]
Is it a typo remgb? rembg is the correct package name.

**Comment by necotec** [comment]
Huups, yes it is a typo.
