### ISSUE TITLE
Problem with some frames

### ISSUE THREAD

**Issue by salvalopez** [danielgatis/rembg#17]
Is there a way to adjust this to use previous frameif it did that frame nice as reference? Is doing nice with most of the frames but in "random" sequencesdo it wrong. Here an example.

Thank you so much for the work i'm learning a lot!

![WhatsApp Image 2020-10-07 at 20 38 33](https://user-images.githubusercontent.com/15722104/95459912-8a88a780-0974-11eb-81ef-fa8e84525f20.jpeg)
![WhatsApp Image 2020-10-07 at 20 39 06](https://user-images.githubusercontent.com/15722104/95459919-8bb9d480-0974-11eb-9fb3-c7959062ce6d.jpeg)

**Comment by danielgatis** [comment]
this tool is not aimed at videos, sorry.
