### ISSUE TITLE
Quality of resulting image is terrible

### ISSUE THREAD

**Issue by colin-broderick** [danielgatis/rembg#172]
I have tried using this to remove the background from some images, and it works reasonably well. However the quality of the non-masked region in the output image is absolutely obliterated. The image becomes very blurry and tonnes of detail is lost. This surprises me as I would have expected this to be computing and applying a mask, so the non-masked region should be completely intact apart from compression artefacts.

Am I using it wrong? Is there something I need to know about choosing or preparing good inputs?

Thanks

**Comment by colin-broderick** [comment]
Actually, the quality loss only appears to appear when using alpha blending (-a -ae 15). I assumed the blend was applied only to the edge but I guess this isn't correct. We would like to blend the edges for the reason demonstrated in your README. Any tips for blending edges without losing quality for the rest of the image?

**Comment by manzke** [comment]
Tested and could verify it. When saving with alpha mat the quality of the whole image is reduced

**Comment by danielgatis** [comment]
you can try changing the az parameter like 2000

**Comment by manzke** [comment]
#173 agreed. az needs to be above your resolution

**Comment by leadbox-ryan** [comment]
Why isn't this in the docs?
