### ISSUE TITLE
 the final picture became very blurry

### ISSUE THREAD

**Issue by tomstevelfq** [danielgatis/rembg#173]
Why after I added the parameter alpha matting, the final picture became very blurry

**Comment by danielgatis** [comment]
you can try changing the `az` parameter like: `2000`

**Comment by manzke** [comment]
I can confirm it. Your resolution is above the az default value 1000 (means 1400x1400) it will downscale it and will look blurry.

**Comment by leadbox-ryan** [comment]
Where is az? Why isn't this in the docs? 

Searching "az" in this repository only brings up "lazy"…

>     type=click.File("wb", lazy=True),

https://github.com/danielgatis/rembg/blob/acc526fbafd0b2043cdaa07d15491be4ffa55428/rembg/commands/i_command.py#L85

**Comment by abhishek0093** [comment]
> you can try changing the `az` parameter like: `2000`

Hi @danielgatis , Thankyou for your amazing work and sharing with all. 
I am also facing the similar issue where sometimes the image is becoming blurred and sometimes boundary about foreground object isn't being clear. As per some discussions it is being suggested to change the az (alpha_matting_base_size) parameter which should be present in this location : https://github.com/danielgatis/rembg/blob/main/rembg/bg.py in remove function. But now I can't find it across entire project. Is the name have got changed? Can you please suggest how to change this az value and pass it to remove function ?
