### ISSUE TITLE
Can it run it on low configuration server?

### ISSUE THREAD

**Issue by tushar09** [danielgatis/rembg#175]
I am running a small droplet in DigitalOcean. 1GB ram and 1vCPU.
`Basic - Premium Intel
Shared CPU
1 vCPU
1 GB
25 GB
1 TB
$6/mo`

 It's working fine in my local PC. But when I run `rembg` in my droplet the memory and cpu usage goes to 100%. I also run SpringBoot in it and it gets killed automatically when I execute  `rembg -p path/to/input path/to/output`

So is there any possibilities or any chance to run `rembg` in this kind of **low configuration server**? It would be really appreciated if you could help me to solve this problem.

**Comment by danielgatis** [comment]
please, check out the new release and try to run it again.

**Comment by rupeshchandgude** [comment]
Hi, @tushar09 Did your issue resolved? I am facing the same issue on AWS free tier Linux machine, having 1 GB ram and 8 GB storage. The same code is working on a local machine, I am using rembg of version 2.0.10. @danielgatis, What are the minimum system requirements to use rembg?

**Comment by tushar09** [comment]
I haven't tried it afterward

**Comment by JanisPlayer** [comment]
Why don't you just use a swap file with Zram. And given the prices and poor performance, I can recommend German hosts. For 6 euros we get 4 vCores with the performance of an Intel i5 8 Gen. Plus 8 GB of RAM, KVM VPS. And IPv6 also runs without problems. I also recently tested AWS and was just annoyed that it wasn't all-inclusive for private customers. The performance for the price was comparable to an RPI 3. So if you don't want something like CPU credit or want to calculate every GB of costs with the calculator, then use German hosters. You really get something for your money.

**Comment by shajin-screl** [comment]
@danielgatis Can you list minimum system requirements ?

**Comment by shajin-sha** [comment]
@danielgatis  Can you list minimum system requirements?
