### ISSUE TITLE
feature request: functionality to add a background image/color to the generated image

### ISSUE THREAD

**Issue by option-greek** [danielgatis/rembg#186]
Will be great to have an optional way to add a custom background image/color to the generated image (through simple overlay) would be great.

PS: Thank you for this awesome library. The quality of generated image is superb! (not to mention the speed - even with just the CPU).

**Comment by bmarotta** [comment]
Hi thanks too. It would also be nice to simply output a mask for the background or the foreground color. Thanks!

**Comment by danielgatis** [comment]
in the next release try to use the option `-om`

**Comment by bmarotta** [comment]
Thanks. It works like a charm when I do:

python rembg\cli.py i -om ...

For whatever reason, when I simply do rembg i -om ...

It says "Error: No such option: -o"

Any ideas?

**Comment by danielgatis** [comment]
no :(

**Comment by option-greek** [comment]
May be you have an older version of rembg in your path @bmarotta. May be reinstall might fix it ?

**Comment by bmarotta** [comment]
I'll check. Additionally when running it in linux, it cannot download the model. 

Why did you decide to save the model in a GoogleDrive and not in the github repository?

**Comment by bmarotta** [comment]
> May be you have an older version of rembg in your path @bmarotta. May be reinstall might fix it ?

Thanks. That was the trick. Doing  `pip install rembg` is not enough to upgrade. One must do `pip install --upgrade rembg`
