### ISSUE TITLE
Model u2net.onxx does not exist

### ISSUE THREAD

**Issue by nguyenquyem99dt** [danielgatis/rembg#187]
I installed the package by command "GPU=1 pip install rembg". When I ran app.py as in "Example 2: Using PIL", I got the error "NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/ubuntu/.u2net/u2net.onnx failed:Load model /home/ubuntu/.u2net/u2net.onnx failed. File doesn't exist". 
How can I download the model?

**Comment by danielgatis** [comment]
look at: https://github.com/danielgatis/rembg/blob/main/rembg/detect.py#L14

**Comment by nguyenquyem99dt** [comment]
Thank you!

**Comment by pw717** [comment]
> look at: https://github.com/danielgatis/rembg/blob/main/rembg/detect.py#L14

Hi, I believe I experience the same issue but the link above is broken...

```
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ~/.u2net/u2net.onnx failed:Load model ~/.u2net/u2net.onnx failed. File doesn't exist
```

**Comment by pw717** [comment]
Hi, I believe I have the same issue running rembg :

```
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ~.u2net/u2net.onnx failed:Load model ~/.u2net/u2net.onnx failed. File doesn't exist
```

But the link provided above is broken...

Thank you in advance for your help.

**Comment by pw717** [comment]
The problem is I do not have a ~/.u2net/u2net.onnx file and I do not know how to create one...

**Comment by AndreasGerken** [comment]
I had the same issue. I guess normally the model will be downloaded by the package but in the .README there are also the download links:
https://github.com/danielgatis/rembg#models

Download the model and put it to ~/.u2net/
Maybe this should still be fixed as its not obvious.
