### ISSUE TITLE
Unable to install yet...

### ISSUE THREAD

**Issue by blublokt** [danielgatis/rembg#189]
I spent few hours trying to install but no success yet.
I downloaded the zip file and extracted directory rembg-main.

From directory rembg-main I ran:
> pip.exe install --upgrade setuptools
> pip.exe install numpy
> pip.exe install rembg

But I got different errors: dependency conflict , visual studio c++ 14.0 missing, etc

Which Python version should be used?
Which files of visual studio c++ should be insalled?

Thanks.

**Comment by rainlizard** [comment]
I think you have to use Python version 3.9, I don't think it works on the most recent Python. And Windows 10, I had trouble on Windows 8.1
