### ISSUE TITLE
Save file while using server

### ISSUE THREAD

**Issue by nikunjvtpl** [danielgatis/rembg#196]
How to save original file and processed file while using with "rembg s", in this repo.

**Comment by nikunjvtpl** [comment]
in cli.py file, inside post_index function add this code.
timestamp = str(int(time.time()))
        org_image_name = "original_images/org_image_"+timestamp+".jpg"
        f = open(org_image_name, 'wb')
        f.write(file)
        f.close()

This code save original file.

and bg.py file

above return statement pu this code
 temp_file = bio.read()
    file = temp_file
    timestamp = str(int(time.time()))
    bg_image_name = "bg_removed_images/rbg_image_" + timestamp + ".png"
    f = open(bg_image_name, 'wb')
    f.write(file)
    f.close()

But this code cant work on vps server you can use only on local development server. and in local it's working perfectly.

**Comment by danielgatis** [comment]
@nikunjvtpl solution is ok.
