### ISSUE TITLE
[Feature Request] Making rembg more lightweight when deployed

### ISSUE THREAD

**Issue by henrybm** [danielgatis/rembg#20]
This probably is impossible, but is there anyway to make the library more lightweight? There is so much overhead.

I want to use it in an app, but pytorch and all the other dependencies can really take up so much space.

**Comment by AltayAkkus** [comment]
This project uses [u2net](https://github.com/NathanUA/U-2-Net) in the background, you could try to convert u2net to ONNX, this might speed up things. See this blog post https://medium.com/microsoftazure/faster-and-smaller-quantized-nlp-with-hugging-face-and-onnx-runtime-ec5525473bb7
