### ISSUE TITLE
from noob tester

### ISSUE THREAD

**Issue by nimrook** [danielgatis/rembg#200]
Hi, sorry for bad english (not native language) but i hope u can understand.
I currently testing rembg for my current work/personal project to remove background image from photo.
Before i found this tools, i also test another remove bg tools (usually online) such as :

- https://www.remove.bg/
- https://www.slazzer.com/
- https://express.adobe.com/tools/remove-background
- etc 

I tried to compare and here the results :
**original file**
![test](https://user-images.githubusercontent.com/101163244/157166936-1306418c-e936-48ce-8d73-3d4c4a8b1e9f.jpg)
**remove.bg**
![removebg](https://user-images.githubusercontent.com/101163244/157166967-5c3d569a-97df-4121-8adc-b36adec83204.jpg)
**adobe spark**
![adobe spark remove background](https://user-images.githubusercontent.com/101163244/157166988-bbc153e0-830f-4106-b990-3b8eb59bdb90.jpg)
**slazzer**
![slazzer](https://user-images.githubusercontent.com/101163244/157167019-5c9809ae-c193-42ae-903e-8b69113b8cd3.jpg)
**rembg**
![test](https://user-images.githubusercontent.com/101163244/157167043-c8b5ade0-64f9-4d1c-8a9a-213a6c0616de.png)

in this case, slazzer give the best results.
i love rembg for automation/batch process but for the test image, result isnt good.
maybe there is any setting to deal with the issues?
thx

**Comment by danielgatis** [comment]
This project uses a machine learning solution the results are not precise, some tools are better than others, it depends on the model and the training phase.
