### ISSUE TITLE
Why I use python, It raise the ValueError:Input type <class 'numpy.ndarray'> is not supported.

### ISSUE THREAD

**Issue by wfmazy** [danielgatis/rembg#202]
from rembg.bg import remove
import numpy as np
import io
from PIL import Image, ImageFile

input_path = r'D:/20200313115756482.png'
output_path = r'D:/20200313115756482-1.png'

f = np.fromfile(input_path)
result = remove(f)
img = Image.open(io.BytesIO(result)).convert("RGBA")
img.save(output_path)

Traceback (most recent call last):
  File "D:/PycharmProjects/Literature Download/app.py", line 14, in <module>
    result = remove(f)
  File "D:\Microsofts\anaconda3\lib\site-packages\rembg\bg.py", line 83, in remove
    raise ValueError("Input type {} is not supported.".format(type(data)))
ValueError: Input type <class 'numpy.ndarray'> is not supported.

**Comment by rupeshchandgude** [comment]
I am also facing the same issue if I run it from PyCharm. But the same code runs as expected when I run it in the terminal. Do I am missing something when I am running the code through PyCharm?

**Comment by capedra** [comment]
https://github.com/danielgatis/rembg/issues/206
