### ISSUE TITLE
Set params in url

### ISSUE THREAD

**Issue by disasterovich** [danielgatis/rembg#208]
I'm running rembg inside a docker container as a server. 

I set different values for the parameters a and ae, but it does not seem to affect anything. Is it possible to pass parameters to the url?

remove-bg_1     | 2022-03-16T08:45:12.223633820Z INFO:     172.27.0.5:34082 - "GET /?url=https%3A%2F%2Fwww.meme-arsenal.com%2Fmemes%2F6d1f38223fca214309b81e6493195e1e.jpg&a=1&ae=15&m=u2net_human_seg HTTP/1.1" 200 OK
remove-bg_1     | 2022-03-16T08:46:34.234972739Z INFO:     172.27.0.5:34108 - "GET /?url=https%3A%2F%2Fwww.meme-arsenal.com%2Fmemes%2F6d1f38223fca214309b81e6493195e1e.jpg&a=0&ae=15&m=u2net_human_seg HTTP/1.1" 200 OK

**Comment by disasterovich** [comment]
![image_2022_03_14T14_23_33_285Z](https://user-images.githubusercontent.com/391202/158759535-50b55f5a-d4e0-4a5d-a80d-f4c18a71b80b.png)

![IOLumOodh2D28WvQZIA0f6jflcXRwdAigEdP2Nye-no-bg](https://user-images.githubusercontent.com/391202/158759547-9f5d9949-ef5b-41f0-82b1-2f8be0efcf66.png)


When I try to remove the background, the cat's right paw disappears ( 
Also tried set 'm'     => 'u2net_human_seg' - no effect.

**Comment by danielgatis** [comment]
try to  put the request param  `url` as the last param in the url, like:

`GET /?a=0&ae=15&m=u2net_human_seg&url=...`

**Comment by disasterovich** [comment]
No effect(

remove-bg_1     | 2022-04-19T07:53:47.209777160Z INFO:     172.19.0.2:40446 - "GET /?a=0&ae=15&m=u2net_human_seg&url=https%3A%2F%2Fwww.meme-arsenal.com%2Fmemes%2F6d1f38223fca214309b81e6493195e1e.jpg HTTP/1.1" 200 OK

I get the same as before:

![1](https://user-images.githubusercontent.com/391202/163953968-3c51cac5-8772-489e-a7f9-5ff0a3d1f5dc.png)
