### ISSUE TITLE
Is it possible to run this using aws lambda? thx :)

### ISSUE THREAD

**Issue by yongliu2018** [danielgatis/rembg#209]

**Comment by juanmarin96** [comment]
could you solve this?

**Comment by rnag** [comment]
@yongliu2018  and others - In case it is helpful, I've created an almost identical project for AWS environments, [rembg-aws-lambda](https://github.com/rnag/rembg-aws-lambda). It strips down some code, such as dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting `U2NET_HOME` is not required anymore.

The project can be installed with:

```console
pip install rembg-aws-lambda
```

Check it out and let me know if it works for your use case.
