### ISSUE TITLE
How to train custom models

### ISSUE THREAD

**Issue by ondrejbartas** [danielgatis/rembg#21]
Hello, 

I am complete beginner in realm of Python and Image processing, which btw your work is amazing. Thank you for it.

For most cases your predefined models work great. But in some cases I would like to somehow train/update model which is processing pictures. 

I have no idea what is the process.

Can you point me in some direction (step by step tutorial etc.) how to do it?

Again, thank you for your work I ❤️ it

**Comment by ondrejbartas** [comment]
I found one amazing thing which helps a lot with background removal.

staring image is:
![input](https://user-images.githubusercontent.com/45809/96190498-a24ac780-0f42-11eb-917d-88b2e52f4840.png)
and result is:
![output8](https://user-images.githubusercontent.com/45809/96190519-ab3b9900-0f42-11eb-93fa-74571c529033.png)
which is not great but when I add border to image by:
`convert -border 100x100 -bordercolor white input.jpg inputwithborder.png`

![inputx](https://user-images.githubusercontent.com/45809/96190575-c3131d00-0f42-11eb-99ad-562e9132ccea.png)
and then run rembg i get:

![output11](https://user-images.githubusercontent.com/45809/96190606-cc9c8500-0f42-11eb-8ef5-fa7ba9b9f25d.png)
which is completely acceptable.

Any thoughts what will happen when I will send to rembg all images with added white border?

I tested it with other different images and still getting nice results. But it will complicate way how to process images, it would be amazing if it this addition of border could be done directly in rembg. What do you think?

**Comment by danielgatis** [comment]
Hi @ondrejbartas , 

> For most cases your predefined models work great. But in some cases I would like to somehow train/update model which is processing pictures.

Under the hood, this project uses a neural network called [u2net](https://github.com/NathanUA/U-2-Net/issues). You can get more information about training a new model in the project repo.

> I tested it with other different images and still getting nice results. But it will complicate way how to process images, it would be amazing if it this addition of border could be done directly in rembg. What do you think?

I think this step should be done outside of rembg, because it is not sure that this pre-processing step will work for any image.

**Comment by JihyeJung-Work** [comment]
> I found one amazing thing which helps a lot with background removal.
> 
> staring image is:
> ![input](https://user-images.githubusercontent.com/45809/96190498-a24ac780-0f42-11eb-917d-88b2e52f4840.png)
> and result is:
> ![output8](https://user-images.githubusercontent.com/45809/96190519-ab3b9900-0f42-11eb-93fa-74571c529033.png)
> which is not great but when I add border to image by:
> `convert -border 100x100 -bordercolor white input.jpg inputwithborder.png`
> 
> ![inputx](https://user-images.githubusercontent.com/45809/96190575-c3131d00-0f42-11eb-99ad-562e9132ccea.png)
> and then run rembg i get:
> 
> ![output11](https://user-images.githubusercontent.com/45809/96190606-cc9c8500-0f42-11eb-8ef5-fa7ba9b9f25d.png)
> which is completely acceptable.
> 
> Any thoughts what will happen when I will send to rembg all images with added white border?
> 
> I tested it with other different images and still getting nice results. But it will complicate way how to process images, it would be amazing if it this addition of border could be done directly in rembg. What do you think?

@ondrejbartas How can I install this convert border library? Can I install this by pip?

Thanks.
