### ISSUE TITLE
Failed to initialize NumPy

### ISSUE THREAD

**Issue by panaris** [danielgatis/rembg#212]
Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])

windows 11 python 3.10

**Comment by sevtigo** [comment]
face the same problem. solve by downgrading python to 3.9.
![image](https://user-images.githubusercontent.com/3153815/161696783-c2b40d06-75cf-4e3b-a012-7e6c9a631705.png)
