### ISSUE TITLE
Installation failed for python 3.10.2 (succeeded with 3.9.12)

### ISSUE THREAD

**Issue by bwagner** [danielgatis/rembg#219]
Installation failed for python 3.10.2 (succeeded with 3.9.12):

Downgrading python hint from [here](https://github.com/danielgatis/rembg/issues/212#issuecomment-1088334962).

[rembg_install_python_3_10_2.txt](https://github.com/danielgatis/rembg/files/8518585/rembg_install_python_3_10_2.txt)

**Comment by danielgatis** [comment]
this project is for python 3.9 only

**Comment by bwagner** [comment]
might make sense to mention in the description

**Comment by Bernardoow** [comment]
@danielgatis hi!!

Could you give some information on why just 3.9? I liked this lib and I think this should be updated to newest python version.

**Comment by danielgatis** [comment]
Because I'm currently short on time and I was only able to test on version 3.9

If you can test in other versions and verify that everything is ok, I would be nice if you send a PR.

**Comment by Bernardoow** [comment]
Obrigado @danielgatis pela resposta !! 

(Vi que vc era br depois que perguntei !! Então o agradecimento vai ptbr kk)
