### ISSUE TITLE
Some results

### ISSUE THREAD

**Issue by capedra** [danielgatis/rembg#22]
For example:

Photo 1:
Original:
https://i.ibb.co/stYZ06K/IMG-1710.jpg
Without background:
https://i.ibb.co/dG9XC67/4003573022147-F.png

Photo2:
Original:
https://i.ibb.co/dbyn9bt/IMG-1722.jpg
Without background:
https://i.ibb.co/J5kRwSD/4003573022024-F.png

**Comment by ondrejbartas** [comment]
@capedra I am working with rembg naively but with product pictures I got better results when zooming image out:

```
curl -L --fail --show-error -s https://i.ibb.co/stYZ06K/IMG-1710.jpg | \
convert - -set option:distort:viewport "%[fx:w+400]x%[fx:h+400]"-200-200 -virtual-pixel Edge -distort SRT 0 +repage png:-

 |\
curl -s T -F file=@- http://localhost:5000/| \
convert -crop +200+200 -crop -200-200 - png:output.png
```


Curl downloads image,
first convert adds 200px border 
![intermidiate](https://user-images.githubusercontent.com/45809/96646312-3f837280-132c-11eb-9c5b-e246de20975b.png)
then I send image to rembg server
and then crop by 200px around image

![output](https://user-images.githubusercontent.com/45809/96646182-0f3bd400-132c-11eb-83c3-77b76e80577e.png)


Also by using convert it will automatically read exif metadata of input image and rotate it correctly for next usage.

**Comment by capedra** [comment]
@danielgatis @ondrejbartas But then I need to trim the output image, which is something that this library could do as well. Thanks a lot for helping me out!

**Comment by ondrejbartas** [comment]
@capedra 

Look at imagemagick trim function, i am writing this from phone so look at documentation of `convert` with options `trim` and `fuzzy`

Did it helped?
