### ISSUE TITLE
Wondering if it was possible to add more models around anime / manga

### ISSUE THREAD

**Issue by TnT04100** [danielgatis/rembg#221]
Hello, I was wondering if it was possible to add more models, make the AI works around anime/manga background removal ? I don't really know if it's possible, but i'm working on a bot which makes twitter profile pictures using your repo with a blue wall for KCORP's fans automatically on they mostly consists of anime and manga pictures which works sometimes very well but other times doesn't recognize the foreground at all. Idk if you can answer my issue or what but in case I leave my email if we can talk more about this (tkeller04100@gmail.com) !
Thanks for reading !  Have a good day/night

**Comment by danielgatis** [comment]
You need to train a new model.

https://github.com/danielgatis/rembg/issues/58
