### ISSUE TITLE
I cannot get the remove

### ISSUE THREAD

**Issue by Avaloqi** [danielgatis/rembg#222]
here is my error report. 
Ask for some opinions. 
Traceback (most recent call last): 
  File "/Users/aqi/Python_Code/rembg_env/action.py", line 1, in <module>
    from rembg import remove
ImportError: cannot import name 'remove' from 'rembg' (/Users/aqi/Python_Code/rembg_env/rembg_venv/lib/python3.9/site-packages/rembg/__init__.py)

**Comment by win5923** [comment]
me too. Cannot import remove. using pip install and error

**Comment by Feinbube** [comment]
same problem here. (deadsnakes python 3.10 on Ubuntu 20.04.4 LTS on WSL)

try this instead:
```
from rembg.bg import remove
```

**Comment by danielgatis** [comment]
https://github.com/danielgatis/rembg#installation

**Comment by abhishek692** [comment]
Same problem here

**Comment by Feinbube** [comment]
as @danielgatis emphasized: it works like a charm with Python 3.9 :)
