### ISSUE TITLE
I'm not getting very good Results.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [danielgatis/rembg#226]
I'm not getting very good results.

This is the image I'm attempting to remove the background on.
![before-remove](https://user-images.githubusercontent.com/28204537/167177481-f58bdced-de61-49c3-84c0-6109f305d30c.png)

And this is the result I'm getting.
![output](https://user-images.githubusercontent.com/28204537/167177492-e08a243b-a4f4-4628-9d3c-e05c7318dc9a.png)

Do you have any suggestions?

This is the specific code I'm running
```
req = urllib.request.urlopen(image_or_path)
arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
img = cv2.imdecode(arr, -1) # 'Load it as it is'

cv2.imwrite("before-remove.png", img)
output = remove(img, True)
cv2.imwrite("output.png", output)
```

**Comment by selected-pixel-jameson** [comment]
FYI, if I convert the image to grayscale it works perfect.

**Comment by danielgatis** [comment]
you need to train your own model.

https://github.com/danielgatis/rembg/issues/58
