### ISSUE TITLE
How to run on the GPU?

### ISSUE THREAD

**Issue by nguyenquyem99dt** [danielgatis/rembg#228]
Hi, thank you for your contribution to the community!
I installed this library via pip:
pip install rembg[gpu]
But when I run the remover (python script), it only runs with CPU, not using GPU.
How can I use GPU for inference?

**Comment by LauLauHip** [comment]
I also installed Cuda and pytorch and it even says True when i print(torch.cuda.is_available()). Still doesn't work. :(

**Comment by danielgatis** [comment]
I can't reproduce this scenario on my machine. I need some help to find out what is happen :(
