### ISSUE TITLE
Please guide me how to use model u2net_cloth_seg

### ISSUE THREAD

**Issue by nhuhoan** [danielgatis/rembg#231]
Hi, 

I have downloaded and installed model **u2net_cloth_seg.onnx**  into **~/.u2net** , but when I run the command the system gives an error : 
 **Error: Invalid value for '-m' / '--model': 'u2net_cloth_seg' is not one of 'u2net', 'u2netp', 'u2net_human_seg'.**
 
![Selection_066](https://user-images.githubusercontent.com/228457/169935098-fd61eddf-7878-4d37-81b8-4571c5127803.png)

 Please guide me to fix it, 

Thanks so much.

**Comment by danielgatis** [comment]
update the rembg version
