### ISSUE TITLE
Trying to get it to work

### ISSUE THREAD

**Issue by bullmoose20** [danielgatis/rembg#233]
I am on Windows 11. While I did read that it runs with 3.9, does that mean this will not work with a later version? I tried to run with 3.10, 3.9.13 but always getting the following error and not sure what to do:
![image](https://user-images.githubusercontent.com/12549033/170349656-53ed4658-db1d-44ba-93ae-adf585a8dfd8.png)

**Comment by Ghaleb-alnakhlani** [comment]
From what I can see the issue is not with your python version, you need to pass the correct arguments. Make sure the path is correct and try using `p` instead of `i`.
I hope this solves your issue.

**Comment by bullmoose20** [comment]
![image](https://user-images.githubusercontent.com/12549033/170354653-21501e2b-d49d-4500-b5cf-6a760b776fe2.png)
Possibly I am not understanding your documentation, but the image above from your readme is why I used the "i". Nonetheless, here are the results of using "p"
![image](https://user-images.githubusercontent.com/12549033/170354928-169636ba-9d72-40ad-a77b-78026875be00.png)

**Comment by danielgatis** [comment]
Try to run a help:

```
❯ rembg --help
Usage: rembg [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  i  for a file as input
  p  for a folder as input
  s  for a http server
```

**Comment by bullmoose20** [comment]
![image](https://user-images.githubusercontent.com/12549033/170360314-1783fa75-2405-4dd0-9ebb-cb42d4849d69.png)

**Comment by danielgatis** [comment]
plz update your rembg

**Comment by bullmoose20** [comment]
Attempting to upgrade now

**Comment by bullmoose20** [comment]
`(myenv) PS C:\Users\nickz> pip install --upgrade rembg
Requirement already satisfied: rembg in c:\users\nickz\myenv\lib\site-packages (1.0.27)
Collecting rembg
  Using cached rembg-2.0.13-py3-none-any.whl (10 kB)
Collecting watchdog==2.1.7
  Using cached watchdog-2.1.7-py3-none-win_amd64.whl (76 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp310-cp310-win_amd64.whl (555 kB)
Collecting uvicorn==0.17.0
  Using cached uvicorn-0.17.0-py3-none-any.whl (54 kB)
Collecting asyncer==0.0.1
  Using cached asyncer-0.0.1-py3-none-any.whl (8.1 kB)
Collecting python-multipart==0.0.5
  Using cached python-multipart-0.0.5.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm==4.62.3
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting rembg
  Using cached rembg-2.0.12-py3-none-any.whl (10 kB)
  Using cached rembg-2.0.11-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.10-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.9-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.8-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.7-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.6-py3-none-any.whl (9.2 kB)
  Using cached rembg-2.0.5-py3-none-any.whl (9.2 kB)
Collecting gdown==4.2.0
  Using cached gdown-4.2.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rembg
  Using cached rembg-2.0.4-py3-none-any.whl (9.2 kB)
  Using cached rembg-2.0.3-py3-none-any.whl (9.4 kB)
Requirement already satisfied: pymatting==1.1.5 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.1.5)
  Using cached rembg-2.0.2-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.1-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.0-py3-none-any.whl (9.3 kB)
  Using cached rembg-1.0.31-py3-none-any.whl (14 kB)
Collecting requests==2.24.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting pymatting==1.1.1
  Using cached PyMatting-1.1.1-py3-none-any.whl (48 kB)
Requirement already satisfied: torchvision>=0.8.1 in c:\users\nickz\myenv\lib\site-packages (from rembg) (0.12.0)
Requirement already satisfied: waitress>=1.4.4 in c:\users\nickz\myenv\lib\site-packages (from rembg) (2.1.1)
Requirement already satisfied: flask>=1.1.2 in c:\users\nickz\myenv\lib\site-packages (from rembg) (2.1.2)
Requirement already satisfied: scipy>=1.5.4 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.8.1)
Requirement already satisfied: requests>=2.24.0 in c:\users\nickz\myenv\lib\site-packages (from rembg) (2.27.1)
Requirement already satisfied: hsh>=1.1.0 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.1.0)
Requirement already satisfied: tqdm>=4.51.0 in c:\users\nickz\myenv\lib\site-packages (from rembg) (4.64.0)
Requirement already satisfied: filetype>=1.0.7 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.0.13)
Requirement already satisfied: numpy>=1.19.5 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.21.6)
Requirement already satisfied: torch>=1.7.0 in c:\users\nickz\myenv\lib\site-packages (from rembg) (1.11.0)
Requirement already satisfied: pillow>=8.0.1 in c:\users\nickz\myenv\lib\site-packages (from rembg) (9.1.1)
Requirement already satisfied: scikit-image>=0.17.2 in c:\users\nickz\myenv\lib\site-packages (from rembg) (0.19.2)
Requirement already satisfied: click>=8.0 in c:\users\nickz\myenv\lib\site-packages (from flask>=1.1.2->rembg) (8.1.3)
Requirement already satisfied: Jinja2>=3.0 in c:\users\nickz\myenv\lib\site-packages (from flask>=1.1.2->rembg) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\nickz\myenv\lib\site-packages (from flask>=1.1.2->rembg) (2.1.2)
Requirement already satisfied: Werkzeug>=2.0 in c:\users\nickz\myenv\lib\site-packages (from flask>=1.1.2->rembg) (2.1.2)
Requirement already satisfied: commandlines in c:\users\nickz\myenv\lib\site-packages (from hsh>=1.1.0->rembg) (0.4.1)
Requirement already satisfied: numba!=0.49.0 in c:\users\nickz\myenv\lib\site-packages (from pymatting==1.1.5->rembg) (0.55.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nickz\myenv\lib\site-packages (from requests>=2.24.0->rembg) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nickz\myenv\lib\site-packages (from requests>=2.24.0->rembg) (2022.5.18.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\nickz\myenv\lib\site-packages (from requests>=2.24.0->rembg) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nickz\myenv\lib\site-packages (from requests>=2.24.0->rembg) (1.26.9)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\nickz\myenv\lib\site-packages (from scikit-image>=0.17.2->rembg) (2022.5.4)
Requirement already satisfied: networkx>=2.2 in c:\users\nickz\myenv\lib\site-packages (from scikit-image>=0.17.2->rembg) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\nickz\myenv\lib\site-packages (from scikit-image>=0.17.2->rembg) (21.3)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\nickz\myenv\lib\site-packages (from scikit-image>=0.17.2->rembg) (1.3.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\nickz\myenv\lib\site-packages (from scikit-image>=0.17.2->rembg) (2.19.2)
Requirement already satisfied: typing-extensions in c:\users\nickz\myenv\lib\site-packages (from torch>=1.7.0->rembg) (4.2.0)
Requirement already satisfied: colorama in c:\users\nickz\myenv\lib\site-packages (from tqdm>=4.51.0->rembg) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nickz\myenv\lib\site-packages (from Jinja2>=3.0->flask>=1.1.2->rembg) (2.1.1)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in c:\users\nickz\myenv\lib\site-packages (from numba!=0.49.0->pymatting==1.1.5->rembg) (0.38.1)
Requirement already satisfied: setuptools in c:\users\nickz\myenv\lib\site-packages (from numba!=0.49.0->pymatting==1.1.5->rembg) (62.1.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\nickz\myenv\lib\site-packages (from packaging>=20.0->scikit-image>=0.17.2->rembg) (3.0.9)
(myenv) PS C:\Users\nickz> rembg -help
C:\Users\nickz\myenv\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
usage: rembg [-h] [-m {u2net}] [-a [ALPHA_MATTING]] [-af ALPHA_MATTING_FOREGROUND_THRESHOLD]
             [-ab ALPHA_MATTING_BACKGROUND_THRESHOLD] [-ae ALPHA_MATTING_ERODE_SIZE] [-az ALPHA_MATTING_BASE_SIZE]
             [-p PATH PATH] [-o [OUTPUT]]
             [input]
rembg: error: argument -h/--help: ignored explicit argument 'elp'
(myenv) PS C:\Users\nickz> rembg --help
C:\Users\nickz\myenv\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
usage: rembg [-h] [-m {u2net}] [-a [ALPHA_MATTING]] [-af ALPHA_MATTING_FOREGROUND_THRESHOLD]
             [-ab ALPHA_MATTING_BACKGROUND_THRESHOLD] [-ae ALPHA_MATTING_ERODE_SIZE] [-az ALPHA_MATTING_BASE_SIZE]
             [-p PATH PATH] [-o [OUTPUT]]
             [input]

positional arguments:
  input                 Path to the input image.

options:
  -h, --help            show this help message and exit
  -m {u2net}, --model {u2net}
                        The model name.
  -a [ALPHA_MATTING], --alpha-matting [ALPHA_MATTING]
                        When true use alpha matting cutout.
  -af ALPHA_MATTING_FOREGROUND_THRESHOLD, --alpha-matting-foreground-threshold ALPHA_MATTING_FOREGROUND_THRESHOLD
                        The trimap foreground threshold.
  -ab ALPHA_MATTING_BACKGROUND_THRESHOLD, --alpha-matting-background-threshold ALPHA_MATTING_BACKGROUND_THRESHOLD
                        The trimap background threshold.
  -ae ALPHA_MATTING_ERODE_SIZE, --alpha-matting-erode-size ALPHA_MATTING_ERODE_SIZE
                        Size of element used for the erosion.
  -az ALPHA_MATTING_BASE_SIZE, --alpha-matting-base-size ALPHA_MATTING_BASE_SIZE
                        The image base size.
  -p PATH PATH, --path PATH PATH
                        An input folder and an output folder.
  -o [OUTPUT], --output [OUTPUT]
                        Path to the output png image.
(myenv) PS C:\Users\nickz>`

**Comment by Ghaleb-alnakhlani** [comment]
I guess you are installing an old version.
`rembg in c:\users\nickz\myenv\lib\site-packages **(1.0.27)**`
Try this install python 3.9 and install the `rembg` using this command.
`python3.9 -m pip install rembg`

**Comment by bullmoose20** [comment]
Thanks... here are the results. I am in the python 3.9 directory
`PS C:\Users\nickz\AppData\Local\Programs\Python\Python39> python.exe -m pip install rembg
Defaulting to user installation because normal site-packages is not writeable
Collecting rembg
  Using cached rembg-2.0.13-py3-none-any.whl (10 kB)
Requirement already satisfied: pymatting==1.1.5 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.1.5)
Collecting gdown==4.4.0
  Using cached gdown-4.4.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting filetype==1.0.9
  Using cached filetype-1.0.9-py2.py3-none-any.whl (16 kB)
Collecting watchdog==2.1.7
  Using cached watchdog-2.1.7-py3-none-win_amd64.whl (76 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp310-cp310-win_amd64.whl (555 kB)
Collecting numpy==1.21.5
  Using cached numpy-1.21.5-cp310-cp310-win_amd64.whl (14.0 MB)
Collecting click==8.0.3
  Using cached click-8.0.3-py3-none-any.whl (97 kB)
Collecting rembg
  Using cached rembg-2.0.12-py3-none-any.whl (10 kB)
  Using cached rembg-2.0.11-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.10-py3-none-any.whl (9.4 kB)
Collecting gdown==4.3.1
  Using cached gdown-4.3.1.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rembg
  Using cached rembg-2.0.9-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.8-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.7-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.6-py3-none-any.whl (9.2 kB)
  Using cached rembg-2.0.5-py3-none-any.whl (9.2 kB)
Collecting gdown==4.2.0
  Using cached gdown-4.2.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rembg
  Using cached rembg-2.0.4-py3-none-any.whl (9.2 kB)
  Using cached rembg-2.0.3-py3-none-any.whl (9.4 kB)
  Using cached rembg-2.0.2-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.1-py3-none-any.whl (9.3 kB)
  Using cached rembg-2.0.0-py3-none-any.whl (9.3 kB)
Collecting numpy==1.22.1
  Using cached numpy-1.22.1-cp310-cp310-win_amd64.whl (14.7 MB)
Collecting rembg
  Using cached rembg-1.0.31-py3-none-any.whl (14 kB)
Collecting waitress==1.4.4
  Using cached waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Collecting flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting filetype==1.0.7
  Using cached filetype-1.0.7-py2.py3-none-any.whl (15 kB)
Collecting scikit-image==0.19.1
  Using cached scikit_image-0.19.1-cp310-cp310-win_amd64.whl (12.4 MB)
Collecting tqdm==4.51.0
  Using cached tqdm-4.51.0-py2.py3-none-any.whl (70 kB)
Collecting rembg
  Using cached rembg-1.0.27-py3-none-any.whl
Requirement already satisfied: numpy>=1.19.5 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.21.6)
Requirement already satisfied: scikit-image>=0.17.2 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (0.19.2)
Requirement already satisfied: waitress>=1.4.4 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (2.1.1)
Requirement already satisfied: filetype>=1.0.7 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.0.13)
Requirement already satisfied: hsh>=1.1.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.1.0)
Requirement already satisfied: flask>=1.1.2 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (2.1.2)
Requirement already satisfied: torch>=1.7.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.11.0)
Requirement already satisfied: tqdm>=4.51.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (4.64.0)
Requirement already satisfied: requests>=2.24.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (2.27.1)
Requirement already satisfied: pillow>=8.0.1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (9.1.1)
Requirement already satisfied: torchvision>=0.8.1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (0.12.0)
Requirement already satisfied: scipy>=1.5.4 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from rembg) (1.8.1)
Requirement already satisfied: Werkzeug>=2.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from flask>=1.1.2->rembg) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from flask>=1.1.2->rembg) (3.1.2)
Requirement already satisfied: click>=8.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from flask>=1.1.2->rembg) (8.1.3)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from flask>=1.1.2->rembg) (2.1.2)
Requirement already satisfied: commandlines in c:\users\nickz\appdata\roaming\python\python310\site-packages (from hsh>=1.1.0->rembg) (0.4.1)
Requirement already satisfied: numba!=0.49.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from pymatting==1.1.5->rembg) (0.55.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from requests>=2.24.0->rembg) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from requests>=2.24.0->rembg) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from requests>=2.24.0->rembg) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from requests>=2.24.0->rembg) (2.0.11)
Requirement already satisfied: networkx>=2.2 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from scikit-image>=0.17.2->rembg) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from scikit-image>=0.17.2->rembg) (21.3)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from scikit-image>=0.17.2->rembg) (2022.5.4)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from scikit-image>=0.17.2->rembg) (1.3.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from scikit-image>=0.17.2->rembg) (2.19.2)
Requirement already satisfied: typing-extensions in c:\users\nickz\appdata\roaming\python\python310\site-packages (from torch>=1.7.0->rembg) (4.2.0)
Requirement already satisfied: colorama in c:\users\nickz\appdata\roaming\python\python310\site-packages (from tqdm>=4.51.0->rembg) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from Jinja2>=3.0->flask>=1.1.2->rembg) (2.1.1)
Requirement already satisfied: setuptools in c:\program files\python310\lib\site-packages (from numba!=0.49.0->pymatting==1.1.5->rembg) (58.1.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from numba!=0.49.0->pymatting==1.1.5->rembg) (0.38.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\nickz\appdata\roaming\python\python310\site-packages (from packaging>=20.0->scikit-image>=0.17.2->rembg) (3.0.9)
Installing collected packages: rembg
Successfully installed rembg-1.0.27
PS C:\Users\nickz\AppData\Local\Programs\Python\Python39> rembg --help
C:\Users\nickz\AppData\Roaming\Python\Python310\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
usage: rembg [-h] [-m {u2net}] [-a [ALPHA_MATTING]] [-af ALPHA_MATTING_FOREGROUND_THRESHOLD] [-ab ALPHA_MATTING_BACKGROUND_THRESHOLD]
             [-ae ALPHA_MATTING_ERODE_SIZE] [-az ALPHA_MATTING_BASE_SIZE] [-p PATH PATH] [-o [OUTPUT]]
             [input]

positional arguments:
  input                 Path to the input image.

options:
  -h, --help            show this help message and exit
  -m {u2net}, --model {u2net}
                        The model name.
  -a [ALPHA_MATTING], --alpha-matting [ALPHA_MATTING]
                        When true use alpha matting cutout.
  -af ALPHA_MATTING_FOREGROUND_THRESHOLD, --alpha-matting-foreground-threshold ALPHA_MATTING_FOREGROUND_THRESHOLD
                        The trimap foreground threshold.
  -ab ALPHA_MATTING_BACKGROUND_THRESHOLD, --alpha-matting-background-threshold ALPHA_MATTING_BACKGROUND_THRESHOLD
                        The trimap background threshold.
  -ae ALPHA_MATTING_ERODE_SIZE, --alpha-matting-erode-size ALPHA_MATTING_ERODE_SIZE
                        Size of element used for the erosion.
  -az ALPHA_MATTING_BASE_SIZE, --alpha-matting-base-size ALPHA_MATTING_BASE_SIZE
                        The image base size.
  -p PATH PATH, --path PATH PATH
                        An input folder and an output folder.
  -o [OUTPUT], --output [OUTPUT]
                        Path to the output png image.
PS C:\Users\nickz\AppData\Local\Programs\Python\Python39>`

**Comment by Ghaleb-alnakhlani** [comment]
you don`t need to go to python3 directory. You can run it from the image directory.
and do this to make sure that you are running the latest version.
`rembg --version`

**Comment by bullmoose20** [comment]
Got it working after setting up a python virtualenv.
