### ISSUE TITLE
Tweaking to improve results

### ISSUE THREAD

**Issue by bullmoose20** [danielgatis/rembg#236]
If we see anomalies when removing backgrounds, are there tweaks we can make? I am mostly trying to remove backgrounds on people headshots and noticed that sometimes a shoulder or everything below the neck disappears...

**Comment by bullmoose20** [comment]
Before:
![Josh Gad](https://user-images.githubusercontent.com/12549033/171183293-cc15e671-b1b1-40d2-bb69-41aa42dd89e1.jpg)
![Karl Urban](https://user-images.githubusercontent.com/12549033/171183294-f0b91c1a-ac9b-43de-96e8-e101674028e8.jpg)

After (using rembg i):
![Josh Gad](https://user-images.githubusercontent.com/12549033/171183488-321a6546-c51f-4011-9ce6-a5bd4fac8a1f.png)
![Karl Urban](https://user-images.githubusercontent.com/12549033/171183493-10b8ca29-46bc-41dd-9497-28a37ab601e1.png)

After (using rembg i a -ae):
![Josh Gad-ae](https://user-images.githubusercontent.com/12549033/171186128-f5a59073-8ac5-45b6-bfa4-358f9cf7f5df.png)
![Karl Urban-ae](https://user-images.githubusercontent.com/12549033/171186133-db6567f4-088a-453f-ae61-a48653de5c40.png)

**Comment by bullmoose20** [comment]
Additionally, maybe there is a way for me to specify this somehow?
u2net_cloth_seg ([download](https://drive.google.com/uc?id=15rKbQSXQzrKCQurUjZFg8HqzZad8bcyz), [source](https://github.com/levindabhi/cloth-segmentation)): A pre-trained model for Cloths Parsing from human portrait. Here clothes are parsed into 3 category: Upper body, Lower body and Full body.

And I think almost all are "Upper body"

**Comment by bullmoose20** [comment]
rembg i -m u2net_human_seg 

--help does not show the -m option
README.md does not specify that there is a -m option... I stumbled on this...

**Comment by ArielMAJ** [comment]
I ran into this same thing and u2net_human_seg helped too.

As for improving upon the model, I'm pretty sure you should be able to train your own model (or train u2net_human_seg with your own images) and use it. Pretty sure it isn't an easy task either. GL!

**Comment by alcinopitchprint** [comment]
The training process is explained here by @endh1337 , https://github.com/danielgatis/rembg/issues/193#issuecomment-1055534289
