### ISSUE TITLE
could not import rembg

### ISSUE THREAD

**Issue by abhishek692** [danielgatis/rembg#243]
Traceback (most recent call last):
  File "/Users/abhishek/bgrem/bgrem-python/main.py", line 2, in <module>
    from rembg.bg import remove
ModuleNotFoundError: No module named 'rembg'

**Comment by aloisdg** [comment]
Same on manjaro:

``` 
Traceback (most recent call last):
  File "/home/aloisdg/Downloads/token/image/nobg/rembgs.py", line 1, in <module>
    from rembg import remove
ImportError: cannot import name 'remove' from 'rembg' (/home/aloisdg/.local/lib/python3.10/site-packages/rembg/__init__.py)
```

I am running the example

**Comment by vbernardes-ic** [comment]
Running into the same problem. I've traced so far as to downloading the model from Google Drive.
Apparently Google Drive is returning a Virus scan warning instead of the model:
```
b'<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="PjSwtJ5VzTKcgouCU_6vFg">/* Copyright 2022 Google Inc. All Rights Reserved. */\n.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can\'t scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ">u2net.pth</a> (168M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ&amp;confirm=t" method="post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>'
```

**Comment by ArielMAJ** [comment]
> Running into the same problem. I've traced so far as to downloading the model from Google Drive. Apparently Google Drive is returning a Virus scan warning instead of the model:
> 
> ```
> b'<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="PjSwtJ5VzTKcgouCU_6vFg">/* Copyright 2022 Google Inc. All Rights Reserved. */\n.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can\'t scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ">u2net.pth</a> (168M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ&amp;confirm=t" method="post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>'
> ```
> 
> Edit:
> 
> For now, try this workaround: If you download the model manually from [Google Drive](https://docs.google.com/uc?export=download&id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ) and save it to `~/.u2net/u2net.pth` it should work.

I had the same problem and this solved it. Pretty good solution! I almost downgraded from python 3.10 to 3.9 thinking that was the problem.

**Comment by kronze1996** [comment]
> Same on manjaro:
> 
> ```
> Traceback (most recent call last):
>   File "/home/aloisdg/Downloads/token/image/nobg/rembgs.py", line 1, in <module>
>     from rembg import remove
> ImportError: cannot import name 'remove' from 'rembg' (/home/aloisdg/.local/lib/python3.10/site-packages/rembg/__init__.py)
> ```
> 
> I am running the example after doing a `pip install rembg`
> 
> Edit 1:
> 
> it seems that `remove` is under `rembg.bg` but doing `rembg.bg.remove(data)` does not work either
> 
> ```
> Traceback (most recent call last):
>   File "/home/aloisdg/Downloads/token/image/nobg/rembgs.py", line 18, in <module>
>     output = rembg.bg.remove(image)
> AttributeError: module 'rembg' has no attribute 'bg'
> ```
> 
> Edit 2: alright I think I can make it work with `from rembg import bg` then calling `remove` in the code
> 
> Tried and got `ModuleNotFoundError: No module named 'matplotlib'` let's go for a `pip3 install matplotlib` and:
> 
> ```
> Traceback (most recent call last):
>   File "/home/aloisdg/Downloads/token/image/nobg/rembgs.py", line 18, in <module>
>     output = remove(image)
> NameError: name 'remove' is not defined
> ```
> 
> oh boy
> 
> Edit 3:
> 
> alright again `from rembg import bg` then calling `bg.remove` in the code, move to a new error:
> 
> ```
> Downloading u2net.pth to /home/aloisdg/.u2net: 2.16kiB [00:00, 6.13MiB/s]
> Traceback (most recent call last):
>   File "/home/aloisdg/Downloads/token/image/nobg/rembgs.py", line 18, in <module>
>     output = bg.remove(image)
>   File "/home/aloisdg/.local/lib/python3.10/site-packages/rembg/bg.py", line 90, in remove
>     model = get_model(model_name)
>   File "/home/aloisdg/.local/lib/python3.10/site-packages/rembg/bg.py", line 78, in get_model
>     return detect.load_model(model_name="u2net")
>   File "/home/aloisdg/.local/lib/python3.10/site-packages/rembg/u2net/detect.py", line 113, in load_model
>     torch.load(
>   File "/home/aloisdg/.local/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/home/aloisdg/.local/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '<'.
> ```
> 
> Well #220 and #212

Did anyone find any solution for this?

**Comment by ArielMAJ** [comment]
> Did anyone find any solution for this?

I believe the above comments explain how to circumvent those problems.

I'm not sure how it is for Python 3.9 + rembg latest versions, but if you're running into those same problems I'm assuming you're using rembg==1.0.27 (the only version that is easily pip installable for Python 3.10).

1. rembg 1.0.27 seem to require matplotlib but doesn't install it automatically (so you gotta pip install matplotlib separately).
2. I use `from rembg import bg` and later call `bg.remove(input_image_as_bytes)`
3. There's a good chance it's the case that you didn't manually download the model for detecting objects: that leads rembg to trying to download it automatically and that's broken in v1.0.27 (it downloads the html page instead of the model). If you manually download one of the 2 accepted models for that version (u2net.pth or u2net_human_seg.pth) and place it in the correct folder (~/.u2net/u2net.pth) there's a good chance it will solve that last error.

It works for me like that.

**Comment by aloisdg** [comment]
@kronze1996 You fix the last step by manually downloading the model as per @vbernardes-ic's comment
