### ISSUE TITLE
Command errored out with exit status 1

### ISSUE THREAD

**Issue by sbilketay** [danielgatis/rembg#25]
Hi.
I get the following error after the pip install rembg command.

`ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-0r0l8i3_/scikit-image/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-0r0l8i3_/scikit-image/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-pip-egg-info-oipq9o0h
         cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-0r0l8i3_/scikit-image/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-0r0l8i3_/scikit-image/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-0r0l8i3_/scikit-image/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by danielgatis** [comment]
Hi,
Try this `pip3 install numpy`

**Comment by sbilketay** [comment]
I will try this.
