### ISSUE TITLE
torch error

### ISSUE THREAD

**Issue by sbilketay** [danielgatis/rembg#26]
```
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from rembg) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0 (from rembg)
```

I also get this error when I try to install torch.

```Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-wheel-fdh_s1h4
       cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-record-cp5gwhp7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch
         cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 99, in run
        self.run_command('build_deps')
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-record-cp5gwhp7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch Check the logs for full command output.
```

**Comment by wkm97** [comment]
> ```
> ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from rembg) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch==1.6.0 (from rembg)
> ```
> 
> I also get this error when I try to install torch.
> 
> ```
>   ERROR: Command errored out with exit status 1:
>    command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-wheel-fdh_s1h4
>        cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/
>   Complete output (30 lines):
>   running bdist_wheel
>   running build
>   running build_deps
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 225, in <module>
>       setup(name="torch", version="0.1.2.post2",
>     File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
>       self.run_command(cmd)
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
>       self.run_command('build')
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 51, in run
>       from tools.nnwrap import generate_wrappers as generate_nn_wrappers
>   ModuleNotFoundError: No module named 'tools.nnwrap'
>   ----------------------------------------
>   ERROR: Failed building wheel for torch
>   Running setup.py clean for torch
>   ERROR: Command errored out with exit status 1:
>    command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
>        cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch
>   Complete output (2 lines):
>   running clean
>   error: [Errno 2] No such file or directory: '.gitignore'
>   ----------------------------------------
>   ERROR: Failed cleaning build dir for torch
> Failed to build torch
> Installing collected packages: torch
>     Running setup.py install for torch ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-record-cp5gwhp7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch
>          cwd: /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/
>     Complete output (23 lines):
>     running install
>     running build_deps
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 225, in <module>
>         setup(name="torch", version="0.1.2.post2",
>       File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
>         self.run_command(cmd)
>       File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 99, in run
>         self.run_command('build_deps')
>       File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py", line 51, in run
>         from tools.nnwrap import generate_wrappers as generate_nn_wrappers
>     ModuleNotFoundError: No module named 'tools.nnwrap'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"'; __file__='"'"'/private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-install-jn4ttpcw/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d9/3nm1w1td445fj9yfy49kl3300000gn/T/pip-record-cp5gwhp7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/torch Check the logs for full command output.
> ```

I have this problem too, but after installing pytorch first then it will be okay.
pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

Reference: https://pytorch.org/get-started/previous-versions/

**Comment by sbilketay** [comment]
Thanks.
