### ISSUE TITLE
Alpha matting missing in --help

### ISSUE THREAD

**Issue by Ballistx** [danielgatis/rembg#263]
I used `rembg input output -a -ae 15` and it worked perfectly fine in windows cli but it seems like the description is missing when using the --help option. Only the commands i, p and s are displayed. Probably helpful to add it, I first thought it's only available when using it as library.

Edit: Looked in the code and it seems like there should be a lot more infos shown when using --help, but not for me as you can see in the image.

rembg, version 2.0.21

![image](https://user-images.githubusercontent.com/65251619/177641315-b8d358d1-a129-49e1-b863-5fbd30a1add2.png)

**Comment by danielgatis** [comment]
try this: `rembg i --help`

```
❯ rembg i --help
Usage: rembg i [OPTIONS] INPUT OUTPUT

  for a file as input

Options:
  -m, --model [u2net|u2netp|u2net_human_seg|u2net_cloth_seg]
                                  model name  [default: u2net]
  -a, --alpha-matting             use alpha matting  [default: False]
  -af, --alpha-matting-foreground-threshold INTEGER
                                  trimap fg threshold  [default: 240]
  -ab, --alpha-matting-background-threshold INTEGER
                                  trimap bg threshold  [default: 10]
  -ae, --alpha-matting-erode-size INTEGER
                                  erode size  [default: 10]
  -om, --only-mask                output only the mask  [default: False]
  --help                          Show this message and exit.
```
