### ISSUE TITLE
[BUG] Color in the Image is lost or gets changed

### ISSUE THREAD

**Issue by ASH1998** [danielgatis/rembg#269]
**Describe the bug**
Color in the Image is lost or gets changed after after removing background with u2net.
The output for the color is not the same as the original image. Please check the images provided.

So my question is what sort of pre/post processing is done to make the output as such, and is there a way to get output close to original image.

**To Reproduce**
1. Use u2net base model on the original image
2. Verify the colors of output

**Expected behavior**
The image should look the same.

**Images**
Original Image
![436b78405d18204ac4825c991ddc9525f2e1557897d3285ef5c22d86](https://user-images.githubusercontent.com/23384411/179913862-542ef740-d620-4136-a2f2-a5e00799569a.png)

BG Removed Image
![a67c5cb292222ac5414944f9ab613eaba848762caa89445a70dc2f1d](https://user-images.githubusercontent.com/23384411/179913902-770c56d6-c7ef-4842-b692-06e7126d6299.png)

**OS Version:**
Linux 20.04

**Rembg version:**
v2.0.21

**Comment by danielgatis** [comment]
This issue is related to the model. 
You must train a model with your images to get a better result.
The default model is a general one... so it can get some odd results.

https://github.com/danielgatis/rembg/issues/193#issuecomment-1055534289
