### ISSUE TITLE
Add config option for default model

### ISSUE THREAD

**Issue by AltayAkkus** [danielgatis/rembg#27]
Hey,
I really like your project! It really helped me a lot.
But I have a small issue: I am currently building a Docker Container with a FastAPI Server for rembg, to deploy it via Kubernetes and get a pretty scalable and cheap Background Removal as a Service.
I will release that later, but I have a performance issue:
In bg.py you automatically load both models, but I will only use the u2netp one.
I want to speed up the API as fast as I can, and therefore there should be a config option (there is no config, yet?) to only load the needed model.
That will be a difficult task tho, I don't really know how to implement it since this module is not a class and I can't add parameters to it or anything.

Greetings,
Altay@Dorfmeyster

**Comment by danielgatis** [comment]
done!
just get the last version.

for more details:
https://github.com/danielgatis/rembg/blob/master/src/rembg/bg.py#L67
