### ISSUE TITLE
[BUG] rembg 2.0.21 depends on onnxruntime==1.10.0

### ISSUE THREAD

**Issue by bramses** [danielgatis/rembg#278]
**Describe the bug**

rembg 2.0.21 depends on onnxruntime==1.10.0

**To Reproduce**

`pip install rembg`

```
pip install onnxruntime==1.10.0  
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.10.0 (from versions: 1.12.0, 1.12.1)
ERROR: No matching distribution found for onnxruntime==1.10.0
```

**OS Version:**
macOS Monterey, Silicon

**Rembg version:**
v2.0.21

**Comment by danielgatis** [comment]
python version?

**Comment by bramses** [comment]
@danielgatis Python 3.9.12

also apparently m1 cant use 1.10.0 https://github.com/microsoft/onnxruntime/issues/12502#issuecomment-1209648398

**Comment by danielgatis** [comment]
I will try to upgrade the onnx lib to 1.12 version. tks!

**Comment by repushko** [comment]
I've fixed that: https://github.com/danielgatis/rembg/pull/279

Awaiting approval

**Comment by repushko** [comment]
It's merged, I guess we can close the issue now
