### ISSUE TITLE
Using with python 3.8.8

### ISSUE THREAD

**Issue by jamie-reconlabs** [danielgatis/rembg#281]
Hi Daniel,

We have been using rembg succesfully for several projects in our servers. We use python 3.8.8 and so far so good. It's not an option for us to change to python 3.9. Since a few days ago, we cannot install rembg any more by running `pip install rembg`

In our working server (with python 3.8.8), the output of `pip list` says our rembg version is 2.0.13. However, attempting to install with with `pip install rembg==2.0.13`, also fails with  
`
ERROR: Could not find a version that satisfies the requirement rembg==2.0.13 (from versions: none)
ERROR: No matching distribution found for rembg==2.0.13
`

Is there any workaround for this?

**Comment by danielgatis** [comment]
Today, on pypi.org only 3.9 is available.

To install another tag version try this:
```
pip install git+https://github.com/danielgatis/rembg.git@v2.0.13
```

**Comment by danielgatis** [comment]
@jamie-reconlabs good news! the new version has support for this python version, try install it plz :)
