### ISSUE TITLE
How to run it on GPU?

### ISSUE THREAD

**Issue by MlLearnerAkash** [danielgatis/rembg#283]

**Comment by danielgatis** [comment]
just install the gpu version

```
pip install rembg[gpu]
```

**Comment by MlLearnerAkash** [comment]
Thanks for your reply.

But after even install ```pip install rembg[gpu]```, I don't think it is invoking GPU because there is no inference time difference between its CPU version inference time and GPU version inference time.

**Comment by miloszmat123** [comment]
same issue here, is there any way to change it?
