### ISSUE TITLE
Importing rembg prevents opencv from working

### ISSUE THREAD

**Issue by theflyingzamboni** [danielgatis/rembg#288]
**Describe the bug**
When I try to import rembg to a python file or interpreter, all cv2 functionality ceases to work. Running any cv2 command will result in no action performed in the interpreter, and a script just hangs. Removing the rembg import causes cv2 functions to work normally again. It is not necessary to even use a rembg function to cause the bug, simply importing it is enough. No warning or error is ever thrown.

**To Reproduce**
Run:
```import cv2
import numpy as np
import rembg

img = np.ones((100, 100, 3), np.float32)
cv2.imshow('x', img)
cv2.waitKey(0)
```

**Expected behavior**
I expected it to work and not break other things.

**OS Version:**
Windows 10 Home

**Rembg version:**
v2.0.24

**Python version**
3.9.7

**Comment by danielgatis** [comment]
rembg uses the headless version. Take a look at here:
https://pypi.org/project/opencv-python-headless/

**Comment by theflyingzamboni** [comment]
You might consider having a headed package as well. Most people operating desktops are just going to have normal cv2 installed, and requiring the headless version makes this package a bit of a no-go.

**Comment by Interpause** [comment]
For reference, albumentations auto-detects if opencv is alr installed in its `setup.py` to get around this issue: https://github.com/albumentations-team/albumentations/blob/main/setup.py
