### ISSUE TITLE
Running on a GPU

### ISSUE THREAD

**Issue by cihadturhan** [danielgatis/rembg#29]
Hello Daniel,

This project works great out of the box. Thanks for sharing.

I'm working on a hobby project but I realized it works slow on CPU (30 sec for a 1200x1800 image).

What I wonder is, if I use a server with a GPU support (e.g. google compute engine), how much the result will change.
I saw [this line](https://github.com/danielgatis/rembg/blob/8d5e4aba5db7df90fe87f44fee605229c122984d/src/rembg/u2net/detect.py#L68) so I think it will use CUDA if it's available. Is this correct?

The last question is, how much performance boost I will be able to see? 2x or 3x maybe?
Thanks,
Cihad

**Comment by danielgatis** [comment]
take a look at here:
https://github.com/NathanUA/U-2-Net/issues/35
