### ISSUE TITLE
Crop transparent background

### ISSUE THREAD

**Issue by nikevp** [danielgatis/rembg#300]
Background: 
I am trying to detect the primary color in objects. I am using rembg to remove the background noise to increase accuracy. However, I am running into an issue where the transparent background is treated as "black" by opencv. 

Ask:
I took a look at the args for `remove()` and I didn't see a way to crop/trim the transparent background. Is there a way to remove all of the transparent background from the image and resize to just the object? I found this solution https://stackoverflow.com/a/1905468 but it isn't perfect.

BTW. Awesome package, thank you!

**Comment by nikevp** [comment]
I ended up just going the stackoverflow route. Roughly: 

`
# crop background
output_img = Image.fromarray(img_modified)
output_img.getbbox()  # (64, 89, 278, 267)
cropped_pil_img = output_img.crop(output_img.getbbox())
img_modified = np.asarray(cropped_pil_img)
`

**Comment by yunusemrecetin** [comment]
How can apply these changes to my setup? Can you help me with this subject?
