### ISSUE TITLE
[BUG] argmax_dispatcher() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by Sherman-Liu** [danielgatis/rembg#302]
**Describe the bug**
When using rembg with -m u2net_cloth_seg option, it would give out error message “argmax_dispatcher() got an unexpected keyword argument 'keepdims'”, with no output file in the output folder.

**To Reproduce**
Just run “rembg p _inputfolder_ _outputfolder_ -m u2net_cloth_seg”

**Expected behavior**
The photo should be processed with no error.

**Images**
Any input images would trigger error.

**OS Version:**
Windows 10 19044.1889

**Rembg version:**
v2.0.25

**Additional context**
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32

**Comment by brianmcdonnell** [comment]
Looks like the requirements.txt is incorrect. It lists `numpy==1.21.6`, but `1.21.6` version of `argmax` doesn't have `keepdims` as parameter.  `1.22.0` does have it.

https://github.com/numpy/numpy/blob/v1.21.6/numpy/core/fromnumeric.py#L1122
https://github.com/numpy/numpy/blob/v1.22.0/numpy/core/fromnumeric.py#L1128

Unfortunately after upgrading to numpy 1.22.0 while the `rembg` no longer crashes using `u2net_cloth_seg`, the output images for `u2net_cloth_seg` are broken (the other models still work fine).

**Comment by davidfant** [comment]
Was anyone able to solve this?
