### ISSUE TITLE
[BUG] Could not download from google drive, especially for users in China.

### ISSUE THREAD

**Issue by Mikachu2333** [danielgatis/rembg#303]
## Besides, for Chinese users, we couldn't access to the Google's products due to the FireWall of China. Could you please use the following websites or just upload the model files to github as an alternative choice?

https://www.mediafire.com/
https://www.pcloud.com/
https://www.zippyshare.com/
https://www.mediafire.com/
https://depositfiles.com/
http://uploaded.net/

Really Sorry for bother.

**Comment by danielgatis** [comment]
done!
https://github.com/danielgatis/rembg/blob/main/README.md#models
