### ISSUE TITLE
[BUG] rembg changes the orientation of the picture from portait to landscape

### ISSUE THREAD

**Issue by tommysalt** [danielgatis/rembg#304]
**Describe the bug**
```
Input image:    3000x4000
Output image:   4000x3000 
```
I'm using rembg for 3D rendering and require the orientation to not change in the pipeline. 

**To Reproduce**
`rembg i path/to/input path/to/input`

**Expected behavior**
The orientation should be taken over to the output image.

**Rembg version:**
v2.0.25

**Comment by murfel** [comment]
I confirm the bug is still present.
