### ISSUE TITLE
Incorporate https://github.com/xuebinqin/DIS version 2 when it comes out?

### ISSUE THREAD

**Issue by julianadormon** [danielgatis/rembg#307]
@danielgatis  Thank you for this amazing project!
Will you consider incorporated this model https://github.com/xuebinqin/DIS Version 2 into your package once it is released?
The results look amazing for fine details, such as hair.
Thanks again.

**Comment by AlonDan** [comment]
If possible, that will be amazing!

**Comment by rinab301** [comment]
Hi,
How can I use rembg for doing image processing for the output without the backround, and then return the original backround after my changes on the main object?
Do you have code example for this?

Thank

**Comment by polavishnu4444** [comment]
@danielgatis - Any plan for moving to DIS?

**Comment by Lute-4** [comment]
up
