### ISSUE TITLE
how to choose model by different param  [Question]

### ISSUE THREAD

**Issue by wangping886** [danielgatis/rembg#308]
i install  by  'pip install rembg'  cpu version  and then start by 'rembg s'
rembg, version 2.0.23

and i curl 'http://127.0.0.1:5000?m=u2netp[2]&url=imgurl'
doesn't occur error.  i mean that  use different m doesn't effect

doesn't support param m in this version ?  how can i choose model by different param

**Comment by danielgatis** [comment]
try:

```
http://127.0.0.1:5000?model=...&url=...
```

**Comment by wangping886** [comment]
take effect after using model ! thanks for your timely reply .
