### ISSUE TITLE
Performance warning

### ISSUE THREAD

**Issue by babuus** [danielgatis/rembg#309]
**Describe the bug** @danielgatis 
I am getting performance warning and it is saying 
Try decreasing discard_threshold or start with a larger shift 
![image](https://user-images.githubusercontent.com/38039777/191897736-1738574c-c395-4776-81f4-1b4191d8275e.png)

**To Reproduce**
I was using 2000x2000 image to remove bg

**OS Version:**
win 11

**Rembg version:**
v2.0.21

**Comment by wangping886** [comment]
same problem .  small px of image still  output this waring

**Comment by dmoklaf** [comment]
The warning seems to come from the alpha matting performed by the pymatting library:
https://github.com/pymatting/pymatting/issues/19

**Comment by eafpres** [comment]
I am seeing this as well, changing the thresholds in your api does impact this, but it appears you don't expose the paramters that pymatting is complaining about?

**Comment by joecodecreations** [comment]
would be good to have a solution to this. I'm using even smaller image sizes and getting this.

**Comment by babuus** [comment]
Reduce the image size or increase the hardware req.

**Comment by osmancakir** [comment]
also have this problem. running it on a mac m1 pro 16gb ram

**Comment by btschwertfeger** [comment]
Same problem here while applying to 4K image on Ubuntu with 64 GB RAM.
