### ISSUE TITLE
[BUG] ...RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1029 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Program Files\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

### ISSUE THREAD

**Issue by chelsea456** [danielgatis/rembg#312]
when i run rembg gpu has it error : RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1029 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Program Files\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

**Comment by dandumit** [comment]
I have the same issue. when you find a solution please share.

**Comment by chelsea456** [comment]
> I have the same issue. when you find a solution please share.
> 
> 

I don't find solution, but i run on window is activate but on macos has error

**Comment by togaiaoi** [comment]
I also have the same issue on windows 11.

**Comment by noDGodiaev** [comment]
The same issue on Win10

**Comment by Andebugulin** [comment]
The same issue, smth always happens while working with c++ :(

**Comment by Jangsoodlor** [comment]
`pip uninstall rembg[gpu] onnxruntime-gpu`
Works for me. But you won't be able to use GPU acceleration (Which [based on my research](https://onnxruntime.ai/) seems to only supports [NVIDIA GPUs](https://onnxruntime.ai/docs/execution-providers/) for inferencing (I could be wrong though)).

**Comment by disconnect00** [comment]
I've found a solution for this. I changed my installed Python folder from C:\Users to D:. I think it's a permission issue. I'm using Windows 10

**Comment by baimoda** [comment]
重新安装包‘onnxruntime’,问题解决了

**Comment by baimoda** [comment]
我用的是win10，就是package的问题，重新安装onnxruntime,解决问题。

**Comment by NeoNeetPro** [comment]
I also have same issue.

**Comment by hansnolte** [comment]
The same problem also with the new v2.0.30 version.
I have tried the suggestions of jangsoodlor and disconnect00, both unfortunately without success.
Does anyone else have any tips?

I am on Win 10.

**Comment by oldoty-moco** [comment]
I am also facing the same problem on Windows 10, v2.0.30. I have tried re-installing the appropriate versions of CUDA, ONNX Runtime and cuDNN to no avail.

**Comment by gopfranco** [comment]
I changed the install directory to one in my Documents folder and that seemed to fix it.

**Comment by dikshantchadha77** [comment]
> 

New here, can you please tell how to change the install directory ? Thank you

**Comment by JimGaleForce** [comment]
Win10: For me, it appears this was because of multiple python installations. The traceback path showed 2 different paths, miniconda3 and python39. I also have python310 installed. I solved it by putting on another machine that only has one python installation. However, another way might be to rename all python folders, but one, so that the PATH variables only resolve to one. Hopefully, it's the same one as the onnx lib install. Otherwise, you may have to reinstall this package. ANOTHER way, if other apps are not dependent on your current installs is simply to uninstall all python, reinstall one python, then install this package. HTH

**Comment by treksis** [comment]
same issue here.

**Comment by judy** [comment]
Absolutely helped, thank you! I didn't know about procmon either, that's going to be a very useful tool in the future.

I referred to your solution [in this thread](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/issues/3#issuecomment-1470024586) where people are having the same issue.

**Comment by treksis** [comment]
I solved with

```
pip install -r requirements.txt --ignore-installed
```

I got some warning stuffs but it works

<img width="888" alt="image" src="https://user-images.githubusercontent.com/54779707/226130367-d149e7ca-90b9-457e-8d54-b84cbeba7fca.png">

**Comment by sanyuzhang** [comment]
Works for me:
```
pip uninstall rembg //uninstall rembg
pip uninstall onnxruntime //uninstall onnxruntime
pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
```

**Comment by Zyin055** [comment]
I went down the rabbit hole of trying to get it working on the GPU on Windows. It's not worth the hassle, just uninstall the GPU version and let it use the CPU, it's plenty fast. Thanks @Jangsoodlor `pip uninstall rembg[gpu] onnxruntime-gpu`

**Comment by FoliAGEQBS** [comment]
> > 对我有用：
> > ```
> > pip uninstall rembg //uninstall rembg
> > pip uninstall onnxruntime //uninstall onnxruntime
> > pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> > ```
> 
> 这根本不起作用

If it does not work, please make sure you use the python in the Stable-Diffusion directory

**Comment by youuoypi** [comment]
> 

how to use the python in the SD directory? Thank you.

**Comment by duoduo369** [comment]
Works for me.win 11

秋叶stable diffussion整合包，首先关闭运行的ui。

找到里面的python.exe后

 .\python.exe -m pip uninstall rembg[gpu] onnxruntime-gpu

![image](https://github.com/danielgatis/rembg/assets/6789022/afcaf049-51be-490b-88a6-4b1e7ae1119f)

**Comment by Jasson** [comment]
> Works for me.win 11
> 
> 秋叶stable diffussion整合包，首先关闭运行的ui。
> 
> 找到里面的python.exe后
> 
> .\python.exe -m pip uninstall rembg[gpu] onnxruntime-gpu
> 
> ![image](https://private-user-images.githubusercontent.com/6789022/290533730-afcaf049-51be-490b-88a6-4b1e7ae1119f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTU5ODYsIm5iZiI6MTcwNDE1NTY4NiwicGF0aCI6Ii82Nzg5MDIyLzI5MDUzMzczMC1hZmNhZjA0OS01MWJlLTQ5MGItODhhNi00YjFlN2FlMTExOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDAzNDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRjYjBkODI3YmVmN2IzNzVkNzcyMmFlMWJjOWUwYzk0ZDY0Y2RhOTI4YjJhM2Y2ZjY3ZWUyZDc5NzVlZTk4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e5ft5KWjPJvNjsE1s9wmbFzH9cjgsZpD44icJC2345I)

在执行install解决问题

**Comment by nightwalker89** [comment]
> Works for me:
> 
> ```
> pip uninstall rembg //uninstall rembg
> pip uninstall onnxruntime //uninstall onnxruntime
> pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> ```
Thank

**Comment by shynesss** [comment]
> Works for me.win 11
> 
> 秋叶stable diffussion整合包，首先关闭运行的ui。
> 
> 找到里面的python.exe后
> 
> .\python.exe -m pip uninstall rembg[gpu] onnxruntime-gpu
> 
> ![image](https://private-user-images.githubusercontent.com/6789022/290533730-afcaf049-51be-490b-88a6-4b1e7ae1119f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzY3MTYsIm5iZiI6MTcwNjc3NjQxNiwicGF0aCI6Ii82Nzg5MDIyLzI5MDUzMzczMC1hZmNhZjA0OS01MWJlLTQ5MGItODhhNi00YjFlN2FlMTExOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDgzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI1MjQ3NTRlODNhMTBmMDYwZjAyZTQzZjNjMTlkNDYzOGNkNGI5NzU3MmY3M2FiNTcyYjFiMDk0YmIzNzFhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.twQDI3XmEQUcz7ntuqPro1Xj3zuyYBl-Yz3KBXCLi2w)

thanks!

**Comment by 7kms** [comment]
> Works for me:
> 
> ```
> pip uninstall rembg //uninstall rembg
> pip uninstall onnxruntime //uninstall onnxruntime
> pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> ```

It's really help me. By the way, you should be care with your python location, especially your executable python isn't the golbal one.
For me,because of I use a embeding python, so I should exec as below:
```shell
.\system\python\python.exe -m 'pip' uninstall rembg
.\system\python\python.exe -m 'pip' uninstall onnxruntime
.\system\python\python.exe -m 'pip' install rembg[gpu] onnxruntime-gpu

```

**Comment by Nico-07** [comment]
> Works for me.win 11
> 
> 秋叶stable diffussion整合包，首先关闭运行的ui。
> 
> 找到里面的python.exe后
> 
> .\python.exe -m pip uninstall rembg[gpu] onnxruntime-gpu
> 
> ![image](https://private-user-images.githubusercontent.com/6789022/290533730-afcaf049-51be-490b-88a6-4b1e7ae1119f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODI2NjEsIm5iZiI6MTcxMDU4MjM2MSwicGF0aCI6Ii82Nzg5MDIyLzI5MDUzMzczMC1hZmNhZjA0OS01MWJlLTQ5MGItODhhNi00YjFlN2FlMTExOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTZUMDk0NjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM0NDUyNjg0NzU2ODc2MGMwMWVlNzExOTgxMjNhY2MxOTc5NTRmODM0Nzg3OWExMGFmMTBmNjNkMjk4YmVkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fF8ytlvXMpnqjHyklJh2ppEM5yFXw-KAMEwZIq1WUDw)

THANKS

**Comment by tkz24589** [comment]
see https://onnxruntime.ai/docs/install/，install onnxruntime-gpu in pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/. good!

**Comment by aswordok** [comment]
> 是package的问题，重新安装onnxrunti

U are right.

**Comment by hushanhsiang** [comment]
> Works for me:
> 
> ```
> pip uninstall rembg //uninstall rembg
> pip uninstall onnxruntime //uninstall onnxruntime
> pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> Yes problem fixed~~ Thanks.

**Comment by hushanhsiang** [comment]
> Works for me:
> 
> ```
> pip uninstall rembg //uninstall rembg
> pip uninstall onnxruntime //uninstall onnxruntime
> pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> ```

Thanks~~

**Comment by tomgwasira** [comment]
My comment is not necessarily to do with rembg, but this error can also be caused when your ONNXRuntime version does not support your TensorRT version.

**Comment by Royrychou** [comment]
> 对我有用：
> 
> ```
> pip uninstall rembg //uninstall rembg
> pip uninstall onnxruntime //uninstall onnxruntime
> pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support
> ```

it works but...with out onxxruntime other nodes would be error

**Comment by xam0482** [comment]
应该是 onnxruntime onnxruntime-gpu 两个版本不一致造成的 , 更新成相同的版本

**Comment by listmaster21** [comment]
pip uninstall rembg //uninstall rembg
pip uninstall onnxruntime //uninstall onnxruntime
pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support

its work for me 2 :) thanx a lot :)

**Comment by lzluuu** [comment]
It worked when I changed ONNX Runtime-gpu version to 1.17.1 (My cuda version is 12.1), even Runtime-gpu 1.18.1 doesn't work

**Comment by 16638226337-cell** [comment]
I successfully solved this error, "EP ERROR onnxruntime_providers_tensorrt.dll" is due to insufficient permissions, I use aconda and win10 to install facefusion, solution: you need to install the facefusion folder and aconda to the C drive directory at the same time, this problem may be a bug in software development, There is also a possibility that it is an onnxruntime version issue
