### ISSUE TITLE
Not able to use 'remove', Getting some Access Denied with some errors

### ISSUE THREAD

**Issue by shreyash8** [danielgatis/rembg#317]
**Issue Description**

Not able to use 'remove' while using rembg as a library in python.

**The code which I tried:**
```
from rembg import remove
from PIL import Image

input_path = 'sample_images/0Q8IKWLK95RKOD0P_5.jpg'
output_path = 'output.jpg'

input_ = Image.open(input_path)
output = remove(input_)
output.save(output_path)
```

**Error Received**
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab 

Traceback (most recent call last):
  File "rembg_test.py", line 8, in <module>
    output = remove(input_)
  File "/home/rembg_testing/venv/lib/python3.8/site-packages/rembg/bg.py", line 133, in remove
    session = new_session("u2net")
  File "/home/rembg_testing/venv/lib/python3.8/site-packages/rembg/session_factory.py", line 60, in new_session
    ort.InferenceSession(
  File "/home/rembg_testing/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/rembg_testing/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg: 

**Rembg version:**
v2.0.25

**Comment by shreyash8** [comment]
So, I have downloaded the 'u2net.onnx' from the provided link,  This solves the 1st issue.

But, I am still getting the Runtime Error.

![Screenshot from 2022-10-14 19-27-46](https://user-images.githubusercontent.com/30978739/195865174-55fb56c1-4e1c-4523-8ad9-3efc50df46e7.png)

**Comment by shreyash8** [comment]
Solved the issue, It was a problem with onnx runtime.

**Comment by Rams901** [comment]
can you elaborate more how you the solution?

**Comment by Rams901** [comment]
That's great. Thanks for sharing.
How about the access denied file, where exactly do you put the file? I'm using colab I tried creating a folder called u2net and putting the file there but didn't work.

**Comment by shreyash8** [comment]
> That's great. Thanks for sharing. How about the access denied file, where exactly do you put the file? I'm using colab I tried creating a folder called u2net and putting the file there but didn't work.

Folder name should be  .u2net  
It should be in the user home directory.
