### ISSUE TITLE
[BUG] [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /root/.u2net/u2net.onnx failed:Load model /root/.u2net/u2net.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by Sahar-DataScience** [danielgatis/rembg#318]
**Describe the bug**
Access denied with the following error:

 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab 

**To Reproduce**
from rembg import remove
from PIL import Image
for input_path in glob.glob('/content/multi_class_input/*.jpg'):
  output_path = input_path.replace('input','output')
  input = Image.open(input_path)
  output = remove(input)
  output.save(output_path)

**Expected behavior**
output foreground png 

**Images**
Input images to reproduce.

**OS Version:**
iOS 22

**Rembg version:**
v2.0.21

**Additional context**

**Comment by michaldivis** [comment]
I'm having the same problem.

**Comment by luis-armando-perez-rey** [comment]
I'm also having the same problem.

**Comment by Faivrem** [comment]
Hello, I have the same issue. Too much request on Google Drive.

**Comment by danielgatis** [comment]
This is kind google download protection, but you can download the models manually:

https://github.com/danielgatis/rembg#models

**Comment by Dhruvagwal** [comment]
I am also want the custom path option because it's difficult to handle during deployment 
So i made some changes and added custom path option in the code ....

REPO URL : https://github.com/Dhruvagwal/rembg_with_custom_path/tree/master

I tested on my own code so feel free to check it and use it on our own risk...


from rembg import remove
import sys

def rem_bg(input_path, output_path, model_path):
        with open(input_path, 'rb') as i:
            with open(output_path, 'wb') as o:
                input = i.read()
                output = remove(input,model_path=model_path)
                o.write(output)
if __name__ == "__main__":
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    model_path = sys.argv[3]
    rem_bg(input_path, output_path, model_path)

**Comment by R0Wi** [comment]
> This is kind google download protection, but you can download the models manually:
> 
> https://github.com/danielgatis/rembg#models

@danielgatis since I also stumbled over this and saw that Google Drive's virus protection was the problem: would it be a suitable solution to host the model files here on GitHub? Maybe a new repository `danielgatis/rembg-models` could do the trick if you don't want to bloat the main repo here?

**Comment by danielgatis** [comment]
models here:
https://github.com/danielgatis/rembg/releases/tag/v0.0.0

**Comment by ylimani** [comment]
> Hello, Here is the working solution if you can't figure out where to put the file.
> 
> 1-Download the file from the link provided. (name is u2net.onnx) 2- `cd ~ mkdir .u2net cp <full_path_to_file>/u2net.onnx u2net.onnx cd <full_path_to_work_repo>`
> 
> Note: If you're using colab, you have to use magic '%' before each cd so it actually moves to that path.

I'm kind of a e newbie here, but where would I put the file manually on Google Colab directory, thank you
