### ISSUE TITLE
[BUG] ... removing clothes

### ISSUE THREAD

**Issue by ajhernandezgrupoviamar** [danielgatis/rembg#321]
this image show a bug with the clothes
https://img.freepik.com/free-photo/young-beautiful-woman-with-red-curly-hair-standing-profile-wearing-suit-looking-camera-with-confident-face-expression-white-background_176420-48822.jpg?w=2000

**Comment by Sba-Stuff** [comment]
Using "u2net_human_seg" model, I get this result. 

![1](https://user-images.githubusercontent.com/36412543/232201260-f835d234-f8e3-493c-92a8-7099af9fa963.png)
