### ISSUE TITLE
cannot cache function '_make_tree': no locator available for file '/var/lang/lib/python3.8/site-packages/pymatting/util/kdtree.py'

### ISSUE THREAD

**Issue by souravjamwal77** [danielgatis/rembg#323]
**Describe the bug**
While installing on AMI-2 (AWS Lambda Image) caching not working. 

**To Reproduce**
Try to install the package in lambda-based docker images.

**Expected behavior**
Either caching should be disabled or users should have option to disable caching.

**Images**
Input images to reproduce.

**OS Version:**
AWS AMI-2

**Rembg version:**
v2.0.25

**Additional context**
```
cannot cache function '_make_tree': no locator available for file '/var/lang/lib/python3.8/site-packages/pymatting/util/kdtree.py'
```

**Comment by rnag** [comment]
@souravjamwal77 In case it is helpful, I've created an almost identical project for AWS environments, [rembg-aws-lambda](https://github.com/rnag/rembg-aws-lambda). It strips down some code, such as dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting `U2NET_HOME` is not required anymore.

Install with:

```console
pip install rembg-aws-lambda
```

Check it out and let me know if it works for your use case. See also: https://github.com/danielgatis/rembg/issues/373
