### ISSUE TITLE
[Question] How to host on AWS Lambda?

### ISSUE THREAD

**Issue by Danoctum** [danielgatis/rembg#326]
Currently trying to host this ono AWS Lambda.

Steps I've done:
1. Clone image from dockerhub and push to private ECS repository
2. Create Lambda from Docker container on architecture x86_64 and expose port 5000
3. Added NUMBA_CACHE_DIR environment variable with value `/tmp`

After doing this configuration and running the Lambda, I get the following error:
```
/usr/local/lib/python3.9/dist-packages/numba/np/ufunc/parallel.py:323: UserWarning: Could not obtain multiprocessing lock due to OS level error: [Errno 38] Function not implemented
```

According to my research, this is because Lambda's can not run on multiple cores in Python (even when raising Lambda RAM to > 1769MB).
A fix could be to downgrade to Python 3.7, but that would mean getting an older version of this library.

I've tried to search the source code for usage of `Multiprocessing.Pools`, which could be replaced by `Multiprocessing.Queue` as a fix, but I think that's in a library that rembg makes use of. 

Does anyone have an idea how to fix this?

**Comment by zfLQ2qx2** [comment]
@Danoctum For Lambda the number of processors you receive is a function of memory. It's not official but people have done testing and it seems that you get one full vCPU for every 2GB of RAM you request in the function definition. An alternate method might be use use an ECS task where you can set the number of CPUs explicitly. In both cases you'll probably want a wrapper script to copy the input image from S3 and write the result back to S3. I'm not clear if a GPU is required or not.

**Comment by niteshanandan** [comment]
@Danoctum Were you able to resolve this?

**Comment by niteshanandan** [comment]
@zfLQ2qx2 I've increased my lambda to 4GB of RAM but to no avail.

**Comment by mayankrana2022** [comment]
I have successfully deployed lambda. I never faced this issue. May be I could help you guys out.
Let me know what info/configuration you need.

**Comment by peterheb** [comment]
Here is a Dockerfile where I was able to get it running. I'm not really a Python developer so am a bit out of my depth here, but maybe you'll find it useful: https://github.com/peterheb/rembg-lambda

**Comment by rnag** [comment]
@Danoctum and others - In case it is helpful, I've created an almost identical project for AWS environments, [rembg-aws-lambda](https://github.com/rnag/rembg-aws-lambda). It strips down some code, such as dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting `U2NET_HOME` is not required anymore.

Install with:

```console
pip install rembg-aws-lambda
```

Check it out and let me know if it works for your use case. See also: https://github.com/danielgatis/rembg/issues/373
