### ISSUE TITLE
nnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE :[BUG] ...

### ISSUE THREAD

**Issue by merjekrepo** [danielgatis/rembg#328]
Hello,

When I run the code below, I get the following error:

onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/fatihshen/.u2net/u2net.onnx failed:Load model /Users/fatihshen/.u2net/u2net.onnx failed. File doesn't exist

```
from rembg import remove
from PIL import Image
input_path = 'my_cat.jpeg'
output_path = 'my_cat.png'
input = Image.open(input_path)
output = remove(input)
output.save(output_path)
```

I am using Macbook Pro (macOS Monterey, version 12.2, M1 chip). My Python is 3.10.2.

**Comment by Flashwalker** [comment]
the same

**Comment by sakuraiyuta** [comment]
I got same problem and found workaround:

- Download `u2net.onnx` from https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab
- Put `u2net.onnx` to path `${HOME}/.u2net/u2net.onnx`

Maybe reached the limit to access the file on Google Drive.

**Comment by danielgatis** [comment]
nowadays the models are downloaded from github instead of google drive, so this bug is fixed.
