### ISSUE TITLE
Help needed with understanding the best use of alpha matting

### ISSUE THREAD

**Issue by ashkaps** [danielgatis/rembg#33]
Hi @danielgatis ,
From my previous comment on , i did some more research and experimentation and have found that the combinations of alpha matting fg, bg and erosion works well for a set of objects.
For example 240-10-3 with estimate_alpha_cf and estimate_foreground_ml works really really well for animals or things with fine edges like hairs.
190-100-3 with estimate_alpha_rw and estimate_foreground_cf works ok for humans and excellent for other non-living objects like phone, laptop, fruits, (things with more crisp boundaries).

Any thoughts or understanding on how to make the results for humans better?

I also have one other observation I found and thought to share. 
For the same code and different machine specs, I am seeing different output. The main difference is of the CPU and RAM (both my machines don't have a GPU). In your opinion, does the capacity of the machine matters?

Uploading a few samples from my experiments. Any direction or help would be appreciated.

https://drive.google.com/file/d/1m0EokvSPmqjDp3hov5qm5jlcq6wkD8Rt/view?usp=sharing

**Comment by danielgatis** [comment]
> Any thoughts or understanding on how to make the results for humans better?

Nope. There is no silver bullet for this. take a look at https://github.com/NathanUA/U-2-Net/issues/75


> In your opinion, does the capacity of the machine matters?

Nope.

**Comment by jason-engage** [comment]
@danielgatis Hey did you ever figure out the solution to getting rid of that grey outline?
