### ISSUE TITLE
Need clear documentation

### ISSUE THREAD

**Issue by WebLeach** [danielgatis/rembg#333]
**My confusions**
You have mentioned different pretrained dataset and drive link and said they are stored in .u2net folder.
But its unclear wheather if we just download others (general one is auto downloaded) and throw them in the folder, they will be auto used.

Also its confusing to me about multiple input methods, yes its nice to have multiple ways, but will importing the same file with pillow provide any difference?

Sorry about my silly confusions (would be nice if the discussion tab enabled, so such FAQ could be done there?)

**Os version**
Win 11

**Rembg version:**
v2.0.21

**Comment by DavidNTompkins** [comment]
I'm not the owner, just some guy, but on your first point - to use a different model you'll need download the model to the .u2net folder and then specify it. Here's a line that seems to do that in python (assuming you've imported all of rembg).

`output = rembg.remove(input,session=rembg.session_factory.new_session('u2net_human_seg'))`

**Comment by RaSan147** [comment]
Got it, so I can't do it the `commandline` way. Thanks

**Comment by WebLeach** [comment]
Got it, so I can't do it the `commandline` way. Thanks

**Comment by DavidNTompkins** [comment]
Oh you probably can, it's just not what I used. I would try adding -m "model_name" to your command. Best of luck
