### ISSUE TITLE
[BUG] RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int ()(int, Eigen::ThreadPoolInterface), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg:

### ISSUE THREAD

**Issue by KevinVanEijk** [danielgatis/rembg#339]
The following error happens even if OMP_NUM_THREADS was set:
RuntimeError: /onnxruntime_src/onnxruntime/core/platform/posix/env.cc:183 onnxruntime{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 0 error msg: 

I fixed this by adding back the following line in session_factory:
`sess_opts.intra_op_num_threads = int(os.environ["OMP_NUM_THREADS"])`

This line was originally added by this pull request:
https://github.com/danielgatis/rembg/pull/203

But lost with this commit:
https://github.com/danielgatis/rembg/commit/738cf156afaee3201f78a6a607e78c611dd69437

**Comment by danielgatis** [comment]
merged!
