### ISSUE TITLE
[BUG] Please update remove to not use deprecated PIL resampling function!

### ISSUE THREAD

**Issue by gobenchain** [danielgatis/rembg#340]
Remove() no longer works because the new PIL version no longer supports the "Resampling" method.

Line 21 in session_base.py should be changed to:
im = img.convert("RGB").resize(size, Image.LANCZOS)

Thanks :)

**Comment by samiede** [comment]
I als have the same problem. How can I resolve this?

**Comment by anna-golub** [comment]
It worked for me when I uninstalled the latest version of rembg (2.0.29) and installed an older one. I used 2.0.24, but maybe some others will work too

**Comment by samiede** [comment]
I made a fork (and a PR) that resolves this!
