### ISSUE TITLE
Docker Instance WebUI doesn't work

### ISSUE THREAD

**Issue by AvMavs** [danielgatis/rembg#343]
**Describe the bug**
It does not let me open the WebUI, and gives me an error.

**To Reproduce**
Open docker, and run the command `docker run -p 5000:5000 danielgatis/rembg s`

1. Go to 'http://localhost:5000'
2. See error.

**Expected behavior**
The RemBG WebUI should launch.

**Images**
![image](https://user-images.githubusercontent.com/82929505/202125748-cd261cd6-5426-4dbc-8b25-46a1360bf422.png)

**OS Version:**
Ubuntu 22.04

**Rembg version:**
v2.0.21 (docker)

**Logs:**

```yaml
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     172.17.0.1:44726 - "GET / HTTP/1.1" 422 Unprocessable Entity
INFO:     172.17.0.1:44726 - "GET / HTTP/1.1" 422 Unprocessable Entity
INFO:     172.17.0.1:58970 - "GET / HTTP/1.1" 422 Unprocessable Entity
INFO:     2.3.4.63:12019 - "GET / HTTP/1.1" 422 Unprocessable Entity
INFO:     2.3.4.63:12020 - "GET / HTTP/1.1" 422 Unprocessable Entity
```

**Comment by AlfredUFY** [comment]
Try `http://localhost:5000?url=imageurl`, this works for me

**Comment by AvMavs** [comment]
What format did you use for the imageurl? using https://website.com/image.png just opened that webpage for me!

**Comment by danielgatis** [comment]
```
The RemBG WebUI should launch.
```

There is no REMBG WebUI.
It is just a URL `http://localhost:5000/?url=imageurl`

**Comment by AvMavs** [comment]
Can you share an example of the format with a random image link?

**Comment by danielgatis** [comment]
```
http://localhost:5000/?url=https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Wikipedia_Monument_in_Slubice_20190918-8.jpg/800px-Wikipedia_Monument_in_Slubice_20190918-8.jpg
```

**Comment by AvMavs** [comment]
Oh, I used this. I just realised my issue was Brave redirecting to the image. 🤦🏻‍♂️. Works great on Firefox, thank you!
