### ISSUE TITLE
[BUG] ...I am to pip install the package but when I apply rembg then it throws the below mentioned error. Not able to access the model from Gdrive

### ISSUE THREAD

**Issue by sameersharma00747** [danielgatis/rembg#346]
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab

**Comment by danielgatis** [comment]
fixed in the last version!
