### ISSUE TITLE
Can't use it on AWS lambda

### ISSUE THREAD

**Issue by mayankrana2022** [danielgatis/rembg#349]
**Describe the bug**
Can't use it on AWS lambda

**To Reproduce**
Create a docker image to use it for creating a lambda function
On calling remove method, lambda fails and results in OSError
"errorMessage": "[Errno 30] Read-only file system: '/home/sbx_user1051'",

**Rembg version:**
v2.0.29 and v2.0.29

**Additional context**
{
  "errorMessage": "[Errno 30] Read-only file system: '/home/sbx_user1051'",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/task/myfunction.py\", line 9, in lambda_handler\n    link = server.process_video(event)\n",
    "  File \"/var/task/server.py\", line 50, in process_video\n    result = remove(frame)\n",
    "  File \"/var/lang/lib/python3.8/site-packages/rembg/bg.py\", line 133, in remove\n    session = new_session(\"u2net\")\n",
    "  File \"/var/lang/lib/python3.8/site-packages/rembg/session_factory.py\", line 51, in new_session\n    pooch.retrieve(\n",
    "  File \"/var/lang/lib/python3.8/site-packages/pooch/core.py\", line 224, in retrieve\n    make_local_storage(path)\n",
    "  File \"/var/lang/lib/python3.8/site-packages/pooch/utils.py\", line 249, in make_local_storage\n    os.makedirs(path, exist_ok=True)\n",
    "  File \"/var/lang/lib/python3.8/os.py\", line 213, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n",
    "  File \"/var/lang/lib/python3.8/os.py\", line 223, in makedirs\n    mkdir(name, mode)\n"
  ]
}

**Comment by niteshanandan** [comment]
@mayankrana2022 Did you hit this by any chance? 
`/var/lang/lib/python3.8/site-packages/numba/np/ufunc/parallel.py:323: UserWarning: Could not obtain multiprocessing lock due to OS level error: [Errno 38] Function not implemented
`

**Comment by mayankrana2022** [comment]
@niteshanandan No, this did not happen with me. I am using a docker image for lambda.
Here's are the dependencies that I am using to deploy it to lambda.

opencv-python-headless==4.6.0.66
rembg==2.0.29

Hope it might help.
