### ISSUE TITLE
Can't use "alpha-matting-base-size" in google colab

### ISSUE THREAD

**Issue by smithee77** [danielgatis/rembg#354]
Hi, I've installed your repo in Google Colab with
`!pip install rembg[gpu]`
And I'd like to modify az option (alpha-matting-base-size). But I can't find it in the usage(help) options:
`!rembg i --help`

Options:
  -m, --model [u2net|u2netp|u2net_human_seg|u2net_cloth_seg|silueta]
                                  model name
                                  [default: u2net]
  -a, --alpha-matting             use alpha
                                  matting
  -af, --alpha-matting-foreground-threshold INTEGER
                                  trimap fg
                                  threshold
                                  [default: 240]
  -ab, --alpha-matting-background-threshold INTEGER
                                  trimap bg
                                  threshold
                                  [default: 10]
  -ae, --alpha-matting-erode-size INTEGER
                                  erode size
                                  [default: 10]
  -om, --only-mask                output only the
                                  mask
  -ppm, --post-process-mask       post process the
                                  mask
  --help                          Show this
                                  message and
                                  exit.

How can I access to this parameter?
Many thanks

**Comment by abhishek0093** [comment]
Hi @smithee77 , did you resolved the issue and find way to change az value there?
