### ISSUE TITLE
`setup.py` should define actual dependencies

### ISSUE THREAD

**Issue by jangop** [danielgatis/rembg#355]
Currently, the packages specified in `requirements.txt` are copied into `setup.py`:

```python
with open(here / "requirements.txt") as f:
    requireds = f.read().splitlines()

[...]

    install_requires=requireds,
```

This is bad practice and makes it difficult to use `rembg` in any project with dependencies.

`requirements.txt` should be used to define a repeatable installation, such as a development environment or a production environment. As such, versions of dependencies contained therein should be as specific as possible.

`install_requires` should be used to indicate dependencies necessary to run the package. As such, versions of dependencies contained therein should be as broad as possible.

Please see [“install_requires vs requirements files” on python.org](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/) or [“requirements.txt vs setup.py” on stackoverflow](https://stackoverflow.com/a/43659126) for more information.

I'd be happy to contribute a PR with looser dependency specifications in `setup.py`.

**Comment by danielgatis** [comment]
```
I'd be happy to contribute a PR with looser dependency specifications in setup.py.
```

Please, your PR is very welcome! Thanks!
