### ISSUE TITLE
program is stuck on the line "from rembg import remove"

### ISSUE THREAD

**Issue by rinab301** [danielgatis/rembg#356]
Hi,
I need to use rembg for removing background and I have a problem:  the program is stuck on the line "from rembg import remove" (I also tried "from rembg.bg import remove"). There isnt any error...  I have python 3.9.5 (also tried 3.7...) and running in with visual studio, and also tried with pycharm. I did "pip install rembg", and also tried to install previous versions of rembg. Nothing worked.  Someone can please help?

**Comment by jangop** [comment]
You may have installed `rembg` in a different environment from the one you are using to execute your code.

Please provide more concise information regarding your setup and how you are trying to run your code.
