### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Digby26** [danielgatis/rembg#377]
Hi, Im running python 3.8.0 and when I try to install I get the below error, I have updated pip and wheel. I have tried locating the log files but they get deleted soon as the attempt fails so I'm unable to open them. I'm on Windows 10

`C:\Users\{user}>pip install rembg==2.0.30
Collecting rembg==2.0.30
  Using cached rembg-2.0.30-py3-none-any.whl (13 kB)
Collecting click~=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting pillow~=9.3.0
  Using cached Pillow-9.3.0-cp38-cp38-win32.whl (2.2 MB)
Collecting pooch~=1.6.0
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting uvicorn~=0.20.0
  Using cached uvicorn-0.20.0-py3-none-any.whl (56 kB)
Collecting numpy~=1.23.5
  Using cached numpy-1.23.5-cp38-cp38-win32.whl (12.2 MB)
Collecting fastapi~=0.87.0
  Using cached fastapi-0.87.0-py3-none-any.whl (55 kB)
Collecting watchdog~=2.1.9
  Using cached watchdog-2.1.9-py3-none-win32.whl (78 kB)
Collecting scikit-image~=0.19.3
  Using cached scikit_image-0.19.3-cp38-cp38-win32.whl (11.3 MB)
Collecting onnxruntime~=1.13.1
  Using cached onnxruntime-1.13.1-cp38-cp38-win32.whl (5.1 MB)
Collecting python-multipart~=0.0.5
  Using cached python-multipart-0.0.5.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting opencv-python-headless~=4.6.0.66
  Using cached opencv_python_headless-4.6.0.66-cp36-abi3-win32.whl (26.1 MB)
Collecting tqdm~=4.64.1
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting scipy~=1.9.3
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + meson setup --prefix=c:\users\{user}\appdata\local\programs\python\python38-32 C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97 C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97\.mesonpy-l7t23cq7\build --native-file=C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      The Meson build system
      Version: 1.0.0
      Source dir: C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97
      Build dir: C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97\.mesonpy-l7t23cq7\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\{user}\AppData\Local\Temp\pip-install-huoo9sjr\scipy_32a0cf31ae834d2187aa93ebc5e60a97\.mesonpy-l7t23cq7\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by eli-schwartz** [comment]
This error message does not come from rembg -- it comes from scipy, which is a dependency of rembg.

Note the issue here is that SciPy 1.9.3 does not provide pre-built wheels for 32-bit Windows anymore, so this attempts to download the SciPy source code sdist and build it from scratch. This fails for you because you don't have a C[^1] compiler installed (Visual Studio is the first one it tried).

[^1]: You need a bunch of things to compile SciPy from source. A fortran compiler is more relevant than a C one, actually. The official guidance of SciPy upstream is that building from source is too complicated for people who aren't experts at build pipelines, and you're better off avoiding it if you can obtain an environment that has wheels: https://scipy.org/install/#source

**Comment by rafaleo** [comment]
I have similar issue and can't upgrade scipy to 1.9.3, having only 1,7.3 installed.
