### ISSUE TITLE
Can I run it without NVIDIA GPU?

### ISSUE THREAD

**Issue by hukacode** [danielgatis/rembg#38]
Hi there,

I got this error because my PC does not have NVIDIA GPU.
Can I run it without GPU?

`rembg -o ~/Downloads/cat.png ~/Downloads/cat.jpg                                                 
/home/huka/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/huka/.local/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/home/huka/.local/lib/python3.8/site-packages/rembg/cmd/cli.py", line 118, in main
    remove(
  File "/home/huka/.local/lib/python3.8/site-packages/rembg/bg.py", line 84, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/home/huka/.local/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f4ad769ff90>`

Many thanks for considering my request.

Best regards,
HungNLK

**Comment by weihaox** [comment]
It works on my Mac. So it may not the problem of NVIDIA GPU. Looks more like a problem caused by the package PIL.

**Comment by danielgatis** [comment]
> Can I run it without NVIDIA GPU?

yes!

**Comment by hukacode** [comment]
Hello @weihaox @danielgatis 

Thank you so much for your supporting.

Best regards,
Huka
