### ISSUE TITLE
Object size reduces with "u2net_clothe_seg"

### ISSUE THREAD

**Issue by shersoni610** [danielgatis/rembg#380]
Hello,

I noticed that with "u2net_cloth_seg" model, the size of the object reduces but the image size  is same as original.  Am I missing something which is specific to this model. All other models work as expected.

Thanks

**Comment by shersoni610** [comment]
With the "girl-1.jpg" example, the clothe_seg model, the original image resize height increases by 3 time and the results are unexpected.

**Comment by shersoni610** [comment]
For the cloth.segmentation, the behavior of these codes are quite different:

outimg = remove(img, session=session, only_mask=False)
#outimg = remove(img)

The second code is better than the first one but there is no segmentation in the second also.

**Comment by jonnyhoff** [comment]
> With the "girl-1.jpg" example, the clothe_seg model, the original image resize height increases by 3 time and the results are unexpected.

My original image of 563 × 845 gets resized to 563 × 2535.
