### ISSUE TITLE
[BUG] output image is not good for images with white background.

### ISSUE THREAD

**Issue by eunwoo** [danielgatis/rembg#382]
**Describe the bug**
I use rembg to remove background. The most of the results are good. but for some images, it generates strange result.
here is '1.jpg'
![1](https://user-images.githubusercontent.com/8966503/215312512-e3ec59a3-888f-40f4-8dc7-431d3aaa57d9.jpg)
here is '3.png'
![3](https://user-images.githubusercontent.com/8966503/215312630-6908551c-0fbc-4032-9cbe-a3722014dd53.png)

**To Reproduce**
        image = Image.open('1.jpg')
        image_result = remove(image)
        image_result.save('3.png')

**Expected behavior**

**Images**
Input images to reproduce.

**OS Version:**
Windows 11

**Rembg version:**
v2.0.30

**Additional context**

**Comment by ashishsaini** [comment]
+1 same issue, not able to remove the white background from AI generated images. 

Input:
![ai_image](https://user-images.githubusercontent.com/5359237/219465456-9f1c432f-eb82-494c-8181-e5008d465034.jpg)

Output:
![rm_bg](https://user-images.githubusercontent.com/5359237/219465523-c3fd582f-944e-4fd8-9f43-4648d5026059.png)

Using default settings, but also tried with alpha matting but no good result.

**Comment by skylarr1227** [comment]
yeah-same issue here and i cannot find a good workaround-any fix for this

**Comment by Flippchen** [comment]
For the first picture I have a solution that at least gives better results. You have to initialize a session with the "u2netp" model and pass it to the remove function.
`
from rembg import remove, new_session
session = new_session("u2netp")
image = Image.open('test.jpg')
image = remove(image, session=session)
image.show()
`

I also found it quite useful to use the ImageEnhancer from Pillow. With it, you can make the images darker, for example.
`
from PIL import Image, ImageEnhance
image = Image.open('test.jpg')
img_enhancer = ImageEnhance.Brightness(image)
image = img_enhancer.enhance(.5)
`

**Comment by ashishsaini** [comment]
@Flippchen looks awesome will, try on other frames.  Thanks 👍

**Comment by jtoy** [comment]
will have a go as well, maybe some visual "unit tests" for others to see.
