### ISSUE TITLE
[BUG] .. How can we make edges smooth here instead of blurry? 

### ISSUE THREAD

**Issue by Zenith21** [danielgatis/rembg#385]
**Describe the bug**
Ground part of the edges are blurry.. how can we have it smooth ?

**To Reproduce**

**Expected behavior**

**Images**
Input images to reproduce. (Below images are after background removal)
![image](https://user-images.githubusercontent.com/17794550/216741675-d423e609-ad90-426e-8305-36779be48955.png)
![image](https://user-images.githubusercontent.com/17794550/216741683-04f56bbd-ccf3-4b31-a277-ba4aba063921.png)

**OS Version:**
iOS 22

**Rembg version:**
v2.0.21

**Additional context**

**Comment by vaseemcholakkan123** [comment]
you can use the second parameter from the documentation to improve the end result
`post_process_mask=True`
