### ISSUE TITLE
How to change the model when use it as a library

### ISSUE THREAD

**Issue by yiouyou** [danielgatis/rembg#387]
How to change the model when use it as a library?

Within the doc, it desribed how the change the model when use it as a command line. But no examples of how to change the model when use it as a library.

**Comment by ansorre** [comment]
I tryed this and worked:

from rembg import remove
from rembg.session_factory import new_session

input_path = 'input.png'
output_path = 'output.png'
model='u2net_human_seg';

with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input = i.read()
        output = remove(input, session=new_session(model))
        o.write(output)
