### ISSUE TITLE
Custom pre-trained model is not used by the library 

### ISSUE THREAD

**Issue by karim-booh** [danielgatis/rembg#388]
Hello,

I have a custom pre-trained model based on this git recommandation, i have my .onnx model and i put it inside .u2net directory, i change the new session with my new model name,
When i execute it it take the last update of u2net train model from git and it seems to overwrite my file i notice this because my train model is heavier than the u2net one and after the execution my model is lighter.
Furthermore, i have no changes between my train model and the u2net on the images that i use.

Mac OS 13.1
Rembg version: v2.0.30

**Comment by Gradylo** [comment]
HI, How was the problem solved?
