### ISSUE TITLE
Speed problem

### ISSUE THREAD

**Issue by z905762202** [danielgatis/rembg#389]
Is there a method called by multiple threads?

**Comment by ShehrozIrfan** [comment]
Hey @z905762202 
I've tried adding the multi-threading, multi-processing and sessions to speed up the process:

<details>
<summary>Using Multi-Processing</summary>

```
import os
import argparse
import ffmpeg
import subprocess
import time
from multiprocessing import Pool

def process_image(image_path):
    # Create the output path for the processed image
    processed_path = os.path.join(processed_directory, os.path.basename(image_path))
    # Call the rembg command for a single image
    subprocess.run(["rembg", "i", image_path, processed_path])


# getting the time when the script started
process_start = time.time()

# Create temporary directories
current_directory = os.getcwd()
tmp_directory = os.path.join(current_directory, "tmp")
frames_directory = os.path.join(tmp_directory, "frames")
processed_directory = os.path.join(tmp_directory, "processed")

if not os.path.exists(frames_directory):
    os.makedirs(frames_directory)

if not os.path.exists(processed_directory):
    os.makedirs(processed_directory)

if __name__ == "__main__":
    # Parse args
    parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video')
    parser.add_argument('input', type=str, help='Input video')
    parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal")
    parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold")
    parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold")
    parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size")
    parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction')
    parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing')
    args = parser.parse_args()

    if not args.skip_extract:
        # Extract video info
        probe = ffmpeg.probe(args.input)
        video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
        width = int(video_stream['width'])
        height = int(video_stream['height'])
        whstr = str(width) + 'x' + str(height)
        framerate = video_stream['avg_frame_rate']

        # Extract input video frames
        print("Extract input video frames...")
        stream = ffmpeg.input(args.input)
        stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")
        ffmpeg.run(stream)

    if not args.skip_process:
        # Set the number of worker processes to use
        num_workers = os.cpu_count()

        # Get a list of image paths to process
        image_paths = [os.path.join(frames_directory, f) for f in os.listdir(frames_directory)]

        # Create a multiprocessing Pool with the specified number of workers
        with Pool(num_workers) as pool:
            # Call the process_image function for each image in the list
            pool.map(process_image, image_paths)

    # Output video
    stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p')
    stream = ffmpeg.output(stream, "output.mp4", crf=22, r=10, acodec='aac', s='360x640', vcodec='libx265')
    ffmpeg.run(stream)

# getting the time when script ends
process_end = time.time()

# Calculate the duration
duration = process_end - process_start

# Display the duration
print("All the process has taken: {} minutes".format(duration / 60))

```
</details>

<details>
<summary>Using Multi-Threading</summary>

```
import os
import threading
import argparse
import ffmpeg
from rembg import remove
import time
import shutil

def process_frames(start, end):
    for i in range(start, end):
        filename = f"{frames_directory}/{i+1:04d}.png"
        with open(filename, "rb") as i:
            basename = os.path.basename(filename)  # Extracts the file name from the path
            name, ext = os.path.splitext(basename)  # Separates the name
            digits = name[-4:]  # Extracts the last 4 characters, assuming they are always digits

            with open(os.path.join(processed_directory, f"{digits}.png"), "wb") as o:
                input = i.read()
                output = remove(input, alpha_matting=args.a, alpha_matting_foreground_threshold=args.af, alpha_matting_background_threshold=args.ab, alpha_matting_erode_size=args.ae)
                o.write(output)

# Create temporary directories
process_start = time.time()
current_directory = os.getcwd()
tmp_directory = os.path.join(current_directory, "tmp")
frames_directory = os.path.join(tmp_directory, f'frames-{process_start}')
os.makedirs(frames_directory, exist_ok=True)
processed_directory = os.path.join(tmp_directory, f'processed-{process_start}')
os.makedirs(processed_directory, exist_ok=True)

#Parse args
parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video')
parser.add_argument('input', type=str, help='Input video')
parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal")
parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold")
parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold")
parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size")
parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction')
parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing')
args = parser.parse_args()

#Extract video info
probe = ffmpeg.probe(args.input)
video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
width = int(video_stream['width'])
height = int(video_stream['height'])
whstr = str(width) + 'x' + str(height)
framerate = video_stream['avg_frame_rate']

#Extract input video frames
if not args.skip_extract:
    print("Extract input video frames...")
    stream = ffmpeg.input(args.input)
    stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")
    ffmpeg.run(stream)

#Process frames with rembg
if not args.skip_process:
    print("Process frames with rembg...")
    num_frames = len(os.listdir(frames_directory))
    num_threads = 5
    frames_per_thread = num_frames // num_threads
    threads = []
    for i in range(num_threads):
        start = i * frames_per_thread
        end = start + frames_per_thread
        if i == num_threads - 1:
            end = num_frames
        t = threading.Thread(target=process_frames, args=(start, end))
        t.start()
        threads.append(t)
    for t in threads:
        t.join()

#Output video
stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p')
stream = ffmpeg.output(stream, "output.mp4", crf=22, r=10, acodec='aac', s='360x640', vcodec='libx265')
ffmpeg.run(stream)


# Remove temporary directories
shutil.rmtree(frames_directory)
shutil.rmtree(processed_directory)

# getting the time when script ends
process_end = time.time()
duration = process_end - process_start
print("All the process has taken: {} minutes".format(duration / 60))
```
</details>

<details>
<summary>Using sessions</summary>

```
from pathlib import Path
from rembg import remove, new_session
import subprocess
import time
import argparse
import sys
import os
import ffmpeg
import pathlib
from rembg.bg import remove
import shutil
from PIL import Image

session = new_session()

# getting the time when the script started
process_start = time.time()
current_directory = os.getcwd()

# Create temporary directories
tmp_directory = os.path.join(current_directory, "tmp")
frames_directory = os.path.join(tmp_directory, f'frames-{process_start}')
os.makedirs(frames_directory, exist_ok=True)
processed_directory = os.path.join(tmp_directory, f'processed-{process_start}')
os.makedirs(processed_directory, exist_ok=True)

#Parse args
parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video')
parser.add_argument('input', type=str, help='Input video')
parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal")
parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold")
parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold")
parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size")
parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction')
parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing')
args = parser.parse_args()

#Extract video info
probe = ffmpeg.probe(args.input)
video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
width = int(video_stream['width'])
height = int(video_stream['height'])
whstr = str(width) + 'x' + str(height)
framerate = video_stream['avg_frame_rate']

#Extract input video frames
if not args.skip_extract:
    print("Extract input video frames...")
    stream = ffmpeg.input(args.input)
    stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")
    ffmpeg.run(stream)

for file in Path(frames_directory).glob('*.png'):
    print("Process frames with rembg...")
    input_path = str(file)
    output_path = os.path.join(processed_directory, f"{file.stem}.png")
    print(f"file stem {file.stem}")

    with open(input_path, 'rb') as i:
        with open(output_path, 'wb') as o:
            input_data = i.read()
            output_data = remove(input_data, session=session)
            o.write(output_data)

#Output video
stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p')
stream = ffmpeg.output(stream, "output.mp4", crf=18, b='4M', r=60, vcodec='libx265')
ffmpeg.run(stream)

# Clean temporary directories
shutil.rmtree(frames_directory)
shutil.rmtree(processed_directory)

# getting the time when script ends
process_end = time.time()

# Calculate the duration
duration = process_end - process_start

# Display the duration
print("All the process has taken: {} minutes".format(duration / 60))
```
</details>

Hope it will help :)

**Comment by z905762202** [comment]
thanks a lot
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danielgatis/rembg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danielgatis/rembg] Speed problem (Issue #389)





 
Hey @z905762202
 I've tried adding the multi-threading, multi-processing and sessions to speed up the process:
  Using Multi-Processing import os import argparse import ffmpeg import subprocess import time from multiprocessing import Pool def process_image(image_path):     # Create the output path for the processed image     processed_path = os.path.join(processed_directory, os.path.basename(image_path))     # Call the rembg command for a single image     subprocess.run(["rembg", "i", image_path, processed_path]) # getting the time when the script started process_start = time.time() # Create temporary directories current_directory = os.getcwd() tmp_directory = os.path.join(current_directory, "tmp") frames_directory = os.path.join(tmp_directory, "frames") processed_directory = os.path.join(tmp_directory, "processed") if not os.path.exists(frames_directory):     os.makedirs(frames_directory) if not os.path.exists(processed_directory):     os.makedirs(processed_directory) if __name__ == "__main__":     # Parse args     parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video')     parser.add_argument('input', type=str, help='Input video')     parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal")     parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold")     parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold")     parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size")     parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction')     parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing')     args = parser.parse_args()     if not args.skip_extract:         # Extract video info         probe = ffmpeg.probe(args.input)         video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)         width = int(video_stream['width'])         height = int(video_stream['height'])         whstr = str(width) + 'x' + str(height)         framerate = video_stream['avg_frame_rate']         # Extract input video frames         print("Extract input video frames...")         stream = ffmpeg.input(args.input)         stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")         ffmpeg.run(stream)     if not args.skip_process:         # Set the number of worker processes to use         num_workers = os.cpu_count()         # Get a list of image paths to process         image_paths = [os.path.join(frames_directory, f) for f in os.listdir(frames_directory)]         # Create a multiprocessing Pool with the specified number of workers         with Pool(num_workers) as pool:             # Call the process_image function for each image in the list             pool.map(process_image, image_paths)     # Output video     stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p')     stream = ffmpeg.output(stream, "output.mp4", crf=22, r=10, acodec='aac', s='360x640', vcodec='libx265')     ffmpeg.run(stream) # getting the time when script ends process_end = time.time() # Calculate the duration duration = process_end - process_start # Display the duration print("All the process has taken: {} minutes".format(duration / 60))    Using Multi-Threading import os import threading import argparse import ffmpeg from rembg import remove import time import shutil def process_frames(start, end):     for i in range(start, end):         filename = f"{frames_directory}/{i+1:04d}.png"         with open(filename, "rb") as i:             basename = os.path.basename(filename)  # Extracts the file name from the path             name, ext = os.path.splitext(basename)  # Separates the name             digits = name[-4:]  # Extracts the last 4 characters, assuming they are always digits             with open(os.path.join(processed_directory, f"{digits}.png"), "wb") as o:                 input = i.read()                 output = remove(input, alpha_matting=args.a, alpha_matting_foreground_threshold=args.af, alpha_matting_background_threshold=args.ab, alpha_matting_erode_size=args.ae)                 o.write(output) # Create temporary directories process_start = time.time() current_directory = os.getcwd() tmp_directory = os.path.join(current_directory, "tmp") frames_directory = os.path.join(tmp_directory, f'frames-{process_start}') os.makedirs(frames_directory, exist_ok=True) processed_directory = os.path.join(tmp_directory, f'processed-{process_start}') os.makedirs(processed_directory, exist_ok=True) #Parse args parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video') parser.add_argument('input', type=str, help='Input video') parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal") parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold") parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold") parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size") parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction') parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing') args = parser.parse_args() #Extract video info probe = ffmpeg.probe(args.input) video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None) width = int(video_stream['width']) height = int(video_stream['height']) whstr = str(width) + 'x' + str(height) framerate = video_stream['avg_frame_rate'] #Extract input video frames if not args.skip_extract:     print("Extract input video frames...")     stream = ffmpeg.input(args.input)     stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")     ffmpeg.run(stream) #Process frames with rembg if not args.skip_process:     print("Process frames with rembg...")     num_frames = len(os.listdir(frames_directory))     num_threads = 5     frames_per_thread = num_frames // num_threads     threads = []     for i in range(num_threads):         start = i * frames_per_thread         end = start + frames_per_thread         if i == num_threads - 1:             end = num_frames         t = threading.Thread(target=process_frames, args=(start, end))         t.start()         threads.append(t)     for t in threads:         t.join() #Output video stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p') stream = ffmpeg.output(stream, "output.mp4", crf=22, r=10, acodec='aac', s='360x640', vcodec='libx265') ffmpeg.run(stream) # Remove temporary directories shutil.rmtree(frames_directory) shutil.rmtree(processed_directory) # getting the time when script ends process_end = time.time() duration = process_end - process_start print("All the process has taken: {} minutes".format(duration / 60))    Using sessions from pathlib import Path from rembg import remove, new_session import subprocess import time import argparse import sys import os import ffmpeg import pathlib from rembg.bg import remove import shutil from PIL import Image session = new_session() # getting the time when the script started process_start = time.time() current_directory = os.getcwd() # Create temporary directories tmp_directory = os.path.join(current_directory, "tmp") frames_directory = os.path.join(tmp_directory, f'frames-{process_start}') os.makedirs(frames_directory, exist_ok=True) processed_directory = os.path.join(tmp_directory, f'processed-{process_start}') os.makedirs(processed_directory, exist_ok=True) #Parse args parser = argparse.ArgumentParser(description='Applies rembg to the frames of a video') parser.add_argument('input', type=str, help='Input video') parser.add_argument('-a', action="store_true", help="Turns on alpha matting during background removal") parser.add_argument('-af', type=int, default=240, help="Alpha matting foreground threshold") parser.add_argument('-ab', type=int, default=10, help="Alpha matting background threshold") parser.add_argument('-ae', type=int, default=10, help="Alpha matting erode size") parser.add_argument('--skip-extract', action="store_true", help='Skips ffmpeg frame extraction') parser.add_argument('--skip-process', action="store_true", help='Skips rembg frame processing') args = parser.parse_args() #Extract video info probe = ffmpeg.probe(args.input) video_stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None) width = int(video_stream['width']) height = int(video_stream['height']) whstr = str(width) + 'x' + str(height) framerate = video_stream['avg_frame_rate'] #Extract input video frames if not args.skip_extract:     print("Extract input video frames...")     stream = ffmpeg.input(args.input)     stream = ffmpeg.output(stream, f"{frames_directory}/%04d.png")     ffmpeg.run(stream) for file in Path(frames_directory).glob('*.png'):     print("Process frames with rembg...")     input_path = str(file)     output_path = os.path.join(processed_directory, f"{file.stem}.png")     print(f"file stem {file.stem}")     with open(input_path, 'rb') as i:         with open(output_path, 'wb') as o:             input_data = i.read()             output_data = remove(input_data, session=session)             o.write(output_data) #Output video stream = ffmpeg.input(f"{processed_directory}/%04d.png", r=framerate, f='image2', s=whstr, pix_fmt='yuv420p') stream = ffmpeg.output(stream, "output.mp4", crf=18, b='4M', r=60, vcodec='libx265') ffmpeg.run(stream) # Clean temporary directories shutil.rmtree(frames_directory) shutil.rmtree(processed_directory) # getting the time when script ends process_end = time.time() # Calculate the duration duration = process_end - process_start # Display the duration print("All the process has taken: {} minutes".format(duration / 60))   
Hope it will help :)
