### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by addohm** [danielgatis/rembg#394]
Is there a way to change the background color from black to white?

**Comment by ViennaAwards** [comment]
Find rembg library folder and edit bg.py's Image.new part!

For example, if you want to change the background to white, you can change it by editing with Image.new("RGBA", (img.size), (255,255,255))!

**Comment by rnag** [comment]
Here is a utility function I am using to call `rembg.remove` and replace with a grey-ish background. Note I am using `LIGHTGREY` background, which is defined in the `PIL` library.

```
from __future__ import annotations

import io

from rembg import remove
from PIL import Image
from PIL.Image import Image as PILImage

def replace_background(im: bytes | PILImage, post_process_mask=False) -> bytes:
    if not isinstance(im, PILImage):
        im = Image.open(io.BytesIO(im))

    im = remove(im, post_process_mask=post_process_mask)

    new_im = Image.new('RGBA', im.size, 'LIGHTGREY')
    new_im.paste(im, mask=im)

    bio = io.BytesIO()
    new_im.save(bio, format='PNG')
    im_bytes = bio.getvalue()

    return im_bytes
```

**Comment by cameronj86** [comment]
For CLI users:
`rembg i -x '{ "bgcolor": [{255,255,255,255}] }' fileName.jpg`
