### ISSUE TITLE
[FEATURE] Add support for Python 3.11

### ISSUE THREAD

**Issue by bcsamrudh** [danielgatis/rembg#398]
**Is your feature request related to a problem? Please describe.**
I recently tried installing rembg, but it did not install due to the fact that rembg does not support Python 3.11.

**Describe the solution you'd like**
Please add support for Python 3.11.

**Comment by jeet-khondker** [comment]
@bcsamrudh 
I completely agree with you

**Comment by danielgatis** [comment]
This library depends on "onnxruntime" and it only supports python 3.10 that's why the python version restriction.

**Comment by bcsamrudh** [comment]
@danielgatis Ok.
