### ISSUE TITLE
ImportError: cannot import name 'remove' from partially initialized module 'rembg'[BUG] ...

### ISSUE THREAD

**Issue by DocMors** [danielgatis/rembg#399]
simple attempt to 
`import rembg`
but also for
`from rembg import remove `
Python 3.10.6 on Ubuntu 22.04. Happening through Geany and also on the command line when starting a script with either line in it. This is new and has been working till 2-3 weeks ago.

**Comment by DocMors** [comment]
the idiot poster named his test file with the same name as the import lib...

**Comment by Chris-Mingay** [comment]
Fellow idiot signing in
