### ISSUE TITLE
[Question] Issue with images of flowers

### ISSUE THREAD

**Issue by andevit** [danielgatis/rembg#402]
Hi guys! 
I use this amazing tool and it's a wonder!

I just have this issue. Why do I get bad results if I use images like this?

Original
![_MG_5410](https://user-images.githubusercontent.com/13118572/224018124-a7a79a94-2210-44aa-ac6f-f491a3a6428f.jpeg)

Output
![_MG_5410a](https://user-images.githubusercontent.com/13118572/224018292-f5c65add-a1cb-45fc-bbd5-08e09b2c1449.png)

**Comment by Flippchen** [comment]
You can use the new "isnet-gerneral-use" model. It performs on some pictures much better:
![test](https://user-images.githubusercontent.com/91947480/228475314-e3f31155-b2b3-43bf-9170-a7e7f22009a8.png)
