### ISSUE TITLE
[BUG] Cloth Model Not Working

### ISSUE THREAD

**Issue by sushilronghe99** [danielgatis/rembg#403]
**Describe the bug**
When trying to run the app with Cloth model got following error. 
 pred = np.argmax(pred, axis=1, keepdims=True)
  File "<__array_function__ internals>", line 4, in argmax
TypeError: _argmax_dispatcher() got an unexpected keyword argument 'keepdims'

**To Reproduce**
Run the app with cloth model. 

**OS Version:**
Mac Monterey
Python 3.10 

**Rembg version:**
Latest 

**Additional context**
Is there a way to process the input using two models. I want to process the image with u2net and with a cloth model and then combine the results. Is it possible?

**Comment by nguyentuan3691** [comment]
How to specify processing by other model? sorry i am python master
