### ISSUE TITLE
[Documentation request] Standalone Library for AWS environments

### ISSUE THREAD

**Issue by rnag** [danielgatis/rembg#404]
Hi 👋

This is a truly amazing project, thanks for putting it together!

I wanted to let you know about this other project I started very recently and which I have personally tested in a serverless environment, specifically as an AWS Lambda [Container function](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html):

https://github.com/rnag/rembg-aws-lambda

It is essentially the same project, but a standalone version designed for AWS environments. It strips down some code, such as alpha matting, dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting variables such as `NUMBA_CACHE_DIR` or `U2NET_HOME` is not required anymore.

Re. any cold start issues, they should be eliminated by this variant package. I have done extensive testing before this previously, and determined that the cold start issue(s) to be primarly due to:
1) downloading the `*.onnx` files into the `/tmp` directory each time
2) import statement for `pymatting` - as this package heavily utilizes decorators such as `@njit`, which uses numba to cache function optimizations. As this saves it into `NUMBA_CACHE_DIR` which should ideally point to `/tmp` for AWS Lambda Docker images (the only writable directory on the container), this takes a lot of time on each cold start as `/tmp` directory is clean (empty) at this point.

I feel that a standalone version such as this (which comes with `u2net.onnx` model file already bundled in it) could enable other developers to more easily deploy this great solution to cloud or serverless environments. Check it out and let me what you think about it. I can also help you update the documentation if you're interested.

**Comment by rnag** [comment]
Bump!

**Comment by rishabh063** [comment]
Hey but how did you deploy it ? 

lambdas have a container size < 50 mb where as the onnx file it self is above 150mb
