### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'rembg'

### ISSUE THREAD

**Issue by yatshunlee** [danielgatis/rembg#407]
**Describe the bug**
I can't import rembg but I can use it as a command directly.

**Images**
![image](https://user-images.githubusercontent.com/69416199/225835623-8b3d9a29-1aa9-4ccc-892c-ec055157d860.png)

**OS Version:**
Windows 10

**Rembg version:**
I have "pip-installed" the latest version. But I don't see it on the pip list.

**Comment by jangop** [comment]
You appear to be using Anaconda. My best guess is that you installed rembg outside your `base` environment. Whatever shell-like thing your Windows gives you would still be able to call the installed cli, but the module will not be available to Python.

This does not appear to be a bug in rembg.

**Comment by Theroniya** [comment]
No bug. It works fine when I use the same anaconda env for pip, python and vs code.

**Comment by yatshunlee** [comment]
I instead used https://github.com/xuebinqin/U-2-Net to build the application

@BrentWilkins @Aciid
