### ISSUE TITLE
Not working install

### ISSUE THREAD

**Issue by goodwin74** [danielgatis/rembg#41]
Command **pip install rembg** print error
```
Collecting rembg
  Could not find a version that satisfies the requirement rembg (from versions: )
No matching distribution found for rembg
```
How to solve?

**Comment by shaniEnginer** [comment]
### Unable to install rembg
$ pip install rembg
Collecting rembg
  Using cached rembg-1.0.14.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:

**Comment by weihaox** [comment]
try to download the repo as .zip. 
unzip it and install by `cd rembg && python3.8 setup.py install`

**Comment by danielgatis** [comment]
try this:

```
pip --no-cache-dir install rembg==1.0.16
```
