### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by y0himba** [danielgatis/rembg#415]
**Describe the bug**
Cannot install rembg[gpu] 

```
ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg
```

**To Reproduce**

1. Open command prompt
2. Use `pip install rembg[gpu]`
3. See error:
```
ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg
```

I also tried grabbing the source code, and cloning the repo, as well as `pip install onnxruntime-gpu`.  I also used `pip install -r requirements-gpu.txt`  which returned:
```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.13.1
**Expected behavior**
```
I would expect rembg to be installed as I meet he requirements of Python 3.11.0 on Windows 11 with an nVidia 4070 Ti GPU

**Images**
Input images to reproduce.

**OS Version:**
Windows 11 22H2 22621.1413

**Rembg version:**
v2.0.31

**Additional context**
Python 3.11.0

**Comment by Flippchen** [comment]
Try it with Python 3.10. According to both the error message and the official PyPI documentation, the "rembg" package only supports Python versions up to 3.10. 
Here's the link to pypi: https://pypi.org/project/rembg/

**Comment by y0himba** [comment]
> Try it with Python 3.10. According to both the error message and the official PyPI documentation, the "rembg" package only supports Python versions up to 3.10. Here's the link to pypi: https://pypi.org/project/rembg/

That was it. Removed 3.11, installed 3.10.
