### ISSUE TITLE
[BUG] The color of clothing change

### ISSUE THREAD

**Issue by cprodhomme** [danielgatis/rembg#418]
**Describe the bug**
When i use rembg as a server with somes pictures of clothing, the color of the clothe change (less lively)

and there is a little grey border

Maybe there ara some options to do this but i don't find any documentation about this .. :/ 

**To Reproduce**

- Use rembg as a server
- Use the image below

**Images**
Before : 

![1678353670](https://user-images.githubusercontent.com/7428736/229094904-352f3fc2-ab83-4cd4-adca-6b9493413690.jpeg)

After : 

![photo_detouree](https://user-images.githubusercontent.com/7428736/229095031-bbc817b4-2dbb-4387-89f9-6933ab9b2a92.png)

**OS Version:**
Ubuntu 20

**Rembg version:**
v2.0.21

**Comment by cprodhomme** [comment]
Any ideas @Flippchen @danielgatis ?

**Comment by Flippchen** [comment]
Hey, could you please provide code on how you send the images to the server, process them and send them back?
