### ISSUE TITLE
[BUG] Definable Model Location

### ISSUE THREAD

**Issue by WASasquatch** [danielgatis/rembg#420]
**Describe the bug**
Currently the models are stored in the home directory for the user. This is counter-productive and ripe for storage loss where you don't remember where your space is being used at (especially on windows which has no easy way to stat a harddrives files by size)

**To Reproduce**
N/A

**Expected behavior**
A cache/model directory parameter to store and load models from. 

**Images**
N/A

**OS Version:**
Linux/Windows

**Rembg version:**
[v2.0.21](https://github.com/danielgatis/rembg/commit/658ab422591c341b3cb178ecae854210c0b2d000)

**Additional context**
Trying to use this as part of a larger system, and not being able to contain the models where they should go is a huge problem.

**Comment by vishaal27** [comment]
Second this!

**Comment by danielgatis** [comment]
Try to set the this env var:

https://github.com/danielgatis/rembg/blob/main/rembg/session_factory.py#L49

**Comment by FONCHIEH** [comment]
> Try to set the this env var:尝试设置以下环境变量：
> 
> `U2NET_HOME`

You just specified the model to use. What he asked was how to specify the model under a relative path or an absolute path. instead of default path
