### ISSUE TITLE
[BUG]  Issues with the u2net_cloth_seg model

### ISSUE THREAD

**Issue by danpak6** [danielgatis/rembg#424]
Impressive project! Thank you for sharing it. I am experiencing some issues with the u2net_cloth_seg model and was hoping for some assistance.

Specifically, I am getting unexpected output when running the model. Would you be able to provide some guidance or support to help me resolve this issue?

Thank you!

![source](https://user-images.githubusercontent.com/8300356/230737863-605e6762-7102-4bab-9692-bf0dce8c576c.jpg)

![cloth](https://user-images.githubusercontent.com/8300356/230737721-01832621-9089-471a-b1df-b85c6e17511c.png)

```python
import numpy as np
from PIL import Image
from rembg import remove, new_session
model_name = "u2net_cloth_seg"
session = new_session(model_name)
image = Image.open('images/source.jpg')
image = remove(image, session=session)
image.save('images/cloth.png')

**Comment by Flippchen** [comment]
Hey, do you want to cut out just the dress or the person?

**Comment by 66e61zhv** [comment]
hijacking this issue as i have a similar issue, given the example above, how do i cut out the entire dress without it being segmented as top/bottom?

**Comment by jperezr21** [comment]
I'm also having this issue 😕

**Comment by tuandev1l** [comment]
still have similar issue, how to fix that ?
