### ISSUE TITLE
Use different model like u2net_human_seg.onnx instead of u2net

### ISSUE THREAD

**Issue by imtayyabhayat** [danielgatis/rembg#429]
I'm using rembg as library with python 3.8. it works fine while remove background from objects, but i want to work specific for humans only detection and everything else should be removed. For that, i need to use a different model mentions in .md file. Can anyone help me solve this issue? it is working fine on command line when i use -m option.

**Comment by Flippchen** [comment]
I hope I can help you with this.
```python
from rembg import remove, new_session

model_name = "u2net_human_seg"
session = new_session(model_name)

image = Image.open("path/to/your/image")

image = remove(image, session=session)

image.show()

```
Possible models are:

- u2netp
- u2net_human_seg
- u2net_cloth_seg
- silueta
- isnet-general-use (only in newest Version)

Let me know if you need more help :)

**Comment by imtayyabhayat** [comment]
Yes it helps, very simple and nice approach. Thank you!

**Comment by Flippchen** [comment]
> Oh, apparently there is a `--model` CLI option that isn't listed when you perform `--help`

The `rembg i --help` command shows the right CLI option.
![image](https://user-images.githubusercontent.com/91947480/233181014-0dd6d926-0f35-4969-ad73-b88e32149a95.png)

**Comment by Flippchen** [comment]
> > I hope I can help you with this.
> > ```python
> > from rembg import remove, new_session
> > 
> > model_name = "u2net_human_seg"
> > session = new_session(model_name)
> > 
> > image = Image.open("path/to/your/image")
> > 
> > image = remove(image, session=session)
> > 
> > image.show()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Possible models are:
> > 
> > * u2netp
> > * u2net_human_seg
> > * u2net_cloth_seg
> > * silueta
> > * isnet-general-use (only in newest Version)
> > 
> > Let me know if you need more help :)
> 
> Could you add a CLI parameter for this?
> 
> (Also, is there a way to change what folder it tries to read the model files from?)

Have a look at issue #420 . I hope it fixes it for you :)
