### ISSUE TITLE
"pthread_setaffinity_np failed for thread" error

### ISSUE THREAD

**Issue by AliakbarGhayoori** [danielgatis/rembg#430]
Hi,

I face this error when I want to use the "remove" function of rembg several times. any idea of what is the problem?

![Screenshot from 2023-04-20 12-24-49](https://user-images.githubusercontent.com/24523283/233316092-00203362-53ce-4686-a4aa-3144196a73b5.png)

**Comment by Flippchen** [comment]
Did you installed onnxruntime for GPU or only CPU?

**Comment by AliakbarGhayoori** [comment]
Hi, It's only for CPU

**Comment by AliakbarGhayoori** [comment]
> Did you installed onnxruntime for GPU or only CPU?


Hi, It's only for CPU.
