### ISSUE TITLE
[BUG] "AssertionError" on startup with 2.0.33 

### ISSUE THREAD

**Issue by shakalandy** [danielgatis/rembg#434]
**Describe the bug**
After updating a rembg "server" instance from 2.0.30 to 2.0.33 it stopped working.
Downgrade to 2.0.32 - works again.

is there a new config option missing?
Thanks!

**To Reproduce**

1. Update to 2.0.33
2. start server version with "rembg s"

**Expected behavior**
Server startup works normally.

**Images**
no images used

**OS Version:**
Ubuntu 2.0.32

**Rembg version:**
v2.0.33

**Additional context**

startup error traceback:

``` 
Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rembg/commands/s_command.py", line 214, in s_command
    async def get_index(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 661, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 600, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 446, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 310, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 123, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 159, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 303, in get_dependant
    type_annotation, depends, param_field = analyze_param(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 413, in analyze_param
    assert field_info is None, (
AssertionError: Cannot specify FastAPI annotations in `Annotated` and default value together for 'model'
```

**Comment by dmitry-kotorov** [comment]
I am getting the same error with 2.0.34

rembg_1            | Traceback (most recent call last):
rembg_1            |   File "/usr/local/bin/rembg", line 8, in <module>
rembg_1            |     sys.exit(main())
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
rembg_1            |     return self.main(*args, **kwargs)
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
rembg_1            |     rv = self.invoke(ctx)
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
rembg_1            |     return _process_result(sub_ctx.command.invoke(sub_ctx))
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
rembg_1            |     return ctx.invoke(self.callback, **ctx.params)
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
rembg_1            |     return __callback(*args, **kwargs)
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/rembg/commands/s_command.py", line 212, in s_command
rembg_1            |     async def get_index(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 661, in decorator
rembg_1            |     self.add_api_route(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 600, in add_api_route
rembg_1            |     route = route_class(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 446, in __init__
rembg_1            |     self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 310, in get_dependant
rembg_1            |     sub_dependant = get_param_sub_dependant(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 123, in get_param_sub_dependant
rembg_1            |     return get_sub_dependant(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 159, in get_sub_dependant
rembg_1            |     sub_dependant = get_dependant(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 303, in get_dependant
rembg_1            |     type_annotation, depends, param_field = analyze_param(
rembg_1            |   File "/usr/local/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 413, in analyze_param
rembg_1            |     assert field_info is None, (
rembg_1            | AssertionError: Cannot specify FastAPI annotations in `Annotated` and default value together for 'model'

**Comment by danielgatis** [comment]
can you share the curl to generate this bug, please?

**Comment by dmitry-kotorov** [comment]
> 

I am not sure how to make the curl. I making a POST request from my app with a form and multipartfile in it. It is working great with rembg up to 2.0.32.

I tried to add 'model' field with model name as well. But the problem remains.

**Comment by LAGGOUNE-Walid** [comment]
Same error .

**Comment by danielgatis** [comment]
try to install the last version and try it again please
