### ISSUE TITLE
anime model isnetis

### ISSUE THREAD

**Issue by VinsiGit** [danielgatis/rembg#436]
**Additional context**
[https://github.com/SkyTNT/anime-segmentation](https://github.com/SkyTNT/anime-segmentation)
[https://huggingface.co/skytnt/anime-seg/tree/main](https://huggingface.co/skytnt/anime-seg/tree/main)
There is this anime model I would like to use but I get 'Error: Invalid value for '-m' / '--model': 'isnetis' is not one of 'isnet-general-use', 'sam', 'silueta', 'u2net', 'u2net_cloth_seg', 'u2net_human_seg', 'u2netp'.'
Can this model be added or is there a way that I can make it compatible with the software?

**Comment by danielgatis** [comment]
@VinsiGit @catboxanon thanks guys, please check the new version ;)
