### ISSUE TITLE
[BUG] The library does not use the GPU

### ISSUE THREAD

**Issue by Vv-vfx** [danielgatis/rembg#439]
The library does not use the GPU, In the task manager, the load on cuda is 0 %
I tried different versions of nvidia and pytorch.
RTX 2080 Super.

**Comment by Flippchen** [comment]
Does Pytorch detect your GPU?

**Comment by juanmarin96** [comment]
same issue here, all workload is charge on CPU, I had already installed GPU version of rembg, and my torch detec my GPU, but the  GPU keeps in 0% in my task manager. I'm using Ubuntu 22.04 on WSL2, with CUDA 12.1 and Python 3.10.6

**Comment by Vv-vfx** [comment]
> 

Yes

**Comment by Vv-vfx** [comment]
but:
t = torch.cuda.get_device_properties(0).total_memory
r = torch.cuda.memory_reserved(0)
a = torch.cuda.memory_allocated(0)
f = r-a  # free inside reserved
print(f)
>>> 0

**Comment by longmix** [comment]
I get the same echo as you.

>>> print(torch.cuda.memory_reserved(0))
0
>>> print(torch.cuda.memory_reserved('cuda:0'))
0
>>> print(torch.cuda.device_count())
1
>>> print(torch.cuda.get_device_name(0))
NVIDIA GeForce GTX 960
>>> print(torch.cuda.memory_allocated(0))
0
>>> print(torch.cuda.get_device_properties(0).total_memory)
4294836224
>>>

Is there any wrong ?

**Comment by btxtiger** [comment]
I can also not see any usage of my RTX 3070. 
Why isn't it logged anywhere if the application uses CPU or GPU ?? 
There should be a flag to force using GPU, which should fail, if the GPU was not accessible

**Comment by catscarlet** [comment]
Linux Mint 20.3 Cinnamon
5.4.0-148-generic
 i7-4790K CPU
NVIDIA Corporation GP104 [GeForce GTX 1080]

pip install onnxruntime-gpu
pip install rembg[gpu]

But still no usage on GPU

Anyway to debug?

**Comment by btxtiger** [comment]
@catscarlet I found out, if GPU is available, you can run `nvidia-smi` and see your GPU.
That still doesn't mean that the GPU is being used by rembg.

I'm currently checking the processing time to determine if GPU works.
5000px ~ 6 sec (30 sec on CPU)
2000px ~ 4.5 sec

Less than 4 sec is not possible for single file processing. Seems that processing multiple files at once (`p` mode) has some benefits

**Comment by justinjohn0306** [comment]
Try installing tensorrt and onnxruntime-gpu

**Comment by zhowzeng** [comment]
Same issue here.
I installed `rembg[gpu]` and get `onnxruntime-gpu==1.15.0`.
```python
>>> import onnxruntime as ort
>>> ort.get_available_providers()
['CPUExecutionProvider']
>>> import torch
>>> torch.cuda.is_available()
True
```
After checking [this](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html), I thought that it might be the CUDA issue (I have CUDA 11.4). So I re-installed `onnxruntime-gpu==1.12.0` and

```python
>>> import onnxruntime as ort
>>> ort.get_available_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
```

but

```python
>>> from rembg import remove, new_session
>>> session = new_session('u2net')
2023-05-31 02:09:14.632617804 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:540 CreateExecutionProviderInstance] Failed to create TensorrtExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements to ensure all dependencies are met.
2023-05-31 02:09:14.632651948 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:566 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
>>> session.inner_session.get_providers()
['CPUExecutionProvider']
```

**Comment by lifecoder1988** [comment]
have same issue in aliyun cloud fc gpu docker instance  (GPU:Tesla T40)

**Comment by zharvz** [comment]
Same issue here

**Comment by gnulife** [comment]
我也是同样的问题

**Comment by dfsj66011** [comment]
https://stackoverflow.com/questions/75267445/why-does-onnxruntime-fail-to-create-cudaexecutionprovider-in-linuxubuntu-20/75267493#75267493
solved my problem.

**Comment by MuQQQQQ** [comment]
Make sure you have installed `libcudnn.so`.

It can be easily installed by `conda install cudnn=8.9.2 `

**Comment by leo-smi** [comment]
any idea for intel gpu?
