### ISSUE TITLE
[BUG] better quality result needed

### ISSUE THREAD

**Issue by TheSnowGuru** [danielgatis/rembg#440]
**bug**
An image i tried got a really bad results, and I wanted to ask how i can get a better result?
https://prnt.sc/2bu3MI5215js
got this result: https://prnt.sc/4wJtvTHQkIHv

**To Reproduce**
```
with open(f"{interaction.id}.jpg", 'rb') as i:
            with open(f"{interaction.id}_rmbg.jpg", 'wb') as o:
                input = i.read()
                output = remove(input)
                o.write(output)
                ```

**Expected behavior**
whereas , when I checked a 3rd party app like remove. bg they got a better result.
https://prnt.sc/FdWLBRhw4lwd

**Images**
[Input images to reproduce.](https://prnt.sc/2bu3MI5215js)

**OS Version:**
linux

**Rembg version:**
v2.0.30

**Additional context**
  is it possible to use a different model on this call? if yes, then how? thx

**Comment by Flippchen** [comment]
Hey,

have a look at #429. It is possible that not all of the models there are in your rembg version. You can also play along with several input parameters which you can find in the USAGE.md file.
