### ISSUE TITLE
[BUG] could not to remove the background of a ring in the middle.

### ISSUE THREAD

**Issue by pppica** [danielgatis/rembg#445]
[BUG] could not to remove the background of a ring in the middle.

see my input: https://prnt.sc/V6Au1ROYSAi3
and i got: https://prnt.sc/PloWY8c_aBNb

**Rembg version:**
v2.0.36

is this a bug or not?， thx

**Comment by Flippchen** [comment]
Hey, this is not a bug.


You can try other models:
```python
image_path = "image.png"
image = Image.open(image_path)

# Remove background
session = new_session("isnet-general-use")
cutout = remove(image, session=session)
cutout.save("cutout.png")
```

**Comment by avtpas** [comment]
> Hey, this is not a bug.
> 
> You can try other models:
> 
> ```python
> image_path = "image.png"
> image = Image.open(image_path)
> 
> # Remove background
> session = new_session("isnet-general-use")
> cutout = remove(image, session=session)
> cutout.save("cutout.png")
> ```

Hi.
i'v downloaded the isnet-general-use.onnx file into ~/.u2net ,why it's still downloading it again when i start a request? 

it says "Updating data from 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-general-use.onnx' to file '/Users/avtpas/.u2net/isnet-general-use.onnx'." ， but i had it already !

thx
