### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath' 

### ISSUE THREAD

**Issue by Tanikavision** [danielgatis/rembg#449]
**Describe the bug**
 Original error was: No module named 'numpy.core._multiarray_umath' 
error in numpy core in while deploying rembg using flask 
**To Reproduce**

1.  Use ubuntu 20.04 install python3.10 
2. Deploy your application using Flask

**Python**
python3.10 

**OS Version:**
Linux 

**Rembg version:**
v2.0.37

**Additional context**

**Comment by Flippchen** [comment]
Hey,

which version of numpy are you using?

**Comment by Tanikavision** [comment]
numpy version : 1.24.3  

thanks.

**Comment by Flippchen** [comment]
Could you please downgrade numpy to an older version with pip?

**Comment by Tanikavision** [comment]
downgraded numpy to 1.23.5, still same error pops up related to  'numpy.core._multiarray_umath'

thanks @Flippchen
