### ISSUE TITLE
Upgrade torchvision version 

### ISSUE THREAD

**Issue by ibrahimnsu15** [danielgatis/rembg#45]
I got an error for installing rembg

ERROR: Could not find a version that satisfies the requirement torchvision==0.8.1 (from rembg) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0)
ERROR: No matching distribution found for torchvision==0.8.1 (from rembg)

**Comment by Naman-Monga** [comment]
> 
> 
> I got an error for installing rembg
> 
> ERROR: Could not find a version that satisfies the requirement torchvision==0.8.1 (from rembg) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0)
> ERROR: No matching distribution found for torchvision==0.8.1 (from rembg)

Even I am having the same issue, seems like the torchvision library has not been updated/remove from pypi.

**Comment by umairsajid0017** [comment]
Same issue

**Comment by UneChipo** [comment]
Same issue here

**Comment by ibrahimnsu15** [comment]
I tried in ubuntu 20.04 and Mac OS. It successfully installed. No error Detected. 
That means show error in only windows OS.

**Comment by qfwc258** [comment]
same issue

**Comment by chrlee** [comment]
same issue

**Comment by jwgo** [comment]
```sh
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```
Torch and Torchvision versions need to be paired.
Try this. (you can delete torchaudio option.)

**Comment by jinwyp** [comment]
try this：

pip uninstall torch torchvision
pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
