### ISSUE TITLE
[BUG] Could not find a version that satisfies the requirement rembg while installing using pip in python 3.11.3 version

### ISSUE THREAD

**Issue by arasad28** [danielgatis/rembg#450]
**Describe the bug**
While installing the rembg using pip got this error
ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Requires-Python >3.7, <3.11; 2.0.33 Requires-Python >3.7, <3.11; 2.0.34 Requires-Python >3.7, <3.11; 2.0.35 Requires-Python >3.7, <3.11; 2.0.36 Requires-Python >3.7, <3.11; 2.0.37 Requires-Python >3.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg

**To Reproduce**

1. Use python latest version
2. install rembg using pip latest version

**OS Version:**
Linux

**Rembg version:**
v2.0.37

**Additional context**

**Comment by atyeoqapnipd** [comment]
Same problem, Requirements

python: >3.7, <3.11

It should be python: >2.7, <3.11

**Comment by ThePyceIsRight** [comment]
I am having the same issue.

`
ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Re
quires-Python >3.7, <3.11; 2.0.33 Requires-Python >3.7, <3.11; 2.0.34 Requires-Python >3.7, <3.11; 2.0.35 Requires-Python >3.7, <3.11; 2.0.36 Requires-Python >3.7, <3.11; 2.0.37 Requires-Python >3.7, <3.11; 2.0.38 Requires-Python >3
.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg
`

**Comment by bernardito-luis** [comment]
It's not a bug, rembg simply doesn't have support for 3.11 yet.
Another questions are why? and how can we get it?
