### ISSUE TITLE
[BUG] background color is not attached with image.

### ISSUE THREAD

**Issue by ARajgor** [danielgatis/rembg#452]
**Describe the bug**
Here I provide an image in png format. It perfectly removes the background. but the problem I'm facing is that it didn't add up the white / any color in the background.

**Expected behavior**
As I understand from the documentation it should replace the background.

**Images**
![image](https://github.com/danielgatis/rembg/assets/76404080/52dbecf6-9fbf-4de3-8585-7525ab575d1a)

**OS Version:**
Windows 11 Python 3.9.8

**Rembg version:**
v2.0.37

**Comment by ARajgor** [comment]
So after some research, I found the solution but there is a mistake in the documentation it is not up-to-date with the latest version. Maybe you should add this context to the [USAGE.md](https://github.com/danielgatis/rembg/blob/main/USAGE.md#replacing-the-background-color)

``` bgcolor: Optional[Tuple[int, int, int, int]] ```

so it is set as RGBA by default. RGB should be from 0 to 255 but here A for alpha is also from 0 to 255 not 0 or 1 like we do in another language like CSS.

Here I attached the screenshot of what I want to say......
![image](https://github.com/danielgatis/rembg/assets/76404080/ad51b0eb-4e8c-4bc6-a2bc-de331dd6869f)

**Comment by tranzmatt** [comment]
I had to do something similar with trying to use it for a canny operation.  I had to force the bgcolor to 255,255,255,1 or else I could see the background in an image gradient and the edges would appear in my cv2 Canny

**Comment by ARajgor** [comment]
Can you share some examples like code or image?
