### ISSUE TITLE
It can't seem to load the new models

### ISSUE THREAD

**Issue by justinjohn0306** [danielgatis/rembg#457]
tried running this cmd: 
``rembg p input 06_output_sam -m sam --post-process-mask``
but since the model isn't in the list, it can't seem to load it as shown in the ss below

![ss](https://github.com/danielgatis/rembg/assets/34035011/999c17d6-0609-435c-ae16-24040e568b0b)

**Comment by aziliak** [comment]
Justin, unrelated to this, but have you tried setting up Wav2Lip on Google Compute?  Trying to automate a process but I'm getting stuck.

**Comment by danielgatis** [comment]
please just try to update your rembg version

**Comment by khadija23** [comment]
Hi  how can I use my own SAM model
