### ISSUE TITLE
Output Error Regarding Sam Model

### ISSUE THREAD

**Issue by Dipankar1997161** [danielgatis/rembg#459]
hello @danielgatis ,
### Thank you so much for the work.

Original image:
![000000](https://github.com/danielgatis/rembg/assets/85514219/82023347-5bd1-4496-85fe-981af16b5386)
My image has 1 subject, and I want to segment the subject out.
x = 221, y = 111, w = 523, h = 529 -- bbox coordinates
Image size = 1000×1002

I took 3 specific points on the images (subject body):
[500, 192], [494, 288], [499, 372] - input points
So when I used the x-y format: I got the following mask output
![x-y](https://github.com/danielgatis/rembg/assets/85514219/92dfa40d-4d30-47b6-a57a-1803177bad9e)

when using the y-x system (as per what is mentioned here) 
![000011](https://github.com/danielgatis/rembg/assets/85514219/629a4c6d-ad2a-4604-9528-99109572dd3b)

why is this the case for y-x system, I am getting such an output.

The final segmentation in both cases is weird: the masks and the image appear to be larger than the image.
![x-y_new](https://github.com/danielgatis/rembg/assets/85514219/dc914620-4ca9-490a-b5e4-c02a13cdc8ee)
![y-x_new](https://github.com/danielgatis/rembg/assets/85514219/f901286f-460e-4506-ac65-35819aaba8a5)

## here is my code:
from rembg import new_session, remove
from PIL import Image
import numpy as np

box0 = 221
box1 = 111
box2 = 523
box3 = 529

input_path = "/home/ndip/humannerf/dataset/wild/monocular/images/000000.png"
output_path = "/mnt/data/ndip/h36m_s1_Directions/x-y__new.png"
image = Image.open(input_path)
model = "sam"

#box = np.array([[192, 500], [288, 494]])
box = np.array([[500, 192], [494, 288], [499, 372]])
boxnew = np.array([[553,230], [204,796], [206, 248], [310,500]])
input_labels = np.array([0, 0, 0, 1])
session = new_session(model)
output = remove(image, session = session,input_points = boxnew, input_labels = input_labels, post_process_mask=True, only_mask = True)
output.save(output_path)

Could you tell me. Thank you

**Comment by zeusftk** [comment]
the sam mask size wrong，but when can fix it？？

**Comment by Dipankar1997161** [comment]
> the sam mask size wrong，but when can fix it？？

Try setting the pose_process_mask to False and see. I didn't try it, just a suggestion. Or maybe check the mask size in the sam.py and try to set it to original image size

**Comment by zeusftk** [comment]
Why doesn't the author appear? When can we update SAM and fix bugs

**Comment by Dipankar1997161** [comment]
> Why doesn't the author appear? When can we update SAM and fix bugs

This is not a SAM repository anyways. 
What is your requirement, maybe I can help you with that

**Comment by zeusftk** [comment]
fix the sam rembg，
the inference mask can't alignment the source image，just same problem as yours

**Comment by amrithy** [comment]
Hi - I too am facing the same issue where the SAM model isn't working right. 
The mask is not aligned and hence the output is incorrect. 

Any suggestions on how we could fix it ?

**Comment by Dipankar1997161** [comment]
> Hi - I too am facing the same issue where the SAM model isn't working right. The mask is not aligned and hence the output is incorrect.
> 
> Any suggestions on how we could fix it ?

Hey. My suggestion would be to not use rembg with SAM. Rather you can use SAM alone and get the masks out using the bounding box method. I used that to get the output. Hope it helps

**Comment by Robert-van-Barlingen** [comment]
I am experiencing the same issue. Even though using the SAM model directly, as dipankar suggested is a possible fix, it is simple more convenient to use rembg.

**Comment by JanisPlayer** [comment]
I added that to Extra parameters as JSON.
{ "input_labels": [ 1, 2, 3 ], "input_points": [ [ 500, 192 ], [ 494, 288 ], [ 499, 372 ] ] }
The result is even worse than yours:
![image](https://github.com/danielgatis/rembg/assets/54918417/3759c955-c236-4b1e-95f2-749664cad3e6)

I'm currently building a simple [web version](https://heldendesbildschirms.de/removebg/) for the tool, running it in Docker, and using the forwarded API.
Do you know if the issue lies with the program, or have I misunderstood the API?
As far as I understand, for a rectangle, I should do the following:
{ "input_labels": [ 1, 1 ], "input_points": [ [ 0, 0], [ 500, 500] ] }
For points, I should only count input_labels.
You can find the source code in this [file](https://github.com/danielgatis/rembg/blob/main/rembg/sessions/sam.py), but I'm not getting much clarity from it. The `apply_coords` function looks interesting.

**Comment by marcin1990** [comment]
Same issue here, rembg version 2.0.50.

![obraz](https://github.com/danielgatis/rembg/assets/21237382/7a747e5e-bd73-45db-a29a-a95046715047)

**Comment by Angtian** [comment]
Has a similar issue, I believe there is a bug here:
[https://github.com/danielgatis/rembg/blob/7c1b3c4cb3d59bd8cca44a0cf0e1608e50ad4b44/rembg/sessions/sam.py#L113C47-L113C60](url)
`img.size[::1]`  should be  `img.size[::-1]`
