### ISSUE TITLE
Get all Text and people

### ISSUE THREAD

**Issue by VyVu** [danielgatis/rembg#46]
I have this picture in this link. How can i get all text and people ? 
[https://res.cloudinary.com/teepublic/image/private/s--RvwfU0hK--/t_Preview/b_rgb:191919,c_limit,f_auto,h_630,q_90,w_630/v1598124169/production/designs/13316062_0.jpg](url)

Current i only get people.

Please suggestion
thanks

**Comment by danielgatis** [comment]
You need to train your own models.

https://github.com/danielgatis/rembg/issues/58
