### ISSUE TITLE
ValueError: input_labels is required

### ISSUE THREAD

**Issue by nhuhoan** [danielgatis/rembg#465]
Hi,

I tried to use Rembg with the sam model on Ubuntu, but I always receive this bug : ValueError: input_labels is required.

Rembg version is: 2.0.43

Please let me know how to fix this issue. 

Thanks

**Comment by Mxs2019** [comment]
You need to pass in the input_labels like so
```
rembg i -m sam -x '{"input_labels": [1], "input_points": [[300,300]]}' max.jpeg max-cut.jpeg
```

The issue I'm running into is that I don't want to use the CLI. Do you know how to run a custom model from python?

**Comment by cajdotxa71262** [comment]
same issue on windows11
the command is correct

**Comment by Aashrut** [comment]
Have a look at this USAGE.md file for running rembg in Python.

https://github.com/danielgatis/rembg/blob/main/USAGE.md#using-input-points
