### ISSUE TITLE
[Question] ffmpy

### ISSUE THREAD

**Issue by WASasquatch** [danielgatis/rembg#470]
Why are you requiring a FFMPEG package for rembg? What is this for? Additionally, you should think about using `opencv-python-headless[ffmpeg]` if it's truly required. ffmpy won't install on windows without modifying the install, or using a fixed fork (Like one I did: https://github.com/WASasquatch/ffmpy)

**Comment by danielgatis** [comment]
hello @WASasquatch,
Could you please show me the code where this dependency is?
