### ISSUE TITLE
[BUG] Docker new image tag is failing

### ISSUE THREAD

**Issue by ahelmy** [danielgatis/rembg#472]
**Describe the bug**
When pull latest tag its failing with this error:
```
Missing dependency: 'aiohttp'
Please, install rembg with the cli feature: pip install rembg[cli]
```

**To Reproduce**
Just pull Docker image.

**Rembg version:**
latest

**Comment by ahelmy** [comment]
@danielgatis

**Comment by danielgatis** [comment]
try now please ;)

**Comment by ahelmy** [comment]
Thank you, working

**Comment by chrislytras** [comment]
Not solved for me. Getting it in colab. After manually installing aiohttp it asks for other packages, without end. Are the dependencies broken?
