### ISSUE TITLE
[BUG] I cannot use my owned onnx.

### ISSUE THREAD

**Issue by panpengfei21** [danielgatis/rembg#473]
rembg version
```
rembg --version
rembg, version 2.0.46
```

I use rembg like this:
```
rembg i -m model /input/xxx.jpg /output/xxx.png
```

I encounter issue:
```
Invalid value for '-m' / '--model': 'model' is not one of 'isnet-anime', 'isnet-general-use', 'sam', 'silueta', 'u2net', 'u2net_cloth_seg', 'u2net_human_seg', 'u2netp'.
```

How can I use My owned onnx?

**Comment by panpengfei21** [comment]
I update rembg to 2.0.47, but It is not work.

rembg --version
rembg, version 2.0.47

```
rembg i -m u2net_custom -x '{"model_path": "~/.u2net/model.onnx"}' /path/to/input.jpg /path/to/output.png
```

show me
```
 Invalid value for '-m' / '--model': 'u2net_custom' is not one of 'isnet-anime', 'isnet-general-use', 'sam', 'silueta', 'u2net', 'u2net_cloth_seg', 'u2net_human_seg', 'u2netp'.
```

```
rembg i -m model /input/xxx.jpg /output/xxx.png
```
show me
```
Invalid value for '-m' / '--model': 'model' is not one of 'isnet-anime', 'isnet-general-use', 'sam', 'silueta', 'u2net', 'u2net_cloth_seg', 'u2net_human_seg', 'u2netp'.
```

how to use it?

**Comment by danielgatis** [comment]
It is because I did not publish a new version to pypi. I will do it soon.

**Comment by 0xm1kr** [comment]
Hey @danielgatis any update on a new publish to pypi? Would love to use `isnet-anime` from the cli.

**Comment by danielgatis** [comment]
> Hey @danielgatis any update on a new publish to pypi? Would love to use `isnet-anime` from the cli.

already published just try it

**Comment by 0xm1kr** [comment]
Okay I installed and tried but it complained about not having an `isnet-anime` model. I'll make sure I'm on the latest version.
