### ISSUE TITLE
Allow to configure path to the model instead of downloading it

### ISSUE THREAD

**Issue by kwkr** [danielgatis/rembg#48]
How about allowing to rea a pre-downloaded model from disk using some ENV variable that could be configured? I just set up an AWS Lambda using docker image and had to manually update the code to use model from disk because I had some issues with the downloaded models (AWS Lambda has some specific runtime requirements which made it harder to configure with caching option.). What do you think about this use case?

**Comment by danielgatis** [comment]
nice feature! PR are welcome.

**Comment by danielgatis** [comment]
take a look:
https://github.com/danielgatis/rembg/blob/master/src/rembg/u2net/detect.py#L75
