### ISSUE TITLE
[BUG] Error when installing in termux.

### ISSUE THREAD

**Issue by nl255** [danielgatis/rembg#480]
**Describe the bug**
I am unable to install rembg in Termux, when I try it gives an error about conflicting dependencies and that it depends on onnxruntime despite just using "pip install rembg" or "pip install rembg[cli]".

**To Reproduce**

Open termux.
Install python if not installed (pkg install python)
Try to install rembg with "pip install rembg"

**Expected behavior**

Rembg should install the CPU only version normally.

**Images**

**OS Version:**
Android 12/Termux with all packages updated.

**Rembg version:**
v2.0.41 - v2.0.41

**Additional context**

Perhaps if nothing else would it be possible to add a [cpu] option to the install to force a cpu only version, such as "pip install rembg[cpu,cli] for platforms that don't have onnxruntime?

**Comment by romanovj** [comment]
use venv or pipenv

**Comment by Ammar-Husain** [comment]
I am facing the same proplem, Did you fix it ?, If yes then how

**Comment by andoalon** [comment]
Same issue here. Is this issue supposed to be fixed? Or is it intended to be fixed in the future?
