### ISSUE TITLE
the removal doesn't recognize car correctly

### ISSUE THREAD

**Issue by allentofight** [danielgatis/rembg#490]
I upload a car like the following:

![fetch](https://github.com/danielgatis/rembg/assets/1235483/dab1c719-6881-4a6e-9440-29168a56608e)

when I use rembg api to remove it, it loses the right wheel, like the following:
![image](https://github.com/danielgatis/rembg/assets/1235483/e96ba7ef-f13e-4127-8302-77e2bc8e1a95)

but when I use the photoroom, it recognize the right wheel, and works well
![image](https://github.com/danielgatis/rembg/assets/1235483/acee6433-637a-4568-8554-a1b28232b1ca)

so maybe you should improve it to make it work better

**Comment by dipaninside** [comment]
I have same question. How to get the same result as PhotoRoom API?? Please
