### ISSUE TITLE
[BUG] 2.0.47 version and higher adds background to PNG image

### ISSUE THREAD

**Issue by itlatostadora** [danielgatis/rembg#491]
**Describe the bug**
Since I updated the library to version > 2.0.46 the behavior of some images when I remove the background is not as expected. 
It works with 2.0.46 version but not with higher version

**To Reproduce**
I've created an example to reproduce behaviour:

```
import os
import io
from PIL import Image

def test_rembg():
    output_path = 'out.png'  # Path to the output file
    input_image_path = 'input.png'  # Path to the default input image

    with open(input_image_path, 'rb') as f:
        input_image_bytes = f.read()

    result = remove(input_image_bytes)

    img = Image.open(io.BytesIO(result)).convert("RGBA")
    img.save(output_path)
```

**Expected behavior**

The problem is when the input is a png image (with transparency) and I apply the remove method, it suprisingly adds part of a background to the image (which didn't exist in the input image). I use the default model (u2net). What we expected is that the output image would be the same as the input image.

**Images**

**Input**
![arale](https://github.com/danielgatis/rembg/assets/23118282/ed0bd175-60f2-4ebd-aeda-558fea1b0424)

**Output**
![out](https://github.com/danielgatis/rembg/assets/23118282/3f9555e8-ee72-4cbd-adc3-498cd180606b)

**OS Version:**
Debian GNU/Linux 11 (bullseye)

**Python Version:**
3.10.11

**Rembg version:**
v2.0.47 or higher

**Additional context**
When i run same script with 2.0.46 version or lower, it works as expected. So I don't know what I'm doing wrong here?

**Comment by danielgatis** [comment]
maybe related to this:
https://github.com/danielgatis/rembg/issues/474
