### ISSUE TITLE
[BUG] Use the INT32 model

### ISSUE THREAD

**Issue by ThomasVercetti** [danielgatis/rembg#496]
**Describe the bug**
When I'm trying to use the rembg in python code, it shows me the following messages:

`Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64.`

as I'm tring to convert the INT64 model(u2net.onnx) to INT32 and put it in the .u2net folders, it starts with downloading the u2net.onnx and cover my converted model.

**Comment by chaoliu18** [comment]
please set MODEL_CHECKSUM_DISABLED=TRUE
