### ISSUE TITLE
[FEATURE] ...Cache Download of Model

### ISSUE THREAD

**Issue by djj0s3** [danielgatis/rembg#499]
First, amazing library; thank you! One challenge I'm having useing it as a library is that each run it re-downloads the latest model. I'd love to pass an argument to use a cached version vs downloading every time which would speed things up. I'd expect it to work something like this: check local folder for model file, if not there download, if there use cached version. Bonus points if I could provide the version number of the model to fetch.

**Comment by danielgatis** [comment]
The model is downloaded just once the first time you run. After that, the model is saved in your home directory.
