### ISSUE TITLE
[GPU] not clear how to use GPU

### ISSUE THREAD

**Issue by guiodic** [danielgatis/rembg#508]
First of all: great work!

I installed rembg with: 

`pipx rembg[gpu,cli]`

following the readme.

Then tried with some images, but it seems to work in CPU. top says 300% use of cpu white intel-gpu-top says 0%

Should I install some other component?

**Comment by BenThurber** [comment]
Unfortunately the library relies on CUDA hardware acceleration which is only available on NVIDIA GPUs (see "GPU Support" in the readme), but intel-gpu-top suggests that you are using an Intel GPU?

Otherwise if using NVIDIA, it could be related to Issue #439.
