### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by datalot-369** [danielgatis/rembg#513]
**Describe the bug**
If I run rembg with the sam model, I got a crash.

**To Reproduce**

Single lined example: `time /home/datalot/.local/bin/rembg i -m  /home/datalot/Pictures/me/IMG-20201214-WA0011.jpg ~/Desktop/IMG-20201214-WA0011.jpg`

**Expected behavior**

I expect it to work as if I'm not changing anything.

**Images**
Input images to reproduce.

**OS Version:**
MX Linux 23 (Debian 12 Bookworm)

**Rembg version:**
v2.0.50

**Additional context**
Here's my prompt:

```bash
datalot@mx:~
$ time /home/datalot/.local/bin/rembg i -m sam /home/datalot/Pictures/me/IMG-20201214-WA0011.jpg ~/Desktop/IMG-20201214-WA0011.jpg
Traceback (most recent call last):
  File "/home/datalot/.local/bin/rembg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/datalot/.local/lib/python3.11/site-packages/rembg/cli.py", line 33, in main
    _main()  # type: ignore
    ^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalot/.local/lib/python3.11/site-packages/rembg/commands/i_command.py", line 93, in i_command
    output.write(remove(input.read(), session=new_session(model, **kwargs), **kwargs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalot/.local/lib/python3.11/site-packages/rembg/bg.py", line 164, in remove
    masks = session.predict(img, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datalot/.local/lib/python3.11/site-packages/rembg/sessions/sam.py", line 96, in predict
    raise ValueError("input_labels is required")
ValueError: input_labels is required

real	0m5.685s
user	0m4.957s
sys	0m0.810s
```

Also, when installing (following [this](https://opensource.com/article/23/4/image-editing-linux-python) tutorial) I encountered those errors (I saved the screenshot because I expected something to be broken)

From `python3 -m pip install rembg --break-system-packages`
![2023-09-04_23-44](https://github.com/danielgatis/rembg/assets/21994415/6b254b05-5307-41cd-82c3-acf530189c7f)

Then I realised I can't use the CLI so:

from `python3 -m pip install rembg[cli] --break-system-packages`
![2023-09-04_23-55](https://github.com/danielgatis/rembg/assets/21994415/fad73a75-67dc-4d00-a362-24f9973c7ab2)

**Comment by datalot-369** [comment]
[Thanks to bard](https://g.co/bard/share/c3a64e6c474d), I just realized that using the  `-x '{"input_labels": [1], "input_points": [[100,100]]}' ` argument (shown in the README ) produces no error, but completely useless images:

Original / No model / sam
![image](https://github.com/danielgatis/rembg/assets/21994415/209c7bc4-b54e-443a-941a-bcea54a4b80c)

**Comment by marcin1990** [comment]
Same issue: https://github.com/danielgatis/rembg/issues/459
