### ISSUE TITLE
Not working on windows server

### ISSUE THREAD

**Issue by PrashantD04** [danielgatis/rembg#514]
i created a python api to remove background from the image, worked well on my local system, but when i hosted on windows server it is giving me this error
[WinError 5] Access is denied: 'C:\\\\Windows\\\\system32\\\\config\\\\systemprofile\\\\.u2net' | Pooch could not create data cache folder 'C:\\Windows\\system32\\config\\systemprofile\\.u2net'. Will not be able to download data files."

Please help me with this, i have also give full permission to the folder where the python file is kept, i am using Python 3.9

**Comment by joseereyes** [comment]
Hi @PrashantD04  i could help you with this, let me know if you solved it and we can close this ticket.
