### ISSUE TITLE
keyword argument 'progressbar'?

### ISSUE THREAD

**Issue by Jiang-Lei-CN** [danielgatis/rembg#519]
**Describe the bug**
 File "D:\Python\Python310\Lib\site-packages\rembg\sessions\u2net.py", line 37, in download_models
    pooch.retrieve(
TypeError: retrieve() got an unexpected keyword argument 'progressbar'

**OS Version:**
windows10

**Rembg version:**
v2.0.50
Why? Isn't the key argument 'progressbar' in retrieve()   set  True?

**Comment by idler921** [comment]
Update pooch to 1.7.0 should solve.

Ref: https://www.fatiando.org/pooch/latest/api/generated/pooch.retrieve.html#pooch.retrieve

**Comment by akshatsingh22** [comment]
Navigate to this location - D:\Python\Python310\Lib\site-packages\rembg\sessions then open u2net.py and remove that argument progressbar=True.

That will atleast not throw the error and get you sorted.
