### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443)

### ISSUE THREAD

**Issue by hallywang** [danielgatis/rembg#52]
Traceback (most recent call last):
  File "/Users/apple/.pyenv/versions/3.8.6/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rembg/cmd/cli.py", line 122, in main
    remove(
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rembg/bg.py", line 87, in remove
    model = get_model(model_name)
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rembg/bg.py", line 76, in get_model
    return detect.load_model(model_name="u2net")
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rembg/u2net/detect.py", line 83, in load_model
    download_file_from_google_drive(
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/rembg/u2net/detect.py", line 28, in download_file_from_google_drive
    response = session.get(URL, params={"id": id}, stream=True)
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/apple/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x136a4b460>: Failed to establish a new connection: [Errno 60] Operation timed out'))

**Comment by gitstudy007** [comment]
I had the same problem

**Comment by anlondon** [comment]
I only know that when a crawler encounters such a problem, you can add [verify = False] after the request, but I don’t know how to do it here

**Comment by dataorz** [comment]
if you can not access google, please down from baiduyun:
url ：https://pan.baidu.com/s/1IJOZiELPL9KJ8andi9fpyA，code：lgug

copy to folder ~/.u2net

**Comment by danielgatis** [comment]
Download the models:

https://drive.google.com/file/d/1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ/view?usp=sharing (u2net.pth)
https://drive.google.com/file/d/1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy/view?usp=sharing (u2netp.pth)

and copy to folder ~/.u2net

```
~/.u2net
     |-- u2net.pth
     |-- u2netp.pth
```

**Comment by anlondon** [comment]
oh～thanks


 
---Original---

**Comment by guzuomuse** [comment]
@danielgatis @dataorz 
after files downloaded where to put on windows ? how about create the "u2net" folder. i have create the new "u2net" folder in the root of project. but it does'nt work.
thanks.

**Comment by guzuomuse** [comment]
@danielgatis @dataorz 
how about create folder on windows?  i have create a new folder named ".u2net" and put the two files into it. but it still shows the same error.

**Comment by danielgatis** [comment]
you need to put it in your home folder.
In linux is /home/username
In mac is /Users/username
In windows ??? (I don't know, I don't use windows)

**Comment by anlondon** [comment]
Haha, I also encountered this problem before.
windows:&nbsp; C:\Users\your_user_name\.u2net\
哈哈，我之前也遇到了这个问题，windows你需要放到 C:\Users\用户名\.u2net\




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "danielgatis/rembg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 晚上9:07
收件人:&nbsp;"danielgatis/rembg"<rembg@noreply.github.com&gt;;
抄送:&nbsp;"机械师尼尔"<anlondon@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [danielgatis/rembg] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443) (#52)





 
@danielgatis @dataorz
 after files downloaded where to put on windows ? how about create the "u2net" folder. i have create the new "u2net" folder in the root of project. but it does'nt work.
 thanks.

**Comment by yuanyanhui** [comment]
> if you can not access google, please download from baiduyun:
> url ：[https://pan.baidu.com/s/1IJOZiELPL9KJ8andi9fpyA，code：lgug](https://pan.baidu.com/s/1IJOZiELPL9KJ8andi9fpyA%EF%BC%8Ccode%EF%BC%9Algug)
> 
> copy to folder ~/.u2net

invalid code

**Comment by anlondon** [comment]
感谢，我已解决😄
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "danielgatis/rembg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 上午6:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [danielgatis/rembg] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443) (#52)





  
if you can not access google, please download from baiduyun:
 url ：https://pan.baidu.com/s/1IJOZiELPL9KJ8andi9fpyA，code：lgug
 
copy to folder ~/.u2net
  
invalid code

**Comment by firesh** [comment]
share on baiduyun
https://pan.baidu.com/s/1OjAw-SmGmUX5W2CVuRxSLQ
a2rn

**Comment by zhliuworks** [comment]
> Download the models:
> 
> https://drive.google.com/file/d/1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ/view?usp=sharing (u2net.pth) https://drive.google.com/file/d/1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy/view?usp=sharing (u2netp.pth)
> 
> and copy to folder ~/.u2net
> 
> ```
> . ~/.u2net
> |-- u2net.pth
> |-- u2netp.pth
> ```

I've done what you said, but I still get this error:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f709ae2fc70>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by zhliuworks** [comment]
OK, I've found the solution. I should download these ONNX files instead, after reading the [rembg/detect.py](https://github.com/danielgatis/rembg/blob/main/rembg/detect.py#L14)

u2net:  https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab
u2netp:  https://drive.google.com/uc?id=1tNuFmLv0TSNDjYIkjEdeH1IWKQdUA4HR
u2net_human_seg:  https://drive.google.com/uc?id=1ZfqwVxu-1XWC1xU1GHIP-FM_Knd_AX5j

**Comment by constantine008** [comment]
> a2rn

and
