### ISSUE TITLE
Custom IS-NET model

### ISSUE THREAD

**Issue by TatianaSnauwaert** [danielgatis/rembg#525]
Hi Daniel,

Great work, very useful repo, thanks for that!
Are you planning on adding a possibility to use a custom IS-NET model any time soon?

Thanks in advance!
Best regards,
Tatiana

**Comment by danielgatis** [comment]
try this:

```
rembg i -m u2net_custom -x '{"model_path": "~/.u2net/u2net.onnx"}' path/to/input.png path/to/output.png
```

**Comment by TatianaSnauwaert** [comment]
Thanks for the advice, appreciate it! 
I tried but keep getting this error:
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 2 Got: 320 Expected: 1024
 index: 3 Got: 320 Expected: 1024
 Please fix either the inputs or the model.
 
 I changed the normalization parameters in the predict method in the U2netCustomSession class to 1024 but getting the same error again...Input images are 1024*1024 px already. Any idea what might be the problem here?
 
 Thanks in advance!

**Comment by TatianaSnauwaert** [comment]
There was an issue in the way I exported the model, I fix it and now it runs but the result is unexpected...
![0a010abc22a7437f8267520a76cc3b54 (1)](https://github.com/danielgatis/rembg/assets/63235607/efcd66b6-9e53-46e3-8a06-8a3dbd299b1e)
Have you seen this issue before? Any ideas what could be the problem here?
Thanks in advance!
