### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by kaanduraa** [danielgatis/rembg#526]
Remove results are very good for most of my inputs however some results are bad. Example:
<img src="https://github.com/danielgatis/rembg/assets/22543039/7e1cc469-823d-4b86-bf93-751e3997c308" width="300" height="300">
Expected:
<img src="https://github.com/danielgatis/rembg/assets/22543039/12dd96bf-5f55-40dd-97e0-52b37bd10af2" width="300" height="300">
Result:
<img src="https://github.com/danielgatis/rembg/assets/22543039/2e35904a-1566-428f-a104-7eded804e917" width="300" height="300">
I tried different models, different params but I couldn't make it any better. Am I missing something here?

```
from rembg import remove

input_path = '123.jpeg'
output_path = 'output.jpeg'

with open(input_path, 'rb') as i:
    with open(output_path, 'wb') as o:
        input = i.read()
        output = remove(input)
        o.write(output)
```

**Comment by Na-Cly** [comment]
Same, getting pretty poor results on basic pictures.

**Comment by dCo3lh0** [comment]
I'm on the same boat, i've installed here on my linux machine, but i'm having issue with the quality output, its more blurred, have some strange artifacts, it cuts, like it should, but the image that was cut becomes very bad and i have to use restoration techniques using the previous uncutted image to do some "history brush" and restore its previous pixel informations, it takes long and becomes worse cause i thought i could fasten my process, i do work with e-commerce products into a white background that need to be full 255 white, cant be 254, 253, full white, i can't lose too much time into a image, it needs to be very fast, and i thought rembg could help me fasten this time, but for now, isnt working for me.

![_-2](https://github.com/danielgatis/rembg/assets/21119505/e2e702e7-dcda-4457-9c2c-d1c7b32384f8)

**Comment by abhishek0093** [comment]
Has anyone found any solution to this ? I'm also getting bad results and somtimes the boundary of the foreground object isn't clear or it is blurry. Even in some cases it changes the color and pattern on the foreground object as well.

**Comment by Julrob199** [comment]
Why are problems closed after 14 days? In a world of github, closing an issue automatically solves it. This is still relevant!
