### ISSUE TITLE
zsh: no matches found: rembg[cli]

### ISSUE THREAD

**Issue by trueToastedCode** [danielgatis/rembg#527]
**Describe the bug**

**To Reproduce**

1. `pip install rembg[cli]`

**Expected behavior**
Should in stall the dependency.

**OS Version:**
macOS 14.0

**Rembg version:**
v2.0.21

**Additional context**
arm64

**Comment by danielgatis** [comment]
try this pip install "rembg[cli]"

**Comment by niraj8** [comment]
would it make sense to update the README for this?
unsure if happens only on macos
