### ISSUE TITLE
Blurred

### ISSUE THREAD

**Issue by helmutkaufmann** [danielgatis/rembg#53]
I have 3000x5000px images and the background removal works more or less nicely. However, the resulting image is blurred (the dimensions are the same as the original). Is there a parameter to address this? 
additionally, would it be possible to just output the alpha channel?

**Comment by ashkaps** [comment]
I also have the same question. 
Almost all output images are getting blurred. This example shows the difference clearly. 
@danielgatis any thoughts on what I can pursue to remove the blurry ness?
![5 (1)](https://user-images.githubusercontent.com/31744402/104337418-7af0a000-551b-11eb-9e52-8bc108d49921.jpg)
![4(2) phone - out](https://user-images.githubusercontent.com/31744402/104337447-817f1780-551b-11eb-9ede-301d5e94c008.png)

**Comment by danielgatis** [comment]
To achieve this you need to train your own models.

https://github.com/danielgatis/rembg/issues/58

**Comment by ashkaps** [comment]
Actually solved it after carefully going through the code. 
There was a hardcoded initialisation of size to (1000,1000) which was significantly reducing the quality. (1600,1600) does a good job of preserving the quality without much impact on processing time.

**Comment by danielgatis** [comment]
I pushed a fix to this:
https://github.com/danielgatis/rembg/commit/24711986b73043f20a9b15549c3bcb6e628ecf35

Tks!
