### ISSUE TITLE
[BUG] '{}' is not of type 'array' when using sam model.

### ISSUE THREAD

**Issue by trivikramak** [danielgatis/rembg#536]
**Describe the bug**
Unable to use the "sam" model in python.

Getting error: '{}' is not of type 'array'
"""
Failed validating 'type' in schema:
    {'items': {'properties': {'data': {'items': {'type': 'number'},
                                       'type': 'array'},
                              'label': {'type': 'integer'},
                              'type': {'type': 'string'}},
               'type': 'object'},
     'type': 'array'}

On instance:
    '{}'
"""

**To Reproduce**

model_name = "sam"
session = new_session(model_name)
extracted_pil_image = Image.fromarray(cv2.cvtColor(input_image, cv2.COLOR_BGR2RGB))
removed_background_image = remove(extracted_pil_image, post_process_mask=True, session=session, input_points=input_points, input_labels=input_labels)

**Rembg version:**
v2.0.52

**Additional context**
Same function call is working when model_name = "isnet-general-use"

**Comment by 1591771598** [comment]
hi,how to use sam on rembg??

**Comment by blacksino** [comment]
same,obviously a bug

**Comment by RDjarbeng** [comment]
The sam_prompt is not working. I got the same error as the original

**Comment by RDjarbeng** [comment]
The sam_prompt is not working. I got the same error as the original
