### ISSUE TITLE
Older versions (for <= python 3.7) not working

### ISSUE THREAD

**Issue by zemahran** [danielgatis/rembg#54]
My initial codebase is written for python 3.7 so I was using version 1.0.13 of the rembg package for a long time.
Two days ago I started receiving that error: `_pickle.UnpicklingError: invalid load key, '<'.`

![image](https://user-images.githubusercontent.com/29002560/103008564-0048ec00-453e-11eb-95fe-029e08c9e395.png)

I now can't even use older versions. Does anybody have a solution in mind?

**Comment by danielgatis** [comment]
The older versions have a bug when downloading the models. So, you can try download the models manually and try run.

https://github.com/danielgatis/rembg/issues/52#issuecomment-765503415
