### ISSUE TITLE
Inflates file size

### ISSUE THREAD

**Issue by mfbx9da4** [danielgatis/rembg#544]
**Describe the bug**
I have a file of size 577KB after running the command the background is removed but it's now 7.7MB any idea why?

**To Reproduce**

```
rembg i "./Photoshoot/0E9A9000.jpg" "./Photoshoot-bg-removed/0E9A9000.jpg"
```

**Expected behavior**

**Images**
![0E9A9000](https://github.com/danielgatis/rembg/assets/1690659/9c93e54c-5529-4330-8ef7-547aa6c0fcb5)

**OS Version:**
mac OS

**Rembg version:**
rembg, version 2.0.40

**Additional context**

**Comment by vaibsharma** [comment]
same issue

**Comment by mfbx9da4** [comment]
I think this is just because it's getting turned from jpeg to png.
