### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by KingOfIce77** [danielgatis/rembg#548]
**Is your feature request related to a problem? Please describe.**
Can't use rembg on my python 3.12 project

**Comment by KingOfIce77** [comment]
(to win a coffee ;-D )

**Comment by danielgatis** [comment]
https://github.com/danielgatis/rembg#when-will-this-library-provide-support-for-python-version-3xx

**Comment by HichamChlghami** [comment]
why rembg does not remove bg for complex images
