### ISSUE TITLE
sam prompting issue. Couldn't even replicate the examples

### ISSUE THREAD

**Issue by osmancakir** [danielgatis/rembg#554]
**Describe the bug**

I tried to do background subtraction following the examples in the readme file. But I don't get the same results. 

**To Reproduce**
run below command adter installing rembg cli
`rembg i -m sam -x '{ "sam_prompt": [{"type": "point", "data": [724, 740], "label": 1}] }' examples/car-2.jpg examples/car-2_sam.png`

expecting to see the examples/cars-2.out.png

but got: 

![car-2_sam](https://github.com/danielgatis/rembg/assets/35240896/ab409c08-8231-4e00-94ee-0f0936435957)

Can anyone tell me what am I doing wrong?

**OS Version:**
iOS 22

**Rembg version:**
v2.0.21

**Additional context**

**Comment by osmancakir** [comment]
> The image is 1000x667, and the prompt point was [724,740], so the model selected the segment at the bottom of the image.
> 
> Try this instead:
> 
> ```shell
> rembg i -m sam -x '{ "sam_prompt": [{"type": "rectangle", "data": [115, 225, 900, 570], "label": 1}] }' examples/car-2.jpg examples/car-2_sam.png
> ```

Do you know a way to automate this. I would like to use SAM for human portrait matting.

**Comment by Loewen-Hob** [comment]
Hi! I'm also trying to use SAM for portrait keying, and I'm a bit out of luck at the moment. looking forward to replying and exchanging ideas!

**Comment by Loewen-Hob** [comment]
@ae9is Okay okay thank you very much!

**Comment by osmancakir** [comment]
@ae9is sure, thanks for the answer ☺️ I just wanted to compare the capabilities of each model. Later I also found ModNet, for people interested, I think it is even a bit better.
