### ISSUE TITLE
[FEATURE]  add Apple Silicon / MPS support to this project.

### ISSUE THREAD

**Issue by dzeitman** [danielgatis/rembg#556]
It would be awesome if you could add Apple Silicon / MPS support to this project.    Thanks in advance for your consideration.

**Comment by dzeitman** [comment]
Any progress?

**Comment by dzeitman** [comment]
any progress

**Comment by dzeitman** [comment]
Any progress on adding the Apple Silicon support?

**Comment by 07pepa** [comment]
> Any progress on adding the Apple Silicon support?

apple is supported just neural engine acceleration is not by. Go cry there https://onnxruntime.ai/

**Comment by satial-interfaces** [comment]
You can reference a different onnx runtime, and get the acceleration you're after:

https://github.com/cansik/onnxruntime-silicon

Modify setup.py, and replace the package
