### ISSUE TITLE
MacOS: Port 5000 is used by Airplay (!$*@)#), cannot use the server on MacOS

### ISSUE THREAD

**Issue by zackees** [danielgatis/rembg#558]
I'm on MacOS 14.1 and port 5000 is always in use. This is Apple's fault. The service is used for airplay. A lot of developers are not happy since this is a common debugging port. The result is that I cannot use the http server mode in your app.

But really, this app should not be using 5000 port because it's so commonly used it's just asking for conflict.

Please move the port to an obscure port or let us specify it ourselves. Remember that anything below port 1000 on MacOS requires sudo to run. So please have a 4 digit port number.

**Comment by deltazero-cz** [comment]
Simply run `rembg s --port 5001` to run http server on port 5001 or any other

**Comment by zackees** [comment]
Thanks, this allows me to add it to my toolset. Can 5001 be the default port?
