### ISSUE TITLE
[BUG] Black background

### ISSUE THREAD

**Issue by rominasilvera** [danielgatis/rembg#564]
When trying to remove a JPG's background, the returned output is the same picture but the background is painted in black, instead of transparent or white.

### Importing modules
`from rembg import remove `
`from PIL import Image `
`import numpy as np`

### Setting path and reading image
`input_path = ".venv/Scripts/fotos_exp/AAB_0001.JPG"`
`input_image = Image.open(input_path)`

### Visualising image
`input = Image.open(input_path)`
`print(input.format, input.size, input.mode) # JPEG (2896, 1944) RGB `
`input.show()`

![AAB_0001](https://github.com/danielgatis/rembg/assets/110812887/c9c55662-db60-4a56-a7d4-735961acf811)

### Conversion and saving output file
`input_array = np.array(input_image)`
`output_array = remove(input_array)`
`output_image = Image.fromarray(output_array)`
`output_image = output_image.convert('RGB')`
`output_image.save('.venv/Scripts/output_image.png')`

![output_image](https://github.com/danielgatis/rembg/assets/110812887/86bbb802-fe30-4cfd-bbad-d5d18d9acaee)

I also tried another method, which consists on not transforming to numpy.array:
`output = remove(input)`
`output.show()`
**The output was the same**

### Versions:
`pillow                    10.2.0`
`rembg                     2.0.53`

**Comment by zhengxiongli08** [comment]
Hi, rominasilvera. Black is the default background color, because it's (0, 0, 0) in RGB mode. If you want to change the background color, please use the code below,

`output = remove(input, bgcolor=(255, 255, 255, 255))`

See more from here [https://github.com/danielgatis/rembg/blob/main/USAGE.md](url).
