### ISSUE TITLE
Anyway to fix what U2NET removes?

### ISSUE THREAD

**Issue by FASTANDEXTREME** [danielgatis/rembg#567]
### Discussed in https://github.com/danielgatis/rembg/discussions/566

<div type='discussions-op-text'>

<sup>Originally posted by **FASTANDEXTREME** January 14, 2024</sup>
Sometimes it removes objects that were not supposed to be removed. For example,
![experiment](https://github.com/danielgatis/rembg/assets/66107594/267194a9-9698-471c-873f-c41164a78ad9)
In this image, gun also got removed but it was part of the image and not background.
</div>

**Comment by danielgatis** [comment]
Nope! You need to train your own model to get more accurate results.
