### ISSUE TITLE
Add the option to choose cache directory

### ISSUE THREAD

**Issue by alexblattner** [danielgatis/rembg#568]
**Is your feature request related to a problem? Please describe.**
I'd like to deploy on replicate perfectly, but without having it download the models every time. 

**Describe the solution you'd like**
Using a cache directory of your choice to push the cache to replicate

**Describe alternatives you've considered**
Have it download again and again every time

**Additional context**

**Comment by danielgatis** [comment]
Try to set the env var `U2NET_HOME`.
take a look at: https://github.com/danielgatis/rembg/blob/main/rembg/sessions/base.py#L78

**Comment by alexblattner** [comment]
cache_dir="model_cache",local_files_only=True
