### ISSUE TITLE
[BUG]  '{}' is not of type 'array' when using sam model. 

### ISSUE THREAD

**Issue by ShylockGao** [danielgatis/rembg#569]
**Describe the bug**
Unable to use the "sam" model in cli.
 rembg i -m sam -x '{ "sam_prompt": [{"type": "point", "data": [724, 740], "label": 1}] }' .\1305696_1704870215425_1705054411.png xxx.png
Getting error: '{}' is not of type 'array'
```
jsonschema.exceptions.ValidationError: '{}' is not of type 'array'

Failed validating 'type' in schema:
    {'items': {'properties': {'data': {'items': {'type': 'number'},
                                       'type': 'array'},
                              'label': {'type': 'integer'},
                              'type': {'type': 'string'}},
               'type': 'object'},
     'type': 'array'}

On instance:
    '{}'
``` 

**To Reproduce**
 rembg i -m sam -x '{ "sam_prompt": [{"type": "point", "data": [724, 740], "label": 1}] }' .\1305696_1704870215425_1705054411.png xxx.png

**OS Version:**
window 11

**Rembg version:**
v2.0.53

**Comment by zhengxiongli08** [comment]
Hi, Gao. Have you solved this problem yet? I think I have the same problem with you.

**Comment by ShylockGao** [comment]
> 嗨，高。你解决这个问题了吗？我想我和你有同样的问题。

not solved

**Comment by AbakirH** [comment]
Does anyone know why this is happening?

**Comment by Loewen-Hob** [comment]
I have the same problem. Have you solved it?

**Comment by jalsop24** [comment]
I think it stems from the default being wrong here - https://github.com/danielgatis/rembg/blob/0dcdb080ae083de57084c38e93fb210534c5c693/rembg/sessions/sam.py#L153

**Comment by yuxi-liu-wired** [comment]
How to solve this when using it interactively on the HTTP server?

**Comment by hanqingL-bjtu** [comment]
The error reporting location should be located in
[Link Text](https://github.com/danielgatis/rembg/blob/main/rembg/sessions/sam.py#L169-L169)
It means there is a problem with the json format input of your prompt.

**Comment by kerberosargos** [comment]
Hello, is anybody help me "how to to use SAM model with library usage".

I am trying to handle as following code line but I am getting error.

`bg_cleaned_image = remove(data=my_image, session=rembg.new_session("sam", sam_prompt=[{"type": "point", "data": [724, 740], "label": 1}]) `

**Error**

```
raise error
jsonschema.exceptions.ValidationError: '{}' is not of type 'array'

Failed validating 'type' in schema:
                                       'type': 'array'},
                              'type': {'type': 'string'}},
               'type': 'object'},
     'type': 'array'}

On instance:
    '{}'
```

**Comment by aloeb-gh** [comment]
> Hello, is anybody help me "how to to use SAM model with library usage".
> 
> I am trying to handle as following code line but I am getting error.
> 
> `bg_cleaned_image = remove(data=my_image, session=rembg.new_session("sam", sam_prompt=[{"type": "point", "data": [724, 740], "label": 1}]) `
> 
> **Error**
> 
> ```
> raise error
> jsonschema.exceptions.ValidationError: '{}' is not of type 'array'
> 
> Failed validating 'type' in schema:
>                                        'type': 'array'},
>                               'type': {'type': 'string'}},
>                'type': 'object'},
>      'type': 'array'}
> 
> On instance:
>     '{}'
> ```


Hello,
Try with sam_prompt outside of the session argument.
For me it works with the following code : 

`session_rmbg = new_session(model_name="sam") `
input ect...
`output = remove(input, session=session_rmbg, sam_prompt=[{"type": 'point', "data": [1600, 2400], "label": 1}])
`

**Comment by fuaneng** [comment]
jsonschema.exceptions.ValidationError: '{}' is not of type 'array'

Failed validating 'type' in schema:
    {'items': {'properties': {'data': {'items': {'type': 'number'},
                                       'type': 'array'},
                              'label': {'type': 'integer'},
                              'type': {'type': 'string'}},
               'type': 'object'},
     'type': 'array'}

On instance:
    '{}'

## 这里的 prompt={} 应该改为一个数组
from rembg import remove

prompt = [{'type': 'label', 'data': [0.5, 0.5], 'label': 1}]
output = remove(input, prompt=prompt)

**Comment by Konstantysz** [comment]
If you are using Powershell, here might be the solution: https://stackoverflow.com/questions/70508392/how-to-add-json-object-to-arguments

**Comment by Suvoo** [comment]
> **Describe the bug** Unable to use the "sam" model in cli. rembg i -m sam -x '{ "sam_prompt": [{"type": "point", "data": [724, 740], "label": 1}] }' .\1305696_1704870215425_1705054411.png xxx.png Getting error: '{}' is not of type 'array'
> 
> ```
> jsonschema.exceptions.ValidationError: '{}' is not of type 'array'
> 
> Failed validating 'type' in schema:
>     {'items': {'properties': {'data': {'items': {'type': 'number'},
>                                        'type': 'array'},
>                               'label': {'type': 'integer'},
>                               'type': {'type': 'string'}},
>                'type': 'object'},
>      'type': 'array'}
> 
> On instance:
>     '{}'
> ```
> 
> **To Reproduce** rembg i -m sam -x '{ "sam_prompt": [{"type": "point", "data": [724, 740], "label": 1}] }' .\1305696_1704870215425_1705054411.png xxx.png
> 
> **OS Version:** window 11
> 
> **Rembg version:** v2.0.53

Did you find a solution? I am unable to run "sam" in a python file as well? Like the library approach also failed @kerberosargos @aloeb-gh

**Comment by Suvoo** [comment]
> > Hello, is anybody help me "how to to use SAM model with library usage".
> > I am trying to handle as following code line but I am getting error.
> > `bg_cleaned_image = remove(data=my_image, session=rembg.new_session("sam", sam_prompt=[{"type": "point", "data": [724, 740], "label": 1}]) `
> > **Error**
> > ```
> > raise error
> > jsonschema.exceptions.ValidationError: '{}' is not of type 'array'
> > 
> > Failed validating 'type' in schema:
> >                                        'type': 'array'},
> >                               'type': {'type': 'string'}},
> >                'type': 'object'},
> >      'type': 'array'}
> > 
> > On instance:
> >     '{}'
> > ```
> 
> Hello, Try with sam_prompt outside of the session argument. For me it works with the following code :
> 
> `session_rmbg = new_session(model_name="sam") ` input ect... `output = remove(input, session=session_rmbg, sam_prompt=[{"type": 'point', "data": [1600, 2400], "label": 1}]) `

I am getting the same issue, but I feel prompt is not the problem here :
```
input = Image.open(input_path)
model_name = "sam"
session = new_session(model_name)
output = remove(input, session=session)
output.save(output_path)
```
reproduces the same error

**Comment by manindertaggar** [comment]
This issue still exists. This issue has been closed only due to inactivity. Anyone got it to work?

**Comment by manindertaggar** [comment]
@Suvoo  You are getting that error because sam_prompt is a mandatory field.
See sam.py, Line 145
<img width="675" alt="Screenshot 2024-08-01 at 7 35 19 PM" src="https://github.com/user-attachments/assets/a4e37cd8-d0b7-4b3d-a2a2-ba724608c5ed">


Try passing the input_labels and data as follows, should work.

```python
input = Image.open(input_path)

output = remove(input,
                session=new_session("sam"),
                sam_prompt=[{"type": "point", "data": [10, 10], "label": 0}])
output.save(output_path)
```
