### ISSUE TITLE
rembg can not work with torch 1.7.1?

### ISSUE THREAD

**Issue by qinglangee** [danielgatis/rembg#57]
I installed pytorch 1.7.1 with anaconda. 
When I run `pip install rembg` it said
```
ERROR: Could not find a version that satisfies the requirement torch==1.7.0 (from rembg) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)
ERROR: No matching distribution found for torch==1.7.0 (from rembg)
```

Does rembg need torch exact version 1.7.0?

**Comment by jwgo** [comment]
I'm not a Python developer, but I can answer that,
I think it'll work normally if I set the Torch 1.7.0 Torch Vision 0.8.1.

**Comment by cnxocean** [comment]
> 
> 
> I installed pytorch 1.7.1 with anaconda.
> When I run `pip install rembg` it said
> 
> ```
> ERROR: Could not find a version that satisfies the requirement torch==1.7.0 (from rembg) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)
> ERROR: No matching distribution found for torch==1.7.0 (from rembg)
> ```
> 
> Does rembg need torch exact version 1.7.0?

try this：
pip install torch==1.7.0 torchvision==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by jinwyp** [comment]
try this：

pip uninstall torch torchvision
pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by derykti** [comment]
> 
> 
> try this：
> 
> pip uninstall torch torchvision
> pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

**It is not possible because it has an error:**

ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu
ERROR: No matching distribution found for torch==1.7.0+cpu

**Comment by jinwyp** [comment]
> > try this：
> > pip uninstall torch torchvision
> > pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
> 
> **It is not possible because it has an error:**
> 
> ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu
> ERROR: No matching distribution found for torch==1.7.0+cpu

1 check your vps network 

or 2 manually download this file below
https://download.pytorch.org/whl/cpu/torch-1.7.0%2Bcpu-cp38-cp38-linux_x86_64.whl


then run  
pip install torch-1.7.0%2Bcpu-cp38-cp38-linux_x86_64.whl
