### ISSUE TITLE
How to achieve quality like remove.bg ?

### ISSUE THREAD

**Issue by arnold408** [danielgatis/rembg#58]
Hi,
I have installed rembg.
it works nice.
However, remove.bg quality is much better than rembg.
How to achieve quality like remove.bg ?
Is there any such software like remove.bg?
Or, how to improve the quality of rembg?
thanks

**Comment by danielgatis** [comment]
You need to train your own u2net models.
https://github.com/NathanUA/U-2-Net/issues/76
