### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by zrml** [danielgatis/rembg#586]
**Describe the bug**
When I run it after installation I get
$ rembg
Traceback (most recent call last):
  File "/opt/homebrew/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/opt/homebrew/lib/python3.11/site-packages/rembg/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**To Reproduce**

1. Install for Mac M1
// I have python c3.11.5
// oxy* dependencies installed OK

**Expected behavior**
it should return the minimal help you provide

**OS Version:**
MacOS 14.2.1

**Rembg version:**
Whatever the pip install command installed on 2024-02-13.
I cannot get the version as i get the above error.

**Comment by RTeran** [comment]
Hello! I have the same trouble.
- Rembg 2.0.56
- MacOS M1 14.4.1
- Python 3.12.2
