### ISSUE TITLE
About the model of API "https://photoroom.com/api"

### ISSUE THREAD

**Issue by zhu2bowen** [danielgatis/rembg#602]
Thanks for your excellent work firstly!
I use rembg as a library, and model_name is "u2net.onnx"。I found the out image is very different from the result of API  "https://photoroom.com/api".
So, can you tell me which model the api use?
What can I do to improve the result?
Thank you very much!

**Comment by danielgatis** [comment]
@zhu2bowen the photoroom use a proprietary model, I believe it's not open-source.

**Comment by huangxianliang** [comment]
When dealing with hair edges, the effect is poor，with use model(all model)

**Comment by babakmaziar** [comment]
If there is a hole in the main object of the photo and the background is visible inside it (like a ring), rembg cannot remove the bg of that part
![images (1)](https://github.com/danielgatis/rembg/assets/16468261/c16a86ec-027e-4ebb-9d6f-3ccadf7ddcbd)

![images (1)_nobg](https://github.com/danielgatis/rembg/assets/16468261/615be4d5-4ca9-4242-a658-5d4bf149f456)
