### ISSUE TITLE
recommended CUDA, cuDNN and onnxruntime for Windows 11?

### ISSUE THREAD

**Issue by maxrottersman** [danielgatis/rembg#604]
When I first installed rembg it worked on an image.  Then it stopped working when I tried the "p" parameter.  Not sure what I did.  I keep getting errors that my NVIDIA libraries aren't talking to each other.  Like:

2024-03-07 17:04:54.4301199 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\mediapc\anaconda3\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

then... RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

Any advice greatly appreciated!

**Comment by amarillosebas** [comment]
This "D:\a\_work" directory really confuses me. Not only this is giving me errors when using rembg, when I even try to run ComfyUI's own pip.exe in the command prompt I get an error referencing that mysterious directory. It doesn't exist. The pip.exe error was fixed when I created a symbolic link to Comfy's installation directory on "D:\a\".

**Comment by halkony** [comment]
I have been encountering this bug recently as well. Full message is:

```
Error occurred when executing Image Rembg (Remove Background):

D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
```

Pretty sure I have cuDNN installed so not sure what's up.
