### ISSUE TITLE
[BUG] rembg[cli] not availible on mac

### ISSUE THREAD

**Issue by 07pepa** [danielgatis/rembg#616]
**Describe the bug**
pip3 install rembg[cli] is not availible for mac 

**To Reproduce**

1. get yourself a mac 
2. run pip3 install rembg[cli]
3. see error zsh: no matches found: rembg[cli]

**Expected behavior**
rembg[cli] is availible 

**OS Version:**
14.4.1

**Rembg version:**
latest (not related)

**Additional context**
based on dependencies there is nothing preventing this to be installable on mac

**Comment by KidJunky** [comment]
Try `pip3 install "rembg[cli]"`, with the quotes.
