### ISSUE TITLE
Usage as a library better example

### ISSUE THREAD

**Issue by bendangnuksung** [danielgatis/rembg#62]
Hi! Thank you for this amazing project. It works seamlessly out of the box. 

The example provided for **Usage as a Library** in **README** has still some dependency on the CLI to run it. 
To make it more simpler we can use numpy and PIL to read and write from the script itself. 
```python
from rembg.bg import remove
import numpy as np
import io
from PIL import Image

input_path = 'example.png'
output_path = 'removed_bg_example.png'

f = np.fromfile(input_path)
result = remove(f)
img = Image.open(io.BytesIO(result)).convert("RGBA")
img.save(output_path)
```

If you think this is a better option, I can send a PR for the same. Please do let me know.
Once again great project. 👍

**Comment by zstu-lly** [comment]
I think you provide a better example

**Comment by danielgatis** [comment]
Nice! Open the PR plz ;)

**Comment by bendangnuksung** [comment]
Thanks Daniel. Sent PR for the same.
