### ISSUE TITLE
[BUG] If there is a hole in the main object of the photo and the background is visible inside it (like a ring), rembg cannot remove the bg of that part

### ISSUE THREAD

**Issue by babakmaziar** [danielgatis/rembg#623]
The background around products such as rings or bracelets is easily removed, but the background of the middle cavity of these objects is not removed.

![images (1)](https://github.com/danielgatis/rembg/assets/16468261/c3b2c884-c02c-440f-a8ec-ac3ab550edea)

![Screenshot 2024-04-13 050541](https://github.com/danielgatis/rembg/assets/16468261/8fbec1df-1063-4065-9417-a9f278fe3854)

**Comment by BenjaminRbt** [comment]
Hello,

I do encounter the same issue as you.
I am trying to adjust `alpha_matting` configuration if it brings any improvement.

**Comment by radupoleuca** [comment]
> Hello,
> 
> I do encounter the same issue as you. I am trying to adjust `alpha_matting` configuration if it brings any improvement.

Can you please explain to me how these parameters work?

alpha_matting: bool = False,
alpha_matting_foreground_threshold: int = 240,
alpha_matting_background_threshold: int = 10,
alpha_matting_erode_size: int = 10,
post_process_mask: bool = False,

How can I know what values to give them? What are the maximum values, i.e. the range of accepted values?

**Comment by sipink** [comment]
I experience the same issue for letters also, cannot fix it.
