### ISSUE TITLE
[FEATURE] allow to add border

### ISSUE THREAD

**Issue by adbenitez** [danielgatis/rembg#624]
**Is your feature request related to a problem? Please describe.**
I would like to use this library to create stickers

**Describe the solution you'd like**
allow to set a border_color parameter or "sticker" mode that would allow to set a white border contour

**Describe alternatives you've considered**
using OpenCV instead as shown in this tutorial: https://withoutbg.com/resources/creating-sticker

**Additional context**
the stickers are generated by a bot  in a chat app and they need a white border

**Comment by nisaji** [comment]
I will try this issue 🖐️.
