### ISSUE TITLE
EP error onnxruntime error

### ISSUE THREAD

**Issue by stanleyshek** [danielgatis/rembg#640]
Try installed and ran with these error: 

![Screenshot 2024-06-17 192740](https://github.com/danielgatis/rembg/assets/4930397/43a64ee7-02ed-4a36-97ed-529a1ae49f03)

**Comment by 904557558** [comment]
I just fixed the problem by lowering my cudnn version from 9.2 to 8.9.x

**Comment by stanleyshek** [comment]
> @stanleyshek I just fixed the problem by lowering my cudnn version from 9.2 to 8.9.x

Can you show more details on how to do that?  Thanks!
Nividia only provide 9.x.x version on the website:
https://docs.nvidia.com/deeplearning/cudnn/latest/

**Comment by stanleyshek** [comment]
> @stanleyshek I just fixed the problem by lowering my cudnn version from 9.2 to 8.9.x

@904557558 
Can you show more details on how to do that? Thanks!
Nividia only provide 9.x.x version on the website:
https://docs.nvidia.com/deeplearning/cudnn/latest/

**Comment by 904557558** [comment]
> @904557558 您能详细说明一下如何操作吗？谢谢！ Nividia 仅在网站上提供 9.xx 版本： https://docs.nvidia.com/deeplearning/cudnn/latest/

@stanleyshek 
Here are the URLs for other archived versions of cudnn:
https://developer.nvidia.com/rdp/cudnn-archive

In fact, the CUDA Execution Provider section in the ONNXRUNTIME document clearly states: "ONNX Runtime built with cuDNN 8.x are not compatible with cuDNN 9.x."

This is the URL of the ONNXRUNTIME document:
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
