### ISSUE TITLE
SAM model returns inversed

### ISSUE THREAD

**Issue by francois-dibulo** [danielgatis/rembg#647]
**Describe the bug**

I tried using the SAM model to remove the background and normally I get this result (using e.g. u2netp)

![Screenshot 2024-06-30 at 14 48 43](https://github.com/danielgatis/rembg/assets/12541790/eaa367f3-c8ab-4c6a-8abc-d998d849c177)

With SAM I am getting the opposite:
![Screenshot 2024-06-30 at 14 44 18](https://github.com/danielgatis/rembg/assets/12541790/a23ab893-94a7-4b8f-ab99-22cec4305e99)

**To Reproduce**
Code:

```python
  session = new_session("sam")
  sam_prompt = [{"type": "rectangle", "data": [0, 0, width, height], "label": 1}]
  res = remove(cvImage, session=session, sam_prompt=sam_prompt)
```

**Input image**

![Screenshot 2024-06-30 at 14 52 20](https://github.com/danielgatis/rembg/assets/12541790/315774e4-dcbb-48ca-aec1-177d7ace6730)

**Expected behavior**

* Any idea why SAM returns the opposite?
* Where can I find more information on e.g. what the ``label`` property is doing?
* For those kind of images, which model is the best?

Thank you!

**Rembg version:**
v2.0.57

**Comment by StokedOnIt** [comment]
Was this issue solved as I am experiencing the same problem?

**Comment by francois-dibulo** [comment]
Sadly never found a solution

**Comment by PhocaCz** [comment]
Unfortunately, I get the same problem. The biggest pity is that the border is correct, unlike other models. But it's just the opposite.
