### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [danielgatis/rembg#657]
Hello maintainers,

Github Security Lab has found potential vulnerabilities in rembg. Please let us know what the best point of contact is to send the report. If you don't have a point of contact, you can open [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

Thanks,
Kevin

**Comment by danielgatis** [comment]
@Kwstubbs thanks.
I turned on the "private vulnerability reporting".

**Comment by Kwstubbs** [comment]
@danielgatis Hello, I'm contacting since I have not received a response in the advisory. Please let me know if you have seen it and if you have any plans regarding to fixing the issues. Thank you

**Comment by danielgatis** [comment]
working on it :)
