### ISSUE TITLE
Won't install on Windows/Anaconda 3.8

### ISSUE THREAD

**Issue by ecsplendid** [danielgatis/rembg#66]
(base) C:\Windows\system32>pip install rembg
Collecting rembg
  Using cached rembg-1.0.19.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: requests==2.24.0 in c:\users\tim\anaconda3\lib\site-packages (from rembg) (2.24.0)
Collecting scipy==1.5.4
  Downloading scipy-1.5.4-cp38-cp38-win_amd64.whl (31.4 MB)
     |████████████████████████████████| 31.4 MB 3.3 MB/s
Collecting waitress==1.4.4
  Downloading waitress-1.4.4-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting numpy==1.19.4
  Downloading numpy-1.19.4-cp38-cp38-win_amd64.whl (13.0 MB)
     |████████████████████████████████| 13.0 MB ...
Requirement already satisfied: pillow==8.0.1 in c:\users\tim\anaconda3\lib\site-packages (from rembg) (8.0.1)
Requirement already satisfied: flask==1.1.2 in c:\users\tim\anaconda3\lib\site-packages (from rembg) (1.1.2)
Collecting hsh==1.1.0
  Downloading hsh-1.1.0-py2.py3-none-any.whl (9.0 kB)
Collecting pymatting==1.1.1
  Downloading PyMatting-1.1.1-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB ...
Requirement already satisfied: scikit-image==0.17.2 in c:\users\tim\anaconda3\lib\site-packages (from rembg) (0.17.2)
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.1 (from rembg) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0)
ERROR: No matching distribution found for torchvision==0.8.1 (from rembg)

(base) C:\Windows\system32>

**Comment by danielgatis** [comment]
try this before install rembg:

```
pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by shlee7131** [comment]
Mine is Window/python3.9 and I've got this error 

pip install torch==1.7.0+cpu torchvision==0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html

ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu
ERROR: No matching distribution found for torch==1.7.0+cpu

**Comment by sburris0** [comment]
Why are exact version numbers specified in requirements.txt? If there was `torch>=1.7.0` instead of `torch==1.7.0` then I think this would work, as the available version is 1.7.1.

This is causing problems for me on linux as well

**Comment by danielgatis** [comment]
> Why are exact version numbers specified in requirements.txt? If there was `torch>=1.7.0` instead of `torch==1.7.0` then I think this would work, as the available version is 1.7.1.
> `~=` also works for minor version changes.
> 
> This is causing problems for me on linux as well

can you open a PR with these changes, plz?

**Comment by sburris0** [comment]
Sure, I'll do it tomorrow

**Comment by danielgatis** [comment]
please look at the readme.

**Comment by NexPB** [comment]
This package seems to specifically require torch version `1.7.0` but this can not be downloaded anymore through pip. Even in the readme the command specifically installs torch `1.7.1` which is not compatible with the package.

```
ERROR: Could not find a version that satisfies the requirement torch==1.7.0 (from rembg)
ERROR: No matching distribution found for torch==1.7.0
```
