### ISSUE TITLE
Cannot use GPU

### ISSUE THREAD

**Issue by hjj-lmx** [danielgatis/rembg#661]
pip install rembg[gpu]
call
from rembg import remove
from PIL import Image
input_path = 'input.png'
output_path = 'output.png'
input = Image.open(input_path)
output = remove(input)
output.save(output_path)
GPU is not running

**Comment by dicebattle** [comment]
The same goes for me. I'll write down a little more detailed environment.
OS: Ubuntu 20.04
CUDA: 12.2
ONNX-Runtime: 1.18.1
rembg: (latest)

If I launch the program in server mode and check the GPU utilisation with the `nvidia-smi` command, the GPU is not running at all. On the other hand, if I check the CPU utilisation with the `htop` command, it is using all 12 cores.

**Comment by FuzzyCatZ** [comment]
Same with me

**Comment by gongminmin** [comment]
My solution is
1. Download CUDNN v9.2, extract, put its bin into the PATH.
2. Download zlib (zlibwapi.dll on Windows), also put its path into PATH.
3. pip uninstall onnxruntime_gpu
4. pip install onnxruntime_gpu
Then it runs on GPU.

**Comment by lhh-pi** [comment]
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] 
session = new_session(providers=providers)
f = remove(image, session=session) 

You can try this. It worked for me.
