### ISSUE TITLE
The GPU is not working. `onnxruntime-gpu` does not seem to be activated in any case.

### ISSUE THREAD

**Issue by thuongvovan** [danielgatis/rembg#664]
**Describe the bug**
The GPU is not working. `onnxruntime-gpu` does not seem to be activated in any case.

**To Reproduce**

Here is the English translation of your text:

---

I am running the `rembg` library in Docker and have tried different scenarios, but it seems the GPU is still not working. `onnxruntime-gpu` does not appear to be called in any case. Nothing happens.

The Docker image `nvidia/cuda:11.8.0-cudnn8-runtime-ubi8` has CUDA 11 and cuDNN 8, which are compatible with the default `onnxruntime-gpu==1.18.1` version.

The Docker image `nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04` has CUDA 12 and cuDNN 9, which are compatible with the default `onnxruntime-gpu==1.18.1` version distributed in the Azure DevOps Feed.

Strangely, even when using an image without integrated CUDA or cuDNN, nothing happens. Usually, if using an environment that doesn't support `onnxruntime-gpu`, there would be an error log like the one below:

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************

Please check again!!

**Rembg version:**
v2.0.58

**Comment by sasachen** [comment]
how to fix?
