### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by Mikeblackbelt** [danielgatis/rembg#676]
**Describe the bug**
Whenever I open the app, it reads
"Something went wrong.
Error: Cannot read properties of null (reading '0')"

**To Reproduce**

1. Use app, click Download in 4k
2. Sign in with Github
3. See error

**OS Version:**
Windows 11

**Rembg version:**
v2.0.21

**Comment by Aciole-David** [comment]
@Mikeblackbelt,
I'm pretty sure you're mistakenly referring to another software.
This repo is for rembg, a python module, not an app.
I recommend you do a google search to find the app you're actually using.
Take care :)

**Comment by haroon423** [comment]
Check for Updates: Please ensure that you're using the latest version of the app. If there’s an update available, install it and see if the issue persists.
Clear Cache: Try clearing your browser cache or app cache to ensure there are no corrupted files causing this issue.
Reinstall the App: If possible, uninstall and then reinstall the app to see if that resolves the problem.

**Comment by Mikeblackbelt** [comment]
@Aciole-David ohh ok thanks
