### ISSUE TITLE
[BUG] client stuck on anecompilerservice execution

### ISSUE THREAD

**Issue by PasqualePuzio** [danielgatis/rembg#677]
**Describe the bug**

When trying to execute the rembg command using some models in particular (e.g. birefnet-portrait), the client gets stuck and keeps running forever. Looking at ActivityMonitor (I'm on MacOS), the process ANECompilerService is consuming 100% of the CPU.

Is that expected? How long should I expect that process to run? I've waited for several minutes but nothing happens.

Also, on the console I see the following logs:

`Context leak detected, msgtracer returned -1
`

**To Reproduce**

1. Just run `rembg i -m birefnet-portrait input.png output.png`

**Expected behavior**

I expect the client to be done after a few seconds and be able to generate an image.

**Images**

Input image is attached.

**OS Version:**

MacOS 14.5

**Rembg version:**

v2.0.59

**Comment by PasqualePuzio** [comment]
To give you more context, looks like after killing the ANECompilerService process six times, then the background removal gets finally executed with the expected result.

**Comment by PasqualePuzio** [comment]
The issue seems to be related to onnxruntime

**Comment by zhouslive** [comment]
I got the same errors on MAC: Context leak detected, msgtracer returned -1, especially when switching to the BiRefNet.
