### ISSUE TITLE
[FEATURE] Add a logo for rembg

### ISSUE THREAD

**Issue by Jack-Development** [danielgatis/rembg#681]
**Is your feature request related to a problem? Please describe.**
I am currently using rembg within many applications and presenting the usage of it. As part of that I produce diagrams to represent this process, and write "rembg".

**Describe the solution you'd like**
I think it would not only be beneficial to users, but to the project to have a logo that can be used as a shorthand in marketing or advertising of the system.

**Describe alternatives you've considered**
As I have said currently I simply write the name of the project.

**Comment by danielgatis** [comment]
It would be wonderful to have a logo, but unfortunately, I don't have the talent for that :(

Maybe someone can help with it
