### ISSUE TITLE
Cannot install due to dependencies

### ISSUE THREAD

**Issue by justsweat** [danielgatis/rembg#7]
I'm hitting an error when installing, 

ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from rembg) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.6.0 (from rembg)

**Comment by danielgatis** [comment]
Are you using x64 Python? torch does not provide binaries for x86 python distributions.

**Comment by justsweat** [comment]
Ok thanks, i'm using x86 python
