### ISSUE TITLE
[Question] I want to erase background with a folder, is it possible to set output file extension?

### ISSUE THREAD

**Issue by JIMyungSik** [danielgatis/rembg#700]
I use rembg with a folder.
There are .jpg files in the input folder, however file extension of output files are .png.
Is it possible to set the file extension of output files as .jpg?

**Comment by danielgatis** [comment]
No, because JPG does not support transparent backgrounds. I recommend that you first remove the background and generate a bunch of PNG files, and then use another tool to convert them to JPG.
