### ISSUE TITLE
Fix needed in cli.py (.out.out....png)

### ISSUE THREAD

**Issue by ecsplendid** [danielgatis/rembg#74]
Can you add this fix into your cli.py

https://github.com/ecsplendid/rembg/commit/50fa7d975b64bad0656901d9fa427a346e047571#diff-acf1eef5ef202cdf158cf8af1565d77d7c23f356f5eb4cc6b4f5ba715fda5825

This is to stop it using the previously outputted files as inputs again i.e. producing .out.out.png etc

**Comment by danielgatis** [comment]
done!
