### ISSUE TITLE
How can I use alpha matting with a python script?

### ISSUE THREAD

**Issue by TomGalla11** [danielgatis/rembg#76]
Not found any big documentation. Can somebody say me how I can use alpha matting in a python script? Without the curl.

**Comment by danielgatis** [comment]
```
rembg -a -ae 15 -o out.png in.png
```

**Comment by TomGalla11** [comment]
I mean in this script: `from rembg.bg import remove
import numpy as np
import io
from PIL import Image

input_path = 'input.png'
output_path = 'out.png'

f = np.fromfile(input_path)
result = remove(f)
img = Image.open(io.BytesIO(result)).convert("RGBA")
img.save(output_path)`

**Comment by NexPB** [comment]
@TomGalla11 the remove function takes several params on of which to enable alpha matting.

```phyton
def remove(
    data,
    model_name="u2net",
    alpha_matting=False,
    alpha_matting_foreground_threshold=240,
    alpha_matting_background_threshold=10,
    alpha_matting_erode_structure_size=10,
    alpha_matting_base_size=1000,
):
```
