### ISSUE TITLE
Doing this for videos? 

### ISSUE THREAD

**Issue by alter-sachin** [danielgatis/rembg#8]
Hi! 
Thank you for this work. I am working on videos and I extracted all frames and removed background for each frame.

This understandably takes a long time. 

Is there a way to fasten this process? Would running os.sys calls on multiple threads help? Are there other techniques that could be used.

**Comment by alter-sachin** [comment]
It takes approximately 4 seconds to run on a 480p video frame. 
The disk and RAM space used are near 20% . Is there a way to parallelize this? Would request your thoughts.

**Comment by alter-sachin** [comment]
https://github.com/aws-samples/parallelize-ml-inference/blob/master/src/ml-inference/parallize_inference_pool.py

I found this. Can this method be applied to this library

**Comment by danielgatis** [comment]
Try these steps:

* You can try to get the video in frames in parallel
* Use this project as a library and avoid to call the cli for every frame
* Change the model (pytorch) to run in parallel (https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html)

PRs are welcome ;)
