### ISSUE TITLE
Error Anaconda

### ISSUE THREAD

**Issue by fpcarva** [danielgatis/rembg#81]
Hi! how can i resolve this error when I pass this code at Anaconda promp
C:\Users\projf\Dropbox\Gui\remover-background>rembg -o 119.png 120.png

  File "c:\users\projf\anaconda3\lib\site-packages\pymatting_aot\cc.py", line 21, in <module>
    import pymatting_aot.aot
ModuleNotFoundError: No module named 'pymatting_aot.aot'

**Comment by danielgatis** [comment]
https://github.com/danielgatis/rembg/issues/35
