### ISSUE TITLE
JPEG files not supported?

### ISSUE THREAD

**Issue by Adeel-Intizar** [danielgatis/rembg#82]
Hello, Thank you for your great work
When using rembg for path/to/inputs jpeg files are not supported, it skips them

**Comment by vanDeurs** [comment]
It works for me if I fetch a jpeg image from an URL and then remove its background.

**Comment by danielgatis** [comment]
jpeg files are supported.

see this line:
https://github.com/danielgatis/rembg/blob/master/src/rembg/cmd/cli.py#L124
