### ISSUE TITLE
Extra model argument for using my own trained model

### ISSUE THREAD

**Issue by MaxGodTier** [danielgatis/rembg#86]
Hello, I'm training my own background removal model as u2net u2net_human_seg u2netp solutions don't fit my case scenario (I need pure black and transparent aliased/binary results), would you consider allowing to load a custom model from the command line (ie. -m custom_model.pth)? I love the convenience of your tool.
Also, wouldn't it be better to replace the "==" with ">=" in the requirements.txt ? The requirements are not so strict to need those exact versions, it's working fine with everything upgraded to the latest version. Last time I forgot to modify it and I had to rebuild my environment after it downgraded a lot of my existing packages.

**Comment by danielgatis** [comment]
> would you consider allowing to load a custom model from the command line (ie. -m custom_model.pth)?

This is a very interesting feature.

> Also, wouldn't it be better to replace the "==" with ">=" in the requirements.txt ?

Sure.

Can you open a PR for it, please?

**Comment by mnayef95** [comment]
It's closed before implement the first path of the question

> would you consider allowing to load a custom model from the command line (ie. -m custom_model.pth)?

Is this will be implemented?

**Comment by danielgatis** [comment]
> would you consider allowing to load a custom model from the command line (ie. -m custom_model.pth)?

I will work on that in the next few weeks. But feel free to open a PR sooner.

**Comment by suri199507** [comment]
How to save  the rembg model into pickel file

**Comment by julianadormon** [comment]
Are we able to load a custom model, yet? I am getting an error when trying to set a model other than the 3 offered.
Thanks.
