### ISSUE TITLE
any way to increase accuracy?

### ISSUE THREAD

**Issue by jdidnz** [danielgatis/rembg#9]
hey there first off thanks for putting this together. I'm trying to use it to remove the background of product photos of shoes and I need them to be remove dot bee gee level accurate... any way to 'increase the power'?

cheers

**Comment by danielgatis** [comment]
You need to train your own model. 

Take a look at here:
* https://github.com/NathanUA/U-2-Net/issues/51
* https://github.com/NathanUA/U-2-Net/issues/49
