### ISSUE TITLE
rembg-server & clear install ubuntu 20.04 lts

### ISSUE THREAD

**Issue by skvarovski** [danielgatis/rembg#95]
Dear developer, thanks for the wonderful library.

But when i install new ubuntu server and update dependence and try push POST multipart data (via PHP Guzzle),
web services answer:  "invalid query param 'model'. Available options are []"
can your fix it ?

ps. cli version work fine

---- >>>>>>>> temporary fix by author in other issue:
Download the models:

https://drive.google.com/file/d/1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ/view?usp=sharing (u2net.pth)
https://drive.google.com/file/d/1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy/view?usp=sharing (u2netp.pth)

and copy to folder ~/.u2net

. ~/.u2net
|-- u2net.pth
|-- u2netp.pth

**Comment by danielgatis** [comment]
fixed!
