### ISSUE TITLE
Issue with AWS Lambda

### ISSUE THREAD

**Issue by enricoantonini84** [danielgatis/rembg#97]
I have installed rembg in a docker image and uploaded to an AWS lambda instance.
I tried to run my script but with no luck, because of this error

`"errorMessage": "[Errno 38] Function not implemented",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
    "  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
    "  File \"<frozen importlib._bootstrap>\", line 702, in _load\n",
    "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/task/app.py\", line 9, in <module>\n    from rembg.bg import remove\n",
    "  File \"/var/task/rembg/bg.py\", line 6, in <module>\n    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf\n",
    "  File \"/var/task/pymatting/__init__.py\", line 2, in <module>\n    import pymatting_aot.cc\n",
    "  File \"/var/task/pymatting_aot/cc.py\", line 54, in <module>\n    compile_modules()\n",
    "  File \"/var/task/pymatting_aot/cc.py\", line 18, in compile_modules\n    cc.compile()\n",
    "  File \"/var/task/numba/core/compiler_lock.py\", line 35, in _acquire_compile_lock\n    return func(*args, **kwargs)\n",
    "  File \"/var/task/numba/pycc/cc.py\", line 217, in compile\n    objects += self._compile_mixins(build_dir)\n",
    "  File \"/var/task/numba/pycc/cc.py\", line 187, in _compile_mixins\n    objects = self._toolchain.compile_objects(sources, build_dir,\n",
    "  File \"/var/task/numba/pycc/platform.py\", line 137, in compile_objects\n    objects = self._compiler.compile(sources,\n",
    "  File \"/var/task/numpy/distutils/ccompiler.py\", line 90, in <lambda>\n    m = lambda self, *args, **kw: func(self, *args, **kw)\n",
    "  File \"/var/task/numpy/distutils/ccompiler.py\", line 355, in CCompiler_compile\n    pool = multiprocessing.pool.ThreadPool(jobs)\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/pool.py\", line 925, in __init__\n    Pool.__init__(self, processes, initializer, initargs)\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/pool.py\", line 196, in __init__\n    self._change_notifier = self._ctx.SimpleQueue()\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/context.py\", line 113, in SimpleQueue\n    return SimpleQueue(ctx=self.get_context())\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/queues.py\", line 336, in __init__\n    self._rlock = ctx.Lock()\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/context.py\", line 68, in Lock\n    return Lock(ctx=self.get_context())\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/synchronize.py\", line 162, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
    "  File \"/var/lang/lib/python3.8/multiprocessing/synchronize.py\", line 57, in __init__\n    sl = self._semlock = _multiprocessing.SemLock(\n"`

seems that lambda doesn't support the numpy multiprocessing.pool. Is there any alternative to use?
Regards.

**Comment by JihyeJung-Work** [comment]
@enricoantonini84  Did you solve this problem?

**Comment by enricoantonini84** [comment]
@JihyeJung-Work sort of, I have excluded the alpha matting, the feature requires the multiprocessing capabilities through numpy. I tried to build numpy from sources, with different params to disable multiprocessing.pool but with no luck.

**Comment by mr-romeijn** [comment]
@enricoantonini84 Any chance you're willing to share your Dockerfile?

**Comment by rnag** [comment]
@enricoantonini84 and others - In case it is helpful, I've created an almost identical project for AWS environments, [rembg-aws-lambda](https://github.com/rnag/rembg-aws-lambda). It strips down some code, such as alpha matting, dependencies, CLI, and downloading the `*.onnx` files. The PyPI package contains [`u2net.onnx`](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) already, so installing it or setting `U2NET_HOME` is not required anymore.

The project can be installed with:

```console
pip install rembg-aws-lambda
```

Check it out and let me know if it works for your use case. See also: https://github.com/danielgatis/rembg/issues/373
