### ISSUE TITLE
Cannot remove background from (formerly) jpg

### ISSUE THREAD

**Issue by Cold-A-Muse** [danielgatis/rembg#99]
Hi there, first of all thank you so much for this extremely helpful tool which works amazing with pngs.
I am running into an issue when dealing with JPGs where it never removes the background no matter the file.
I tried to solve this with the following code by converting the JPG into an PNG using the pillow library.  

input_file_path = f'/tmp/{base_folder}/input.png'
im = Image.open(logo_path).convert("RGBA")
im.save(input_file_path)

I am using this solution where sys.stdout.buffer.write(remove(sys.stdin.buffer.read())) is put in a python file and then running
cat input_file_path | python remove.py > rembg_output_file_path

But still no luck. What could possibly the reason for this?

**Comment by danielgatis** [comment]
Can you provide the image?

**Comment by sbairagi** [comment]
I am also stucked jpeg is notsupporting rembg package any solution would be appreciated.
